### ISSUE TITLE
Add 3 letter Greek Alphabet

### ISSUE THREAD

**Issue by watchingeyes1** [Zimtente/ens-collections#104]
"name": "3 Letter Greek Alphabet",
  "slug": "3-letter-greek-alphabet"
  "description": "The 24 letters of the Greek alphabet in 3 characters.",
  "twitter": "GreekAlphaClub",
  "website": "",
  "chat": "",
  "logo": "3-letter-greek-alphabet.png",
  "csv": ["3-letter-greek-alphabet.csv"]
}
[3-letter-greek-alphabet.csv](https://github.com/Zimtente/ens-collections/files/9041447/3-letter-greek-alphabet.csv)
![3-letter-greek-alphabet](https://user-images.githubusercontent.com/108649806/177202680-b3723f39-d9a3-471e-9878-e7f25ea0a672.png)

**Comment by CryptoGatsu** [comment]
pushed this group to main! clean submission thank you!
