### ISSUE TITLE
ADD 999 Passport Club

### ISSUE THREAD

**Issue by 999PassportClub** [Zimtente/ens-collections#105]
Hey, here is the new 999 passport community coming !
"name": "999 Passport Club",
"slug": "999 P-Club"
"description": "all flags around the world with 0-999",
"twitter": "999Passportclub",
"website": ""
"chat": ""
"logo": "999 PASSPORT CLUB.png"
![999 PASSPORT CLUB](https://user-images.githubusercontent.com/108691910/177206414-392da586-a7f6-4fd0-b2b4-d7d6c6cda0aa.png
Best regards

**Comment by tunnckoCore** [comment]
"all flags around the world with 0-999".. sorry what? :D 

Also, missing list of names, or at least examples so we can understand what it's about.

**Comment by 999PassportClub** [comment]
hey! I sent a request on git, it's all the flags in front of the numbers from 0 to 999 :) 
Exemple : 🇮🇪999 or 🇮🇪0 with all the flags!

Envoyé de mon iPhone

**Comment by 999PassportClub** [comment]
Hey ! for example, is 🇺🇸000 until 🇺🇸999.eth with all the flags :)

**Comment by 999PassportClub** [comment]
already a lot of secondary sales and some countries were mint in less than a day, we need you ahah

**Comment by tunnckoCore** [comment]
Yea, and the squatting began.

![](https://pbs.twimg.com/media/FW23UIuXoAIPrV1?format=png&name=small)

No.

**Comment by 999PassportClub** [comment]
but what's the problem ? i dont understand if there is demand
