### ISSUE TITLE
adding 999whaleclub

### ISSUE THREAD

**Issue by shnmvn** [Zimtente/ens-collections#109]
New collection come in: Whaleclub a collection of only 999whale, it will become an ens alpha.
Already got twitter and pastebin for the collection

**Comment by tunnckoCore** [comment]
> Already got twitter and pastebin for the collection

Add it then to see it.

**Comment by shnmvn** [comment]
Sure here they are:
here is pastebin:
https://pastebin.com/49vcbj2Y
here is our twitter:
https://twitter.com/999whaleclub

**Comment by tunnckoCore** [comment]
Sure, you just registered them.

**Comment by shnmvn** [comment]
ok😊
