### ISSUE TITLE
Add ENS Full Date

### ISSUE THREAD

**Issue by nftwisdom** [Zimtente/ens-collections#116]
Hello ENS.vision team! Thank you for your contribution for the ENS community. Without you we cannot get the volume as now.
Here's the info for the ENS Full Date Club. Please let me know if you need anything else.
Metadata:
{
"name": "ENS Full Date Club",
"slug": "ens-full-date-club",
"description": "1January.eth – 31December.eth",
"twitter": "@EnsFullDateClub",
"chat": "https://discord.gg/FnYyqDkmRX",
"logo": "ens-full-date-club.png ",
"csv": ["ens-full-date-club.csv"]
}

[ens-full-date-club.csv](https://github.com/Zimtente/ens-collections/files/9043448/ens-full-date-club.csv)
![ens-full-date-club](https://user-images.githubusercontent.com/108710448/177255298-fb01b175-6d77-48f7-903d-6763443f30ee.png)

**Comment by storagenf** [comment]
old 365 club now change name to ens full date after copying ENS DATE CLUB which is actually cool 1JAN.eth ~ 31DEC.eth

**Comment by storagenf** [comment]
![BMEykHg-_400x400](https://user-images.githubusercontent.com/108618688/177323352-f31c7e07-90bd-4f02-9466-53d68057bdf0.jpeg)

ENS DATE CLUb already registered on ENS.VISION & GEM.xyz

**Comment by CryptoGatsu** [comment]
pushed to main !
