### ISSUE TITLE
0x九九 Club - Add 0x Plus Two Digits Chinese

### ISSUE THREAD

**Issue by 0xdeficon** [Zimtente/ens-collections#128]
Metadata for 0x九九 Club:
{
  "name": "0x九九 Club",
  "slug": "0x九九 Club"
  "description": "0x Plus Two Digits Chinese",
  "twitter": "",
  "website": "",
  "chat": "",
  "logo": "0x九九 Club.png",
  "csv": ["0x九九 Club.csv"]
}

CSV File:
[0x九九 Club.csv](https://github.com/Zimtente/ens-collections/files/9048119/0x.Club.csv)

Logo
![image](https://user-images.githubusercontent.com/106031979/177377597-ef7f7b92-362f-47f6-a04f-ff27df49f776.png)

**Comment by CryptoGatsu** [comment]
do you mind if i rename to 0x2DigitCN? i dont think the CN language will work with naming in visual script
