### ISSUE TITLE
Add 24ClockTimes

### ISSUE THREAD

**Issue by 24ClockTimes** [Zimtente/ens-collections#129]
{
  "name": "24ClockTimes",
  "slug": "24ClockTimes"
  "description": "Collection with 1am-12am and 1pm-12pm",
  "twitter": "24ClockTimes",
  "website": "",
  "chat": "https://discord.gg/eWEdvcT5SS",
  "logo": "24ClockTimes.png",
  "csv": ["24ClockTimes.csv"]

CSV File:
[24ClockTimes.csv](https://github.com/Zimtente/ens-collections/files/9048292/24ClockTimes.csv)

Logo:
![24ClockTimes](https://user-images.githubusercontent.com/108754624/177382544-71ce93d6-457f-41e9-a081-c019bc91b02d.png)
}

**Comment by CryptoGatsu** [comment]
pushed to main!
