### ISSUE TITLE
Add "99 Temperature Club" as a new category

### ISSUE THREAD

**Issue by climatecommando** [Zimtente/ens-collections#130]
name: "99 Temperature Club"
slug: "99-Temperature-Club"
description: "The temperature range of 1-99 degrees is where water is a liquid. One degree warmer or colder and it boils or freezes. The 99 Temperature Club brings this to ENS: 99 three-digit domains each representing one degree of liquidity."
twitter: "@99_temperature"
website: "N/A"
chat: "N/A"
logo: "99-temperature-club.png"
csv: "99_Temperature_list.csv"
[99_Temperature_list.csv](https://github.com/Zimtente/ens-collections/files/9050626/99_Temperature_list.csv)
![99-temperature-club](https://user-images.githubusercontent.com/101946979/177391732-0e467166-b152-4a11-8c6b-0c132bbc792c.png)
"

**Comment by 360DegreesClub** [comment]
CSV is broken. Apologies for that. Should be fixed soon.

**Comment by 360DegreesClub** [comment]
[99_Temperature_list.csv](https://github.com/Zimtente/ens-collections/files/9050084/99_Temperature_list.csv)

This one should work.

**Comment by tunnckoCore** [comment]
>  three-digit

it's not 3-digit, it's 3-char 2 digit.

**Comment by CryptoGatsu** [comment]
pushed to main :D
