### ISSUE TITLE
Update "The 969s" club name to "Roman Numerals 969 Club" and update logo

### ISSUE THREAD

**Issue by chapoh** [Zimtente/ens-collections#131]
Please update club name to Roman Numerals 969 Club and use the following logo: ![image](https://user-images.githubusercontent.com/107825641/177410274-73f29d12-ffaf-4774-818c-f937cf727fa0.jpeg)

**Comment by CryptoGatsu** [comment]
done :D

**Comment by chapoh** [comment]
Thank you! Will the update be viewable later or should it be instant? I see it still as the 969s.

Thanks for all your hard work from you and the whole team
