### ISSUE TITLE
Add Mohi.eth to male first names

### ISSUE THREAD

**Issue by Ethereumite** [Zimtente/ens-collections#134]
**-Explanation why the item should be added/removed from a collection:** Just registered the name Mohi and should be included in the male name category.
**Collection Name:** Male First Names (MFN)
**Name of the item:** Mohi.eth
**Token ID:** 73159906359515477877111061630540902281745479588662837177004241455399776938438

**Comment by Ethereumite** [comment]
also add to collection: Surnames

**Comment by Zimtente** [comment]
thx for your patience - will be added.
