### ISSUE TITLE
Add Kanye Ens Club (all kanye song titles)

### ISSUE THREAD

**Issue by Soloxbt** [Zimtente/ens-collections#135]
{
  "name": "Kanye Ens Club",
  "slug": "kanye-ens-club"
  "description": "All kanye song titles in Ens format",
  "twitter": "KanyeEnsClub",
  "website": "",
  "chat": "",
  "logo": "kanye-ens-club.png",
  "csv": ["kanye-ens-club.csv"]
}
![kanye-ens-club](https://user-images.githubusercontent.com/108774719/177449226-d9f5ae8f-78f1-459d-aaa8-8c840b411684.png)
[kanye-ens-club.csv](https://github.com/Zimtente/ens-collections/files/9050776/kanye-ens-club.csv)

**Comment by CryptoGatsu** [comment]
pushed to main!
