### ISSUE TITLE
add "incapacitate" to english verbs collection

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#139]
Explanation why the item should be added/removed from a collection: Just registered the ENS domain "incapacitate" Incapacitate is an verb in the English language. I believe it should be added to the collection. As it means "to prevent from functioning in a normal way."

Collection Name: English Verbs

Name of the item: incapacitate.eth 

(Optional) Token ID of the item: 30500843566988049867029160597900042839078443776828752136580861246101102990754

**Comment by Zimtente** [comment]
thx for your patience - will be added.
