### ISSUE TITLE
add "pdas" to 4 Letter Dictionary collection

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#140]
Explanation why the item should be added/removed from a collection: I registered "pdas.eth" and I believe it should be added to the collection as pda is also a real word in the english language and it fits the criteria for the 4 Letter dictionary. 

Collection Name: 4 Letter Dictionary 

Name of the item: pdas.eth

(Optional) Token ID of the item: 20664665929847774942983959085846511126947634846592731346565457819549360470007

**Comment by Zimtente** [comment]
thx noted: will be added.
