### ISSUE TITLE
please add "vented" to English Adjectives 

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#141]
Explanation why the item should be added/removed from a collection: The registered ENS domain "vented.eth" should be added to the English adjectives collection because it is in fact an adjective that is commonly used in the English language. 

Collection Name: English Adjectives

Name of the item: vented.eth

(Optional) Token ID of the item: 104490515777276956367154458479681420596273822015112280645176188619675196275617

**Comment by Zimtente** [comment]
thx will be added.
