### ISSUE TITLE
Add atef.eth and atif.eth to Surnames category

### ISSUE THREAD

**Issue by khiworld** [Zimtente/ens-collections#142]
Adding or Removing Names from a Collection
To modify an existing collection, creating an issue.

Explanation why the item should be added/removed from a collection -

atif and atef are  an Arabic masculine given names generally used in the Muslim world, it means "the kind one".  it found on Wikipedia.  So please add it to your Surnames category on ens.vision!

https://en.wikipedia.org/wiki/Atif#Atef

Collection Name
-Surnames

Name of the item
-atif.eth
-atef.eth

(Optional) Token ID of the item

**Comment by khiworld** [comment]
naoi is widely used with the surnames.
https://culturetour.net/japanese-last-names/naoi1281

Collection Name
-Surnames

Name of the item
-naoi.eth

(Optional) Token ID of the item

**Comment by Zimtente** [comment]
thx will be added shortly.
