### ISSUE TITLE
Add Jessiah.eth to Male First Names category

### ISSUE THREAD

**Issue by khiworld** [Zimtente/ens-collections#143]
Adding Names from a Collection
To modify an existing collection, creating an issue.

Explanation why the item should be added/removed from a collection -

From 1880 to 2020, the Social Security Administration has recorded over 2k babies born with the first name **Jessiah** in the United States

https://www.names.org/n/jessiah/about

Collection Name
-Male First Names

Name of the item
-Jessiah.eth

(Optional) Token ID of the item

**Comment by shukaeth** [comment]
thank you, will be added!
