### ISSUE TITLE
Chinese Traditional 999 Club - tokenId

### ISSUE THREAD

**Issue by szanuje** [Zimtente/ens-collections#148]
This club has wrong csv structure, sample:

```
name, token
000, 零零零
001, 零零壹
002, 零零贰
003, 零零叁
004, 零零肆
```

**Comment by CryptoGatsu** [comment]
<img width="1174" alt="Screen Shot 2022-07-06 at 1 48 41 PM" src="https://user-images.githubusercontent.com/84987972/177640365-ba221d57-16fc-4ddd-b8ab-6e6b7e463b64.png">
looks correct to me?

**Comment by szanuje** [comment]
Hmm, there was either a commit which fixed that or I had damaged branch locally
