### ISSUE TITLE
365 club csv format

### ISSUE THREAD

**Issue by szanuje** [Zimtente/ens-collections#149]
Current format is:

```
tokenId,name
67881562657239272870075612277172731473259655004163818330025688975233396675455,april10th
```
I'd suggest to reverse the order to match `name, tokenId` as mentioned in the readme.
This will help to avoid writing complicated parsing logic when reading csv in programs
Some simple logic must be written already since there are other inconsistencies in files like different names e.g. `token` or `tokenId`, or lack of the header in csv.

**Comment by CryptoGatsu** [comment]
got it
