### ISSUE TITLE
Add Surnames to the "Surname" Category

### ISSUE THREAD

**Issue by 0x807a** [Zimtente/ens-collections#155]
Explanation why the item should be added/removed from a collection: These are all surnames of different cultures.

Collection Name: **Surnames**

Name of the item:
- hedinger.eth
- saqqaf.eth
- kensinger.eth
- kobin.eth
- joensen.eth
- beqiri.eth
- leichtman.eth
- janowicz.eth
- lebowitz.eth
- kalinsky.eth
- vandross.eth

**Comment by Zimtente** [comment]
thx will be added.
