### ISSUE TITLE
Add 2 words to "English Nouns" category

### ISSUE THREAD

**Issue by Bosfik** [Zimtente/ens-collections#167]
Reason: Expectation and Handful are both English nouns
Collection: English Nouns
Name of Item: Expectation.eth & Handful.eth
Token ID: 
43855839232727222409943310124748099731870098069842213403405988245980715596011 - expectation
37538404738617962336131858050226357439441955580080784912492286917837781596542 - handful

**Comment by Zimtente** [comment]
thx will be added.
