### ISSUE TITLE
add missing to: Nouns

### ISSUE THREAD

**Issue by hlysht** [Zimtente/ens-collections#179]
Reason: these words are noun English dictionary words.
Collection name: English Nouns
Missing names:

sufficiency
physicality
exhibitioner
demesne
extensible
flatlet
urbanity
liniment
luxemburger
merchandize
kidnaper
microsphere
pentode

**Comment by tunnckoCore** [comment]
Next time open one issue for each collection and add every missing name there.

15+ issues for similar things is making me cry

**Comment by hlysht** [comment]
already deleted. please also add urbanity.eth
physicality.eth
exhibitioner.eth
demesne.eth
extensible.eth
flatlet.eth
