### ISSUE TITLE
add to Male first names:

### ISSUE THREAD

**Issue by hlysht** [Zimtente/ens-collections#184]
reason: these names are common male first names
collection name: Male First Names
Name of the items: 

yuanjun
mohammadu
muhumed
muhammod
maties
charlse
laremy
brasco
josse
thirdy
chryst
ahmadu

**Comment by tunnckoCore** [comment]
close your other issues about male names, and add them here.

**Comment by hlysht** [comment]
alright sir. thanks

**Comment by hlysht** [comment]
josse.eth
thirdy.eth
ahmadu.eth
chryst.eth

**Comment by tunnckoCore** [comment]
Thanks.

**Comment by hlysht** [comment]
sorted out all my requests sir. thank you so much!

**Comment by tunnckoCore** [comment]
Yea, great. :)

**Comment by hlysht** [comment]
@tunnckoCore hi sir! gm. I'd just like to ask if do I still need to add more details to my request like token Id or its okay to leave it as it is? I mean, I saw few requests that was already completed which was created after my requests. Thank you sir. 🫡❤️

**Comment by tunnckoCore** [comment]
@CryptoGatsu

**Comment by hlysht** [comment]
thanks sir @tunnckoCore  please
let me know @CryptoGatsu if I need more details to my request. thank you again. 🫡❤️

**Comment by CryptoGatsu** [comment]
added :D
