### ISSUE TITLE
Adding First Names

### ISSUE THREAD

**Issue by domininft** [Zimtente/ens-collections#19]
Explanation why the item should be added from a collection: first names
Collection Name: Male first Names
Name of the items: antonello.eth, filippo.eth fiorello.eth and eolo.eth

Collection Name: Female first Names
Name of the items: letizia.eth and raffaella.eth

**Comment by danger-dane** [comment]
**Explanation why the item should be added/removed from a collection:** Add because it's a first name
**Collection Name:** Female First Names
**Name of the item:** kasy.eth
**(Optional) Token ID of the item:** 76672084728231783754988067407781471481612035626675136309580619784896875762920

**Comment by Zimtente** [comment]
noted, will be added.
