### ISSUE TITLE
add Surnames to "Surnames Collection"

### ISSUE THREAD

**Issue by pdm203** [Zimtente/ens-collections#191]
Please add the following surnames to the "Surname Collection":
Abinader
Henriquez
Gonsalez
Jaquez
Hache
Grullon
Yunen
Knupper
Doughty
Suero
Colinas
Tineo
Barcenas 
Caramillo
Zazueta
Galaviz
Mandujano
Galeana
Arguelles
Castelan
Villeda
Callejas

**Comment by CryptoGatsu** [comment]
can you send without .eth ending pls

**Comment by pdm203** [comment]
These are all common Spanish names.

**Comment by pdm203** [comment]
thank you for the suggestion CryptoGatsu

**Comment by pdm203** [comment]
> can you send without .eth ending pls

thanks

**Comment by pdm203** [comment]
Barcenas
Caramillo
Zazueta
Galaviz
Mandujano
Galeana
Arguelles
Castelan
Villeda
Callejas
Knupper
Doughty
Suero
Colinas
Tineo
Abinader
Henriquez
Gonsalez
Jaquez
Hache
Grullon
Yunen

**Comment by Zimtente** [comment]
thx will be added.
