### ISSUE TITLE
male first names and surnames requests

### ISSUE THREAD

**Issue by Soloxbt** [Zimtente/ens-collections#192]
**left side** names **right side** how many results on LinkedIn

first names
arvy - 1000
zary - 950
zackariah  - 232
woochang - 1000
micheil - 200
phip - 980

Surnames
charleton - 1300
winifield - 18000
thurstan 3100
thorndike - 1500
hamlen - 200
rufe - 352
saunderson - 30,000
bealle - 14,000 
willmott - 15,000

[first-names.csv](https://github.com/Zimtente/ens-collections/files/9059345/first-names.csv)
[surnames.csv](https://github.com/Zimtente/ens-collections/files/9059346/surnames.csv)
:)

**Comment by CryptoGatsu** [comment]
added first names, surnames are on hold till i get the file :D

**Comment by Soloxbt** [comment]
did you get access to the surnames file yet?
