### ISSUE TITLE
Add first and last names into categories

### ISSUE THREAD

**Issue by threadgirl** [Zimtente/ens-collections#193]
Name: Saryne
Category: Female first name AND last name
Token ID: 26577823136905105337999029642439388704452581593945440635217076375339984611849

Name: Merryll
Category: Female First name
Token ID: 30044374626904047135303878879985292274427096849691594584714560442357995508902

Name: Jesie
Category: Female First name
Token ID: 9873800414824127274425227131649503770645057396065705218975014483582730481859

Name: Alyahya
Category: Arabic last name
Token ID: 86879117040159503916733174296995703588076793866449254865949782167005833753496

Name: Muhanad
Category: Man first name (Arabic / turkish)
Token ID:  13848954724945606504125671258544346475241047142037058182704594008729015121333

Name: Jinane
Category: Female first name 
Token ID: 49955870509376546515976160939538311776100191492423554922039429300998898733198

Name: Christella
Category: female first name
Token ID: 51178894745171131871873611014655735199365209242959376903415475439997910985010

Name: Mikaella
Category:  female first name
Token ID: 30779330405179988922553738486126238568058056314426443170415748929616487909140

Name: Rosinia
Category: female first name
Token ID: 14246279960451215140226009328910348447748019837080835966053609091194001887243

Name: diederich
Category: german first name
Token ID: 97596438585234505766337944258866949491704615704170685904143241442681411049171

Name: Saiid
Category: male first name (arabic)
Token ID: 68739028130742035724793781620975821330194411080257264933147641487483229010504

Name: almajid
Category: last name (arab)
Token ID:  77588280863122747577717438006053616923081607139134876618153158252261724732327

**Comment by tunnckoCore** [comment]
:rocket:

**Comment by opsecx** [comment]
threadgirl!

**Comment by Zimtente** [comment]
thx will be added.
