### ISSUE TITLE
Request adding: male, female and surenames

### ISSUE THREAD

**Issue by f06eth** [Zimtente/ens-collections#196]
Name: abdulrehman 
Catagory: Male first names AND surnames
Token ID: 23936011790153999105085616277193030026734989648660056746316902998995220609545

Name: abdulqudoos 
Catagory: Male first names AND surnames
Token ID: 12812248223499553448414038459693428938182486224405627349772685438558821232103

Name: qudoos 
Catagory: Male first names AND surnames
Token ID: 61275868182045606022085043677744114302852767921622434129090617466031304874586

Name: aliha 
Catagory: Female first names
Token ID: 55867905648773441910237369853652837235035705574481405931714137364435710041638

Name: shahroz 
Catagory: Male first names AND surenames
Token ID: 98323649590643332743501743763814767316703635526071988256306972595793866964685

Name: ayzal 
Catagory: Male first names AND Female first names
Token ID: 87267317984875461040729368829367682582867008963430716950771765258544007157402

Name: ishmal 
Catagory: Male first names AND Female first names
Token ID: 67337126652279182322788916313329775602738932804328879125987507565577991398223

Name: anaiza 
Catagory: Female first names
Token ID: 66593592312345025809836297818903260495592524666641006331075025666206483875984

Name: eshmal 
Catagory: Female first names
Token ID: 6960362117904848772271428055759323614750781923487366513811197100004809063166

Name: ayzel 
Catagory: Female first names
Token ID: 77211461955940279857582667414759531185961954878113376565732747882449260308103

Name: shanza 
Catagory: Female first names
Token ID: 34866866355130001248466929155618675932566591918285408532713870112791410879438

**Comment by Zimtente** [comment]
thx will be added.
