### ISSUE TITLE
Adding to multiple collections

### ISSUE THREAD

**Issue by GFMI** [Zimtente/ens-collections#20]
Hi, 

Could you add the following names to the corresponding lists.

Reason- popular names/ words not listed

Collection 1 - Surnames
Name of items- velasco.eth, garrido.eth, markovic.eth, dixson.eth, thornburg.eth

Collection 2- Female first names
Name of items- Ammie.eth, brittni.eth

Collection 3- Male first names
Name of items- eyad.eth, dharius.eth, irineu.eth, kordell.eth

Collection 4- English nouns
Name of items- regimen.eth 

Collection 5- English Verbs
Name of items- Metamorph.eth, transported.eth

Collection 6- English Adjectives
Name of items- educative.eth, pearly.eth

**Comment by Zimtente** [comment]
noted: will be added.
