### ISSUE TITLE
Add Kole to male first names please 

### ISSUE THREAD

**Issue by chad1941** [Zimtente/ens-collections#204]
Kole is a top 1000 male name and I played baseball with a guy named Kole back in the day. 

Male first names 

[kole.eth 

](https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/90658283380897535493088161138017720279014002882651893877827648943519453996231)

**Comment by CryptoGatsu** [comment]
added :D
