### ISSUE TITLE
Add Female First Name

### ISSUE THREAD

**Issue by FotanEnergy** [Zimtente/ens-collections#205]
I picked up an expired registration today, and its a female first name. Also qualifies as a 5 letter.  I  need it added to Female First Names group

etery.eth 
Token ID: 91959617653075967432289818199836604615764670322339912897208071756679553382775

Etery is a female first name, I believe origin is Georgian. A quick search on google youll see many women named Etery.

**Comment by Zimtente** [comment]
thx will be added.
