### ISSUE TITLE
Add multiple names under Male First Names and Female First Names

### ISSUE THREAD

**Issue by Brastion** [Zimtente/ens-collections#215]
Male First Names
Egil -   https://en.wikipedia.org/wiki/Egil  https://www.behindthename.com/name/egil
Orme - Given name [Orme G. Stuart](https://en.wikipedia.org/wiki/Orme_G._Stuart) (1914–1990), Canadian businessman and naval officer https://en.wikipedia.org/wiki/Orme_(name)

The following names found on https://mumsgrapevine.com.au/2019/05/unique-boy-names/
avantee
blayden
breckett
benvineto
brodley
bannar
braythe
bayler
caeden
duggar
cortey
graylen
gallaway
heziah
gatlan
jacksyn
jailen
jenning
rhyson
wynston

Female First Names 
All found on https://mumsgrapevine.com.au/2020/05/unique-girl-names/ include:
ariellah
amryn
avyanna
ayva
arli
ee-fa
analeah
airlea
annistyn
ahmeira
breeta
brixley
amadee
annya
clydie
cambri
carlisha
dakoa
gypsi
evalina

**Comment by CryptoGatsu** [comment]
male names have been added. female names soon!

**Comment by Brastion** [comment]
> 

Your Awesome! Have a great day!

**Comment by Zimtente** [comment]
female names will be added. thx for your patience
