### ISSUE TITLE
Add Category (Ordinal Club)

### ISSUE THREAD

**Issue by mikemnm77** [Zimtente/ens-collections#217]
name: "Ordinal Club"
slug: "Ordinal-Club"
description: A web3 social club for ENS holders 1st-999th. No roadmap. Just the first 999 Ordinal numbers on the Ethereum blockchain
twitter: @OrdinalClub https://twitter.com/OrdinalClub
website: https://twitter.com/OrdinalClub
chat: https://discord.gg/HkWudGJr6m
logo: "Ordinal-Club.png" attached
csv: "Ordinal-Club.csv" attached 

<img width="303" alt="Ordinal-Club-logo" src="https://user-images.githubusercontent.com/101472365/177912849-a830f085-4aea-49c6-afc9-46e44746e9f8.png">

[Ordinal-Club.csv](https://github.com/Zimtente/ens-collections/files/9068782/Ordinal-Club.csv)

**Comment by CryptoGatsu** [comment]
pushed to main :D

**Comment by mikemnm77** [comment]
> pushed to main :D

I'm assuming that's a good thing xD
