### ISSUE TITLE
Add Schiffer to Surnames list

### ISSUE THREAD

**Issue by nastyens** [Zimtente/ens-collections#218]
Issue: Add Schiffer to Surnames list. 

Schiffer is a popular surname which in German means a "boatman", "bargee" or "skipper".  Notable People with surname Schiffer - Claudia Schiffer (supermodel) 

https://en.m.wikipedia.org/wiki/Schiffer

Collection Name -Surnames 

Name of the item 
 Schiffer.eth

**Comment by Zimtente** [comment]
thx will be added.
