### ISSUE TITLE
Add Ritchi to Male First Names

### ISSUE THREAD

**Issue by ritchieTA** [Zimtente/ens-collections#226]
Reason: Ritchi is a male give first name.
Collection name: Male First Names
Item name: Ritchi
Token ID : 15084789503184884597565870003022248645140843641135645169594378910103135768788

https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/15084789503184884597565870003022248645140843641135645169594378910103135768788

**Comment by CryptoGatsu** [comment]
added :D
