### ISSUE TITLE
please add Diegofernando to Male first names 

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#229]
Diegofernando is a spanish male first name thanks

**Comment by papafun** [comment]
this male name is one of the most common names in Colombia .. please see the attached file
https://www.bebesymas.com/recien-nacido/nombres-bebe-populares-colombia-para-nino-para-nina

domain : diegofernando.eth
token id : 100924643911830380461481638075293708350641552570738444129623886760033834121264

**Comment by CryptoGatsu** [comment]
double names are not being put in the first names category! maybe we will make another category but i honestly dont see it happening! sorry!

**Comment by papafun** [comment]
all good
