### ISSUE TITLE
Add Maripaz to the 'Female First Names' category

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#238]
Please see the attached link maripaz is a spanish female name 

https://myfirstname.rocks/baby-names/maripaz#:~:text=Maripaz%20is%20a%20name%20that,ability%20to%20persuade%20others%20effortlessly.

domain : maripaz.eth
token id : 45165117801755171129213728789701384949975177517364610192559948682109393161479

**Comment by Zimtente** [comment]
thx will be added.
