### ISSUE TITLE
Add cecie and lainie  female names to the 'Female First Names' category

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#240]
Cecie name link 
https://www.babycenter.com/baby-names/details/cecie-1631527

domain: cecie.eth
token id : 81329231745927542227790155758092057222645225577125352315617261511676591690256

lainie name link 
https://charlies-names.com/en/lainie/#:~:text=Lainie%20means%20%E2%80%9Ctorch%E2%80%9D%20(from,%CF%83%CE%B5%CE%BB%CE%AE%CE%BD%CE%B7%E2%80%9D%20meaning%20%E2%80%9Cmoon%E2%80%9D.

domain: lainie.eth
token id : 59638655629692099160726979035942044779211998550294081930594957652051182422815

**Comment by Zimtente** [comment]
thx will both be added.
