### ISSUE TITLE
add 영팔팔팔 Korean 999 Club category

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#243]
Please check that my korean number : 0888 is on the list 
https://pastebin.com/kBjF7hzN

domain : 영팔팔팔.eth
token id : 73615186242189386855530955245177535074850592627457713214605021540686220525764

**Comment by opsecx** [comment]
this number does not apply to a 999-collection

**Comment by papafun** [comment]
My mistake

Thanks mate

regards
