### ISSUE TITLE
Add multiple numbers to Hindi 10k category  category 

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#245]
domain : ०८८८०.eth
token id : 79023225962036274339688181181819551362503940892998302814049182509375356222819

domain : ००७७७.eth
token id : 50425180809102093463749293439822260001297330026784059684913441526973365255922

domain : ०००७७.eth
token id : 72584722624487067519380347531728492693921857067229973875393554640067056305777

domain : ०७७७०.eth
token id : 59945351654767561720427519724729658817249156697340677584951904438536085674036

**Comment by Zimtente** [comment]
does not belong to hindi 10k club - hindi 10k is already closed and full
