### ISSUE TITLE
Category Reguest: 99° Below Club

### ISSUE THREAD

**Issue by RemyToad** [Zimtente/ens-collections#247]
metadata:

{
  "name": "99° Below Club",
  "slug": "99-below-club"
  "description": "Minus degrees with 2 digits: −01° to −99°",
  "twitter": "99BelowClub",
  "website": "n/a",
  "chat": "n/a",
  "logo": "99-below-club.png",
  "csv": ["99-below-club.csv"]
}

logo:
<img width="400" alt="99-below-club" src="https://user-images.githubusercontent.com/108935855/178003709-92465cb1-da8a-4910-9665-ff62204a783b.png">

cvs file:
[99-below-club.csv](https://github.com/Zimtente/ens-collections/files/9072505/99-below-club.csv)

**Comment by tunnckoCore** [comment]
Please no. There was negative 10k and it didn't performed well either.

> Minus degrees with 4 Digits:

It's not 4 digits. It's 4 character length.

**Comment by CryptoGatsu** [comment]
yes i agree with above comment. dont think we will be posting this category. sorry
