### ISSUE TITLE
Please add to English Verbs

### ISSUE THREAD

**Issue by skytrader2022** [Zimtente/ens-collections#252]
Trimming.eth   token id   34324007006746482953250149713450917324420397467560825329559445902829618057583

Luxuriate.eth   token id   22305258861178334524607524635949353480769074180486728923975777488614327371779

squeezing.eth   token id   113002818667704513996629583428986264510147234261759370381479376372614914131989

smoothing.eth   token id   17165656868508641497208553562866248146625476884676899581010323723553513727407

agentive.eth   token id   67501423951262414652278338314062252499447473882792068592454236040276131318433

originating.eth   token id   17949808246375219920989769116745948838400360038902561014442491426518623447842

manned.eth   token id   25918329048604964107878607679732758473801827868543682415931183802231427489705

consenting.eth   token id   58393605203077099884772362713682490793391748017633950009689398506965604011682

gyration.eth   token id   26892271088829370443414026863254456193804204717215989000037135646723867804622

resurgent.eth   token id   53589400086671112945244936502554768161668623248979272851872999666872561396585

stinking.eth   token id   100259405578956264153382387421616180206765588425272415392841048592703795758764

jiggling.eth   token id   20878262089544686900221766899605653544321433448855717814383203749350277621795

Thank you so much

**Comment by skytrader2022** [comment]
Furthest.eth  token id  84374794675204085787548646090471920181837556441592398081324402900658166431215

**Comment by Zimtente** [comment]
added - some of them were adjectives 
impossibly is an adverb - we have no collection yet for adverbs.
