### ISSUE TITLE
Male First Names Category, please add these

### ISSUE THREAD

**Issue by skytrader2022** [Zimtente/ens-collections#253]
Kalpen.eth   token id   34813737073692841545645805160643227396506891418041103219990015638784057320700

Jasprit.eth   token id   74971881112928002805605325677679667402408312959890219527472018006702603069369

Aurik.eth   token id   61972171074773124434431223278818582244265996387039659668279125663829308981778

Seonggi.eth  token id  21439482697628460331996690247680103278107253553966196748631394361407882575089

Curlin.eth  token id   46900391114913768343666118516413951581812121943997307316153232103336472010688

Lalsingh.eth  token id   49092924748705462486033959528182955391982999163017318141924215643476621413234

Laalsingh.eth   token id   107355493110134359899039740185252804118253952705263490022751035285448136795814

Kithe.eth   token id   37954693015290511279155943163576947714884523521059092322193474270446734388227

Dijit.eth   token id   62095496975396536790674777415722105682870969906421378728547247196061002573570

Norvell.eth   token id   14972024571474591972413993375476682255918882490432602808930212596154487888696

Toruk.eth   token id   698604812781411104146984441419227197672214707131731348082605916659681438471

Torukmakto.eth   token id   95150486008080989806760634195543934868298048848794624293044571036562855345403

Tonowari.eth   token id   50321254506559945625255909927195247148702663715805879258330044959171114984500

Thank you!

**Comment by CryptoGatsu** [comment]
added :D
