### ISSUE TITLE
add kaid to 4 letter dictionary collection

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#254]
Explanation why the item should be added: It is a 4 letter word in the English dictionary.

Collection Name: 4 Letter Dictionary

Domain name: kaid.eth

Token: 35411125930536648667630766203280558348391835721291013154987307524263393261162

**Comment by Zimtente** [comment]
thx will be added

**Comment by zo16950** [comment]
Hey, just trying to figure out why “kaid.eth” was taken off the “4 letter dictionary” collection after it was added and was on it for almost a week. It is no longer on the collection. Just following up! Would love a response, thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
