### ISSUE TITLE
Validator999 club

### ISSUE THREAD

**Issue by marksteven070289** [Zimtente/ens-collections#265]
.

**Comment by AudriusHelloWorld** [comment]
validator club image
![validatorclub](https://user-images.githubusercontent.com/19314584/178209980-bd5be782-d587-4bdd-95a2-6455b55c8aaf.png)

**Comment by AudriusHelloWorld** [comment]
validator club image
![validatorclub](https://user-images.githubusercontent.com/19314584/178210349-1ba07a65-66e3-48bf-8461-332978a7ddc9.png)
