### ISSUE TITLE
Surnames addition Proposal

### ISSUE THREAD

**Issue by CryptoMikex** [Zimtente/ens-collections#266]
I would like to propose adding a few missing, yet popular, surnames. I've listed some famous people using each given surname to support this issue.

Tenpenny
- Pretty popular surname. Some known persons with that surname are Sherri Tenpenny(Activist), and Mitchell Tenpenny (Artist). 
- Surnames
- tenpenny.eth 

Rickett
- Known people with that surname are: Charles Michael Rickett (Racing Driver), Chris Rickett (Actor), Thomas Rickett (creator of the Rickett (car))
- Surnames
- rickett.eth

Meyrick
- Known: Andy Meyrick (Racing Driver), Sir David John Charlton Meyrick, 4th Baronet (rower, competed for Great Britain in the 1948 Summer Olympics)
- Surnames
- meyrick.eth

Mansell
- Known: Nigel Mansell (British Racing Driver), Jill Mansell (British Writer), Clint Mansell (British Musican and composer)
- Surnames
- 819k mentions of that surname in documents according to [ancestry.com](http://ancestry.com/)
- mansell.eth

Leyshon
- Known: Andrew Leyshon (Author), Nell Leyshon (writer), Paul Leyshon (Actor)
- Surnames
- over 101k mentions of that surname in documents according to [ancestry.com](http://ancestry.com/)
- leyshon.eth

**Comment by Zimtente** [comment]
thx very much! will be added!
