### ISSUE TITLE
Mozell.eth in wrong category

### ISSUE THREAD

**Issue by CryptoMikex** [Zimtente/ens-collections#267]
Hello!
Mozell.eth is in the Female Names category, however, I recognize this more as a male name. It’s quite popular with famous people like Mozell Williams (football player). 

Other than that - it's also frequently used as a surname. I don't know if you allow double categories. I think it should be in one of them, not female names.

I'm attaching an article about Mozell as a [surname](https://surnam.es/mozell-surname).

**Comment by CryptoMikex** [comment]
![Zrzut ekranu 2022-07-14 o 10 13 48](https://user-images.githubusercontent.com/109063902/178935313-1c966889-4610-4bc7-b7ac-b524c67d86ec.png)
Attaching this file. Register of over 2.5k uses of surname Mozell in legal documents. I could share a link if needed.

**Comment by CryptoMikex** [comment]
More, I found over 38 THOUSAND mentions of that name with gender: Male. I think that's the rightful argument.
![Zrzut ekranu 2022-07-18 o 11 11 58](https://user-images.githubusercontent.com/109063902/179480577-a86ca55d-73d9-4f94-b9cc-67a53fdabc33.png)

**Comment by Zimtente** [comment]
hi, we added it to male first names and surnames category - removed it from female first names - thx for your input. Update will be online soon.
