### ISSUE TITLE
Please add name to Pokemon Trainer Dao

### ISSUE THREAD

**Issue by skytrader2022** [Zimtente/ens-collections#272]
Shinsoku.eth  token id  15452407991439139777644253779497671745503710642348562469789355165873290689843

shinsoku pokemon movie: https://gogoanime.news/category/pokemon-movie-16-shinsoku-no-genosect-mewtwo-kakusei

**Comment by CryptoGatsu** [comment]
not a pokemon!

**Comment by danger-dane** [comment]
What do you think about including poketeam.eth in a Pokemon category? @CryptoGatsu

**Comment by CryptoGatsu** [comment]
poketeam is not a pokémon

**Comment by danger-dane** [comment]
Appreciate your input @CryptoGatsu
