### ISSUE TITLE
add 2 female first names to category (Kelci & Megen)

### ISSUE THREAD

**Issue by nftkm** [Zimtente/ens-collections#283]
-please add 2 female first names to female first names category
-male first names
-Kelci.eth & Megen.eth
-Kelci.eth token ID - [8824263355208506](https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/88242633552085062860308893630651843178331238028387214413167240926650462896896)
-Megen token ID - [3719302245020217](https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/37193022450202170793012887105996608672856674761554446297281205331021721709606)

**Comment by danavramescu** [comment]
2 more female firstnames:
krysty.eth - tokenId: 59231650795634964292265934758849645798365027962060146260576868941577364653089
krystyne.eth - tokenId: 88663026029326167694301976062876250796611430741888506711342144447497204709929
krystyn.eth - tokenId: 109058271509463974979263425529697370311062644766095921211727347507803162981109

**Comment by Zimtente** [comment]
hi thx they will be added.
