### ISSUE TITLE
names for nouns verbs adjectives

### ISSUE THREAD

**Issue by opsecx** [Zimtente/ens-collections#284]
Some names for nouns, verbs and adjectives categories. They are all proper English words belonging to these categories:

English adjectives

cumic, 22334465607708622740272736948471828714364798832582957243399994201003486109815
aflow, 69624744859784035247407605986833748337070557126928252563658397876675000424617
arest, 94190234030392408005857768236942008843505327774134421183190759960535136726336
ahigh, 60072427925345636743488384237897233047701487156417217761896849423954860970688
fumid, 7880641184541017768658509642729826836040723957816010395990987585913238121155
davidic, 39363958143682605603460436686307963644676395569097698897833947737735151421128

English nouns

accusers, 42761955622808833475074721549584784061770364084203288511859525983122967030329
elogy, 35542779759799389424343054659870359370836050826957951549342889967281779849439
culpe, 65167481918324659149850875230165384957631294902418800296527806169231303744084
biomagnetism, 68488323324891029853195801015067539636655455077729020567546997714355404544643
alcometer, 3362027350535152845216249258613754207235615087661739417066743071467369621566
debtee, 7107243178522271134493918193250730930059417933789520705100490732265613949647
darkening, 93903320017398859431275956176509086197444094369183041028153118828455942980497
rhetorics, 108813435759609740948327464211361714834456235499381935066711093541161801814918

English verbs

cabled, 82499541904016374413534771968664865400982804671695619640334435703101247846255
dabbling, 74379092385202102162680664064028462411446133723612077343787632329022651714285
berated, 31568033599270497430739983929900534643686196619236457705564530889952677905167

**Comment by Zimtente** [comment]
Hi thank you - we will add them.
