### ISSUE TITLE
add male first names to category (mustafavalery)

### ISSUE THREAD

**Issue by Dual100** [Zimtente/ens-collections#285]
please add male first name to male first names category
-male first names
-mustafavalery.eth
-mustafavalery.eth token ID - [7260043890965617616697643598162644480401571394201710829728068649140475353882]

This article talk about the most popular baby boys names in the start of the year : https://www.goodhousekeeping.com/life/parenting/a37641039/top-baby-boy-names/

**Comment by CryptoGatsu** [comment]
double names will not be added to first names category
