### ISSUE TITLE
Add Name to Male First Names & Surnames Category

### ISSUE THREAD

**Issue by Leighzhl** [Zimtente/ens-collections#288]
**Explanation why the item should be added: It is a Male First Name and also used as Surname.** Here is some reference: [https://www.google.com/search?q=andreo&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjn4-bH5PX4AhUE4WEKHeqZCkQQ_AUoAXoECAMQAw&biw=1366&bih=629&dpr=1](url)

**Collection Name:** Male First Names, Surnames, Letters

**Domain name:** andreo.eth

**Token:** 87914307345493125386502297629165967304042814917059244907096399074136833582779

**Comment by CryptoGatsu** [comment]
adding to male first names!
