### ISSUE TITLE
add a few things

### ISSUE THREAD

**Issue by hardtopickanamebruh** [Zimtente/ens-collections#291]
Andréas.eth - pls list under forename 
Sultani.eth - is both fore and surname but only listed at surname. Pls add it to forename
creditability.eth - pls add to english nouns
motobikes.eth - pls add to english nouns
sextourist.eth - pls add to english nouns
securer.eth - pls add to english nouns
securements.eth -pls add to english nouns
securement.eth - pls add to english nouns

**Comment by Zimtente** [comment]
noted, will be added
