### ISSUE TITLE
Adding names to Male names category and Surname category

### ISSUE THREAD

**Issue by mihabuki** [Zimtente/ens-collections#294]
Hi,

I'd like to have my male names and surnames added under the Male names category / Surname category on ENS vision.

The names are:
- marquese.eth (like Marquese Chriss, current NBA player),
- markieff.eth (like Markieff Morris, current NBA player),
- braian.eth (popular name in South America - especially in Paraguay, Argentina and Uruguay), 
- yerson.eth (popular name in South America - mostly in Colombia),
- kalidou.eth (popular name in Africa, like Kalidou Koulibaly who signed for Chelsea FC yesterday),
- japhet.eth (popular Hebrew name used mostly in Africa).

The surnames are:
- sarr.eth (popular surname in Africa - like 400k people says forebears.io, also a lot of known footballers with that surname),
- urrego.eth (popular surname in Colombia),
- orjuela.eth (popular surname in Colombia),
- ospino.eth (popular surname in Colombia),
- carnero.eth (popular surname in South America, 84k + people on LinkedIn with that surname),
- holgate.eth (popular surname in UK / USA /Jamaica).

Thank you!

**Comment by Zimtente** [comment]
hi thx will be added soon!
