### ISSUE TITLE
Adding a surname 

### ISSUE THREAD

**Issue by Rykzeb** [Zimtente/ens-collections#297]
MAIDANA is a very common last name mostly in Argentina. Can you please add this domain to the surname category. This one is also a prepunk. Perfect example: We all remember that famous fight between mayweather vs Maidana.

**Comment by danavramescu** [comment]
While at it, maybe add the following surnames aswell, 20k+ people having the name based on forebears

bonnin.eth
maillet.eth
jacquot.eth
harrod.eth

**Comment by Rykzeb** [comment]
Also can u please add to surname. LUFF (ex: Alison Luff, American actress).

**Comment by Zimtente** [comment]
hi thx will be added soon!
