### ISSUE TITLE
Adding Name to a Collection

### ISSUE THREAD

**Issue by ENSK1** [Zimtente/ens-collections#298]
Add Lisabeth to Female Firstnames. 

Reason:

Lisabeth is a given name and a surname. Notable people with the name include:

Given name
[Lisabeth Hughes Abramson](https://en.wikipedia.org/wiki/Lisabeth_Hughes_Abramson) (born 1955), American justice of the Kentucky Supreme Court
[Lisabeth H. Muhrer](https://en.wikipedia.org/wiki/Lisabeth_H._Muhrer), Norwegian handball player

Collection Name: Female Firstnames

Name of the item: lisabeth.eth

(Optional) Token ID of the item:

https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/79923724231990794216757068799098401430979252391606649722240105155509818436761

**Comment by Zimtente** [comment]
Hi thx will be added!
