### ISSUE TITLE
Add To The 3 Letter First Names Category Please.

### ISSUE THREAD

**Issue by punk420** [Zimtente/ens-collections#30]
**osc.eth  (oscar.eth)** 

Can you please add osc.eth to the 3 Letter First Names category. thank you.

https://en.wikipedia.org/wiki/Oscar

https://metadata.ens.domains/mainnet/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/44330984719845966317081840496030061676224271745746371102046295563309333892657

Token I.D:   **44330984719845966317081840496030061676224271745746371102046295563309333892657**

![OSC eth](https://user-images.githubusercontent.com/107779297/174463137-96757048-a8ad-4f7b-8ecc-b1be0cc944e3.png)
****

**Comment by Zimtente** [comment]
noted: will be added.

**Comment by punk420** [comment]
Hello @Zimtente any update ser? thank you!
