### ISSUE TITLE
Adding ENS To collections

### ISSUE THREAD

**Issue by mmmaaaatt** [Zimtente/ens-collections#301]
Hi there. I have created a list of a few ENS Domains that I own, that I would like added to ens.vision at your discretion - 

**Male First Names** - 
richarrd.eth (common spelling and derivative of Richard, a quick search would provide results)
Token ID - 108748704520742245452943347569647577681094795397522454897020941456556981896937

**English Nouns** (as found in Miriam Webster)
gangrene.eth
Token ID- 113777467780069348554509231974260040506538669500990077505487062371381450423036

thingamabob.eth
Token ID- 100274052131788668714462816395197691667453015740274065841356865203500733414027

**English Verbs**
rotates.eth 
Token ID- 35340872747861333987791658295765595933868753533604340515277575399374924298207

Thank you so much for your thoughtful consideration.

**Comment by topofmyclass** [comment]
would like male first names added to ens.vision
Jeymes.eth

Also female first names
Sydne.eth
Oracene.eth
Amanirenas.eth

**Comment by topofmyclass** [comment]
correction Sydne.eth should be male first name

**Comment by Zimtente** [comment]
hi thx will be added!
