### ISSUE TITLE
Please add to English Nouns

### ISSUE THREAD

**Issue by TheSnowSpider** [Zimtente/ens-collections#303]
watermelon.eth token id 98461069191880296877749143305703283260996078225027579120140417113671899922775

bonsai.eth token id 101060357396735725988691454721107179501434368059619652345276239034983118773287

forget-me-not.eth token id 10108454808454674144869726720812191389453157813169489476320855413594995680307

prohibition.eth token id 110002409969710660700018386268324373907480409370225929692057855251707298762184

sellout.eth token id 3548425775296391461149300517845962216692768036150021328017520276938690145668

bastion.eth token id 21187645305491460755594479046094254214726898686376561938313849893355060530759

blade.eth token id 28243070910862431636388898238108161550932067777657997157659982468761589191985

alchemist.eth token id 38607614556252889553955388378939240175669506014104358715415085755513013451631

handball.eth token id 22224921803003794813157871038680853403590519286432968586959627665578633990102

mango.eth token id 82305903972491008242361881560308277861449971162533184515505966788208699691174

spoiler.eth token id 23492477424048039527744487784347832918821392305665028419595306318540627731535

Thank You!

**Comment by Zimtente** [comment]
thx will be added!
