### ISSUE TITLE
Adding diasbranco and jereissati to surnames

### ISSUE THREAD

**Issue by Dual100** [Zimtente/ens-collections#315]
I would like to add diasbranco.eth and jereissati.eth they are from the richiest family in brazil.

This forbes article talk about them https://www.forbes.com/sites/andersonantunes/2014/09/18/the-complete-list-with-the-150-richest-people-in-brazil/?sh=785cfd2033da

token id 
jereissati - 56232056686552003877430049791698363903331844389746864298347500188838373282328
diasbranco - 67097901429521591792505063815406727219381627029317634026004984670673266288412

**Comment by Zimtente** [comment]
thx will be added!
