### ISSUE TITLE
Add the following names to SURNAMES please.

### ISSUE THREAD

**Issue by tshawki** [Zimtente/ens-collections#317]
Please add the following to surnames at your convenience (people listed for reference):

- Stankey (ex: John Stankey, ceo of AT&T) Token ID: 81384365910153960500387689905750053850133847763397135940960784489162899039606
- Moennig (ex: actress: Katherine Moennig) Token ID: 44969854811354087758156944788336629784578212897544636634735506938451270472537
- Bulow (ex: singer Megan Bulow) Token ID: 31070660037554497033194763889988955177157457857622034901064466268790020052885
- Wesselmann (ex: Tom Wesselmann, american artist and Coach fashion collaboration) Token ID: 103276436268328558216621293960184113641644475853472263036051000886743152458199
- Saaid (common Middle Eastern surname) Token ID: 83317850349137985568161334222819291652530220980507944463023031603934755787842
- Checkley (popular American surname) Token ID: 50530307171200010834645967433723117811348356208345331532548561388739469396355
- Steeda (American surname) Token ID: 105969813357012866343034975882747525470520583766524693658483603299200080466310
- Celesio (European surname) Token ID: 104087246901159189134151085366551725777940340224620177428250406665686412656617
- Yearns (American surname) Token ID: 57627739500203183960782157505740202136540472902330847509949143291754340519454

**Comment by Zimtente** [comment]
thx they will be added!
