### ISSUE TITLE
Please add to ENGLISH VERBS category

### ISSUE THREAD

**Issue by tshawki** [Zimtente/ens-collections#318]
Hi can you please add the following to ENGLISH VERBS:
- untwist.eth (Token ID: 53097981548868459139426802938378646246264393871265896960535736184467351385789)
- readd.eth (Token ID: 33078094348865034435874917152674426425828271903585793900361862399693063704380)
  AND also please readd.eth to ENGLISH 5L Dictionary Words
- redesigned.eth (Token ID: 9421167336205495736809845410241836457647507306336606267163519052581312760359)
- yearns.eth (Token ID: 57627739500203183960782157505740202136540472902330847509949143291754340519454)
- vectored.eth (Token ID: 29765947899308071463989566692212748062883303404321991125806830025431129240815)
- revote.eth (Token ID: 6195271257072804135228579976187768621247455650950255150694966891265135200441)

Thank you for your consideration!

**Comment by Zimtente** [comment]
Hi added them to verbs, revote is a noun added it to nouns collection.

**Comment by shawkedeth** [comment]
oops, sorry about revote. i guess i was thinking of it in an action sense
ex "i will revote on the issue" vs a noun "i held a revote this morning"
thanks for your help! the community greatly appreciates your hard work. :)
