### ISSUE TITLE
please add my 2 female first names (kelci and megen) to category 

### ISSUE THREAD

**Issue by nftkm** [Zimtente/ens-collections#32]
hello can you please add 2 of my female first name ens domains to the female first name category? they are kelci.eth and megen.eth 

kelci.eth - https://opensea.io/assets/ethereum/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/88242633552085062860308893630651843178331238028387214413167240926650462896896

megen.eth - https://opensea.io/assets/ethereum/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/37193022450202170793012887105996608672856674761554446297281205331021721709606

thanks!

**Comment by Zimtente** [comment]
noted: will be added.
