### ISSUE TITLE
Please add gigworkers.eth to ENGLISH nouns

### ISSUE THREAD

**Issue by tshawki** [Zimtente/ens-collections#320]
Please add gigworkers.eth to English Nouns category (already in Pre-Punks)
Token ID: 8641596641854459668768738106497721402234966356718690890710643068111380299417

gig workers [noun] (https://www.merriam-webster.com/dictionary/noun)
plural gig workers
Definition of gig worker
: a person who works temporary jobs typically in the service sector as an independent contractor or freelancer : a worker in the gig economy

**Comment by Zimtente** [comment]
thx will be added
