### ISSUE TITLE
Please add neurosurgeons.eth to English Nouns

### ISSUE THREAD

**Issue by tshawki** [Zimtente/ens-collections#321]
Please add neurosurgeons.eth to ENGLISH NOUNS category (Token ID: 101282548972693560407123707013451653379930555918491212698605892240336500368920)

neu·ro·sur·geon
/ˈn(y)o͞orōˌsərjən,ˈn(y)ərəˌsərjən/
noun
plural noun: neurosurgeons
a surgeon specializing in surgery on the nervous system, especially the brain and spinal cord.
"one of the most respected neurosurgeons in North America"

**Comment by Zimtente** [comment]
thx will be added!
