### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by themichaelk** [Zimtente/ens-collections#323]
Hello, 

I am Errol. Hope to find you all builders well. I tried this before with little success, but after seeing I have more widely used and correct versions of names in the category, I think it was time to try this.
The names I have are: Álex.eth (the correct form for Alex in spanish), Paúl.eth (the correct form for paul in spanish) Óliver.eth (I saw olivér, and the correct writing according to the RAE is Óliver because it is "esdrújula"), and last but not least, Jehová.eth (the correct spanish form for jehova, a common name for God in the Judeochristian tradition.

I'd appreciate your help with this very much, and I understand it can take time. I would just love it eventually happens, in other words, at least to get in line :).

If there is anything you need to support this let me know. 

Thank you ens.vision team.

Errol

**Comment by themichaelk** [comment]
Please, also stackpool.eth as a surname, lashauna.eth as female name, and giordan.eth as a male name and surname :)

**Comment by themichaelk** [comment]
Lmao since I'm here, if you have time, please add grohmann.eth as surname, and licensure.eth as English noun (can't believe this one is missing!)

**Comment by CryptoGatsu** [comment]
added :D

**Comment by themichaelk** [comment]
Thank you you beast
