### ISSUE TITLE
Add to Surnames Club

### ISSUE THREAD

**Issue by buffalokid7** [Zimtente/ens-collections#33]
Hello, just writing to see if these clean surnames qualify for the Surname Club on Ens.Vision I believe with the exception of Perry's the others should definitely qualify.

Cellino.eth
Fuccillo.eth
Radwell.eth
Perrys.eth

**Comment by topofmyclass** [comment]
pieters.eth 33k+
albu.eth 33k+
coffie.eth 24k+
Exantus.eth 12k+
landaverde.eth 28k+
mccullum.eth 3,700+
sudirman.eth 22k+ pre punk
jiminez.eth 5k+ 
ginn.eth 14k+
grisham.eth 9k+
saucier.eth 11k+
gooden.eth 20k+
leatherwood.eth 5,900+
grandy.eth 5,900k+
woullard.eth 401+
mcbroom.eth 6,600+
swanier.eth 180+
dedeaux.eth 1,600+
howze.eth 4k+

hey writing to see if these names qualify for surnames collection at least 9k+ names

**Comment by Zimtente** [comment]
noted: will be added.
