### ISSUE TITLE
Please add these domains to SURNAMES category

### ISSUE THREAD

**Issue by danny-42** [Zimtente/ens-collections#333]
svane.eth
https://en.wikipedia.org/wiki/Rasmus_Svane
108075549783742705537996502124933282579074023176525751308097644795168816206953

screwvala.eth
https://en.wikipedia.org/wiki/Ronnie_Screwvala
5094406677066319811630088828353836464760283574814766541967403665906360362265

sidhwani.eth
https://en.wikipedia.org/wiki/Ritesh_Sidhwani
74773496159658458489430603342163058436459811563996457267233112860560178332974

chanchlani.eth
https://twitter.com/ashchanchlani
22269370982356178081149202706840228994063772661605390634191656242033023074796

lalwani.eth
https://en.wikipedia.org/wiki/Lalwani
43161362517448473118892758070929753920906277280847097494885483694331604156217

khubchandani.eth
https://en.wikipedia.org/wiki/Kareem_Khubchandani
57806638357283179598872533786498902265426673952956160018781406943734347196321

rochlani.eth
https://www.linkedin.com/in/neelam-rochlani-9150677/
22601638214714143047490712657489492602072658596945834422351483573510317096464

gangwani.eth
https://en.wikipedia.org/wiki/Sanjay_Gangwani
18720829105664972121484599181462142001032025439267096129202224186955971905780

**Comment by Zimtente** [comment]
hey thx will be added!
