### ISSUE TITLE
Please add these domains to MALE FIRSTNAMES category

### ISSUE THREAD

**Issue by danny-42** [Zimtente/ens-collections#334]
emraan.eth
https://en.wikipedia.org/wiki/Emraan_Hashmi
86988343822898415523074107510473584911888969358366955031820816380818242637596

boman.eth
https://en.wikipedia.org/wiki/Boman_Irani
49762593545035675968015423583267412278930042500909458202555158462675562661708

papon.eth
https://en.wikipedia.org/wiki/Papon_(singer)
28939967862224346354039214060375576942041508952782709602517500760303401869733

mohmmed.eth
https://en.wikipedia.org/wiki/Muhammad (Alternative spelling of Prophet Muhammad)
56184726372712019224069656464071448213238162503979621392044353324853598443667

muhummad.eth
https://en.wikipedia.org/wiki/Muhammad (Alternative spelling of Prophet Muhammad)
18815916975753843378461281458519163977821755335497923892968487639076331561817

muhmmad.eth
https://en.wikipedia.org/wiki/Muhammad (Alternative spelling of Prophet Muhammad)
21770448783970229757888013751641500530897411962920837167862119536394164739179

**Comment by CryptoGatsu** [comment]
added :D
