### ISSUE TITLE
Please add these two ENS domains to First Names & Surnames 

### ISSUE THREAD

**Issue by BMcGibs** [Zimtente/ens-collections#337]
Can you please add Mavy to First Names for Male & Female?

https://www.babycenter.com/baby-names/details/mavy-1313791
https://myfirstname.rocks/baby-names/mavy#:~:text=Mavy%20is%20a%20name%20that,in%20your%20quest%20for%20truth.

Can you please add Jacson to Surnames?

Jacson: 

https://www.houseofnames.com/jacson-family-crest#:~:text=The%20distinguished%20surname%20Jacson%20first,%22a%20son%20of%20Jack.%22

https://www.ancestry.com/name-origin?surname=jacson

**Comment by Zimtente** [comment]
thx will be added!
