### ISSUE TITLE
Add two new male names

### ISSUE THREAD

**Issue by chapoh** [Zimtente/ens-collections#34]
Can these two male names please be added to the list?

Jahmal: https://opensea.io/assets/ethereum/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/80595741641890356714503554011151937174723207073771524575441481288133007351281/

Treyshawn: https://opensea.io/assets/ethereum/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/7414413851529991001173951100397152468101758030288598702630303965927942435469/

**Comment by schnapseth** [comment]
Please also add:

adnan
ismael
vittorio
haytham

thanks!

**Comment by Zimtente** [comment]
noted: will be added.
