### ISSUE TITLE
Add-Dragon-Ball-Z-Characters

### ISSUE THREAD

**Issue by SterlingENS** [Zimtente/ens-collections#340]
[DBZ-Characters.csv](https://github.com/Zimtente/ens-collections/files/9145371/DBZ-Characters.csv)
![DBZ-Characters](https://user-images.githubusercontent.com/109633843/179867540-852e6ce8-537e-48c0-a74d-29dcb90853f6.png)
{
  "name": "DBZ-Characters",
  "slug": "DBZ-Characters"
  "description": "Characters appearing in Dragon Ball Z.",
  "twitter": "",
  "website": "",
  "chat": "",
  "logo": "DBZ-Characters.png",
  "csv": ["DBZ-Characters.csv"]
}

**Comment by CryptoGatsu** [comment]
added :D
