### ISSUE TITLE
Please add pedometer.eth to English Nouns

### ISSUE THREAD

**Issue by eviscerate-eth** [Zimtente/ens-collections#342]
Category: English Nouns

ENS: pedometer.eth

https://www.dictionary.com/browse/pedometer

[ puh-dom-i-ter ] noun

Definition: an instrument worn by a walker or runner for recording the number of steps taken, thereby showing approximately the distance traveled.

I <3 ens.vision

eviscerate.eth

**Comment by eviscerate-eth** [comment]
Token ID: 61007682987200881781722167531931889323132677326485186760991139940335104253690

**Comment by Zimtente** [comment]
thx will be added!
