### ISSUE TITLE
Change the profile picture of: 999 CN club

### ISSUE THREAD

**Issue by shnmvn** [Zimtente/ens-collections#350]
![nuovo](https://user-images.githubusercontent.com/108611775/180047167-1d7fe215-9237-47a1-9997-f96e7644076a.png)
Hi team, I want to ask you is it possible to change our club profile picture with this, thank you already🤝

**Comment by shnmvn** [comment]
![nuovo](https://user-images.githubusercontent.com/108611775/180047594-4ab6a5dd-a866-4c62-8f98-cebc6f5c648d.png)
ok no sorry, this is the right one, ignore the first( I wrongly put the CLub) this is the right picture:

**Comment by Zimtente** [comment]
hi thx this was added on 1th of august, will close this issue now :)
