### ISSUE TITLE
Please add to Male first names 

### ISSUE THREAD

**Issue by skytrader2022** [Zimtente/ens-collections#352]
Ravell.eth  token id  10764227272493966415817369316696912500575135218365509134269448613473374696647

Gere.eth  token id  85358228228727667200723101222774293513883725614868387157059459883392782774185

Djawadi.eth  token id  15990810679229711038555378452254024798377853408382630802067045564564844079736

Quaritch.eth  token id  78621020057837875906422891005143829897092766488990117463437461342189127339291

Tonowari.eth  token id  50321254506559945625255909927195247148702663715805879258330044959171114984500

Branford.eth  token id  71584025987106715559645396079426809066567604250723393505860256481323661657981

Punjabimc.eth  token id  1129170746791915734016158369585240407133510633053321324118640754503217467489

Thank you!

**Comment by Zimtente** [comment]
thx will be added!
