### ISSUE TITLE
Please add Pirry as a male firstnames category

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#374]
Hi guys 
could you please add Pirry as a male firstnames category

name: pirry.eth
token id : 34111308916182187182428008738841809642920099246407860064475324464280436732292

data : 
https://forebears.io/forenames?q=pirry
https://www.namespedia.com/details/Pirry

Thanks again !!

**Comment by Zimtente** [comment]
hey will be added! thx
