### ISSUE TITLE
Male first name addition

### ISSUE THREAD

**Issue by az19-eth** [Zimtente/ens-collections#389]
Please add these male first names as they are very common names not included in this list yet.
These a common names for p**eople of color and eastern Europeans** but have not been included in **Male Firstnames** category

{
  "antonne": "28115004429935029868152347816337843292838817726065810101816483826056499139665",
  "colijn": "4210261310696987234556808350833580276135099581896906085192268477923520842623",
  "aneeldeep": "75089692856748486257011828491165732944850533945638931364962935001163509564630",
  "harbir": "2906030263001526994483133848393586286151980053007313854541799663584783044288",
  "prajith": "101044752605837448863485556417690126773454376230729980529343602161930099344724",
  "quandre": "82568927385179612091032734146019682483320229706510830306116469129410936807791",
  "vardym": "95013067692809638084990394315605406216415480858036752591933892761868585625591",
  "yosef": "92611822504722312647855849079286714078223734980927652584132126967615410263655",
  "kevlin": "93047700420128759113026204608150399785222602903801492231099477503001815001437",
  "stanyslav": "61355463302032483299505541395273921575777478267743409519669094853463610786235"
}

**Comment by Zimtente** [comment]
thx will be added!
