### ISSUE TITLE
Spelling Change in Harry Potter ENS

### ISSUE THREAD

**Issue by Sexadegen** [Zimtente/ens-collections#39]
seamusfinnegan.eth is misspelt.

It should be 

seamusfinnigan.eth

I would be grateful if you could make this change.

**Comment by forzaphil** [comment]
@CryptoGatsu It's still showing as seamusfinnegan on Ens.vision

**Comment by CryptoGatsu** [comment]
<img width="1391" alt="Screen Shot 2022-07-06 at 1 17 42 PM" src="https://user-images.githubusercontent.com/84987972/177635585-2d687d56-7594-4b33-9198-84b63ede188c.png">
its been fixed tho!
