### ISSUE TITLE
Add these high use last names to surnames category

### ISSUE THREAD

**Issue by ledegend** [Zimtente/ens-collections#392]
hassane,80446582122986029313677708848416073750417677895711165458155942163655681703877
mouhammad,1465659985192092875452857671085183500811167390702758592969173906736140561276
ahimed,58107674453353606517456023742387826731669479254518501247651762812831703143720
abdulai,108087377483484926087818968549940031293765108488257763834692572564591725024598
wolfhart,101304938779159148730163723247911937409511825416413453407309373640613417272755
friederich,74332061868730951848209131468860331494541266389134511205481096986118621960601
godfried,51880835397117767813961956179340779194165992469698785643260835463130593733704
choudry,55343666024933151958811004977802444668504214275607342355442275728838836160680
babacar,92612784803564365083019738028337693121041265338759248952553493772116654488044
abreham,3969434445414923441333673538727785561934466601503781924845157111857525629918
ganes,64355826557996562884935781580429369260440884019202167055146684411392625216190
getahun,97752131558455575499878836240869249941796811003577938624584185929934385111770
aissatou,35710320623071974556404943544027180042857903444164022922687867608652477967170
kadiatou,102846012208619747009696088268568427939456582248352369646303574897199384741944
julião,473041132794745744126323099003393724898812095428792827178799749466150217360
sandar,28150468965782864613196060579891893518892336696392693012388715351564789828069
axara,30084688469248243674828254744175069260020746402580593178058238564246526690488
lúcia,76304298682484596683578599540379571309493757341066683615587771756345457341280
tahera,60848098431472578438206658164935520988140859491063634247738790112851645100529
amera,96227745728820811457779349088071274917632837602488358453025760886740686900193
asalam,114244091869853424535866510351824028434122278988010915262087100483479086995249

**Comment by Zimtente** [comment]
thx for waiting, will be added shortly!
