### ISSUE TITLE
Add preparatory.eth to English adjectives

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#399]
Explanation why the item should be added: Preparatory is a common adjective used in the english language. It means serving or carrying out a task or preparing for something. Example: "preparatory school"

Collection Name: English Adjectives

Name of the item: preparatory.eth

Token ID: 71879040029210352034567432907916860343000518956331681507574896395659263043839

![image](https://user-images.githubusercontent.com/103213586/180629451-2ed79a90-d418-4eba-9894-e84525da6bf2.png)

**Comment by Zimtente** [comment]
thx will be added!
