### ISSUE TITLE
Add 3-Letter to additional categories

### ISSUE THREAD

**Issue by Choiseul13** [Zimtente/ens-collections#41]
Good Morning. 

Looking to see if we can add zyv.eth to the following categories:

    3 Letter First Names
    Male First Names

Currently item exists in 3 Letters category

zyv.eth
https://opensea.io/assets/ethereum/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/3379863499264520644943699427214493173151279749026532909779892798982219995132/

Zyv (Name)
https://www.explorebabynames.com/meaning-of-zyv

Thank you

**Comment by Zimtente** [comment]
noted: will be added.
