### ISSUE TITLE
Please add these words into "English Nouns" category

### ISSUE THREAD

**Issue by Emhacko** [Zimtente/ens-collections#417]
I kindly ask you to add following words into "**English Nouns**" category as all of them are nouns.

**Collection Name**: English Nouns

**Words**:

- geniality
- playfulness
- unwillingness
- disinclination

**Personal Name**: 

- geniality
- playfulness
- unwillingness
- disinclination

**Tokens IDs:**

Geniality - 64893311480532098335645871994260164916244394038789244993083772047644093647391
Playfulness - 103386104606229865870922531520018126508312650575031949157995317026875067670411
Unwillingness - 104037239783192193674345008956249036509348115455641505459554243410983693017320
Disinclination - 54781897275546104883858594847493331536484291044913431773629543330903369283007

Thank you in advance.

**Comment by Zimtente** [comment]
hi thx will be added!
