### ISSUE TITLE
Add to Female First Names

### ISSUE THREAD

**Issue by echoghi** [Zimtente/ens-collections#419]
- Collection: Female First Names
---
- Name of Item: marìa.eth
- Token ID: 16186871001000572297705069733042453149492855999198013979664988800388346498749
---
- Name of Item: danìela.eth
- Token ID: 81348531249179661968238357467232004979823842480811676623493892830387955242047
---
- Name of Item: tañia.eth
- Token ID: 113315625197895464255022196302335561798055767425686085630780538838740633810417
---
- Name of Item: guadalupé.eth
- Token ID: 26553307866920753987791107219076422299030373035600272343990436253769763939231
---
- Name of Item: olivía.eth
- Token ID: 65339792976972807114536248853455577737947285542780691309883650225217108781024
---

**Comment by Emhacko** [comment]
This is stupid. I would not add names with same different symbols. You can make hundreds of them. There are already very strange names in the category that are morelikely typos.

**Comment by opsecx** [comment]
most of these have the wrong accents or in the wrong places.

**Comment by Zimtente** [comment]
hi thx yes we added those!
