### ISSUE TITLE
Please add these domains to ENGLISH NOUNS category

### ISSUE THREAD

**Issue by danny-42** [Zimtente/ens-collections#426]
laminates.eth
31826386325882127134934746817585221283390941187007593258998230401321349979741

brades.eth
59208230517780241399579621346856427284233348833820879636306719625879342917469

**Comment by Emhacko** [comment]
laminates is plural noun, not noun.

same applies for brades if I am not wrong.

Cmon people, list proper words only please. Plurals etc. do not belong into categories.

**Comment by Zimtente** [comment]
thx we will add those to plural nouns
