### ISSUE TITLE
first names and surnames for categories

### ISSUE THREAD

**Issue by opsecx** [Zimtente/ens-collections#427]
Hi, here are a few more names for adding to categories:

male first names:

delwin, 32663610891767703042453784951458119505269009396923475818558098702287954259949
donaciano, 30973159460364881613799750061417619159732579087483627117203380690380153057282 
thedore, 14511138368050464210377251625849795023708629300512311546848115741915789732848

female first names:

renada, 42689841386284206542203017785745172930598663181939791888654039416864829298085
tenika, 20538130120195122553182622515934533382432311772804067838964325635515005845534
theodocia, 68527784192453200067086113592939886572167995746372118706580048288662745229637

surnames:

dampier, 443350739797378925920788706927178171447439678390083819677398066446438038322
gigliotti, 10046564583756568784415897604202927771721157307381673797083645634336993324787
goodrow, 67015305569910934726474609024645030376641387121144370728157107370996133462926
grabow, 49619933412933699981233540068585994468713427198079407731026871533557488848298
greenhalgh, 12525279497215397549455355886957548696943053062494213860476008692118776518441
gurule, 39464008858377756055630966616738990542490117084829106341829902252250150434096
halterman, 95163378572710355153083983128867204116348433613392949853220209598120830479276
hermanson, 38726230987605786853154123823934465944075366878680314064577697273646166257934
hessler, 106944599136047419838977217230178880286004889280419268275564247692602465712902
hornberger, 47856931607528850935115646010477342482399927450390335366204119323699091576238
kentfield, 339460907796978988296007743468058812847662645647473656181522986001957324707

**Comment by Zimtente** [comment]
thx will be added!
