### ISSUE TITLE
request to add to double ethmoji club (Length 4/Segment Length 2), thnx

### ISSUE THREAD

**Issue by PmCanary** [Zimtente/ens-collections#428]
👪🏼👪🏼, 39491658419518107599514131873095305403384131273564873354214796368665659796381
👪🏾👪🏾, 106013883174817159954522074450825200080107824380421395877434323198151464266783
👪🏽👪🏽, 44961513207740766576139630906227958255367236394112346804510339721989295703983
👪🏿👪🏿, 850462122742900269302013492021581756680798666572444604695370134283337944870
👪🏻👪🏻, 17276764822726285556750870097520114265442832536826867165864252801645303131730

**Comment by PmCanary** [comment]
[double ethmoji req.txt](https://github.com/Zimtente/ens-collections/files/9192304/double.ethmoji.req.txt)

**Comment by PmCanary** [comment]
just a heads up, not a true triple ethmoji. yours is 6 characters in length, needs to be 3.

**Comment by Zimtente** [comment]
hi thx will be added!
