### ISSUE TITLE
these surnames are missing surnames from top 4k list

### ISSUE THREAD

**Issue by Rosan07** [Zimtente/ens-collections#43]
**(updated I have posted new list above and updated here too)**
These surnames are among top 4000 surnames in world but are missing from ens vision

Shaibu (shaibu.eth) - 2657th most common name in world with 209,483 people using it
Birhanu (birhanu.eth) - 1602nd most common surname in world with 339,000 people using it
Husen (Husen.eth) - it is the 1770th most common surname in world with approx 309,000 people using this surname
Rohman ( Rohman.eth ) - It is the 2490th most common surname with over 222,000 people using it
Thet (Thet.eth) - 1180th most common surname with approx 451,000 people using it
utomo (utomo.eth) - 3366th most common surname in world with approx 166,000 people using it
Tsehay (tsehay.eth) - 1406th most common surname in world with approx 381,900 people using it
Tilahun (tilahun.eth) - 1347th most common surname in world with approx 401,000 people using it
Sibanda (sibanda.eth) -1720th most common surname in world with approx 319,000 people using it
Thandar (thandar.eth) - 1490th most common surname in world with approx 361,000 people using it
Kedir (kedir.eth) - 1680th most common surname in world with approx 327,000 people using it
Kozlova (kozlova.eth) - 2543rd most common surname in world with approx 217,000 people using it
-Belova (belova.eth) - 3567th most common surname in world with approx 157,000 people using it
### Shaibu, Birhanu, Husen, Rohman , Thet, Utomo, Tsehay, Tilahun, Sibanda, Thandar, Kedir, Kozlova, Belova

**Comment by Zimtente** [comment]
noted: will be added.
