### ISSUE TITLE
Please add these domains to ENGLISH NOUNS category

### ISSUE THREAD

**Issue by Puggyback** [Zimtente/ens-collections#431]
Category: English Nouns

Domain: talaria.eth

https://www.merriam-webster.com/dictionary/talaria
[ta·​lar·​ia] noun (plural only)

Definition: winged shoes fastened to the ankles and chiefly used as an attribute of the god Hermes or Mercury of classical mythology

Token ID :42711693139837879030621175781452763887844997752110638673136044657721592380815

Domain: misophonia.eth

https://www.merriam-webster.com/dictionary/misophonia
[mis·​o·​pho·​nia] noun

Definition: a condition in which one or more common sounds (such as the ticking of a clock, the hum of a fluorescent light, or the chewing or breathing of another person) cause an atypical emotional response (such as disgust, distress, panic, or anger) in the affected person hearing the sound

Token ID :42391342436675164633624908824509804465046962023600595787202809377073914848708

Thank you

**Comment by Zimtente** [comment]
thx will be added!
