### ISSUE TITLE
Please add these domains to SURNAME category

### ISSUE THREAD

**Issue by basestation-eth** [Zimtente/ens-collections#433]
Hi, please add these domains 

Surname:

butterwick, 10214208871444935780320736443820308495736797305428680267588449290161300345699
bidd, 13205519562174385027242695601046034114422055887874366472507563128211315472350
cete, 21963067233414375591038226562491326779921819973771320789136736564127634465458
fanks, 88779264578896394412710889804841605457182710644398800886055988264041421054486
airoh, 99815185325084214190319383217343382240964673777070025824256977479853181959353
allenby, 91285731555686562362677185224790896955688121105609269708706745363178621116263
kurby, 100670988362953059814859219030788815865624684244355128823251214936168982409279

**Comment by basestation-eth** [comment]
![image](https://user-images.githubusercontent.com/110099007/183014676-9474f592-8467-451c-8b5e-ce9337cfb257.png)
![image](https://user-images.githubusercontent.com/110099007/183014730-8edc4aa5-3fa4-4ce2-ada2-0f0f2c2d29a4.png)
![image](https://user-images.githubusercontent.com/110099007/183014778-5cb82817-0df7-4ab6-b7fb-f8e840b17a4c.png)
![image](https://user-images.githubusercontent.com/110099007/183014818-41d57670-d35c-4c9d-a3f0-cd46c84f1c83.png)
![image](https://user-images.githubusercontent.com/110099007/183014857-5ee5b132-f54f-4df0-849b-30c675ba9d90.png)
![image](https://user-images.githubusercontent.com/110099007/183014874-418478a5-3a30-4257-a389-a8578003140f.png)
![image](https://user-images.githubusercontent.com/110099007/183014895-80e03260-767e-40e2-8a8b-4c76f681da66.png)

**Comment by Zimtente** [comment]
hey thx will be added!
