### ISSUE TITLE
Please add these domains to ADJECTIVE category

### ISSUE THREAD

**Issue by basestation-eth** [Zimtente/ens-collections#434]
Hi there, please add these domains 

ADJECTIVE:

fattish, 11581185398590993912542515405190383762271518075991167200797041618596413503662
diglot, 55232725541652180184459400540408864589002842854822396685282980513556789627250
garlicky, 5994094141429469141977653021065747571629278222147282454024440152528815310146

**Comment by basestation-eth** [comment]
![image](https://user-images.githubusercontent.com/110099007/183021853-b4a2af03-5fd7-4f1c-b314-d97da3a0ac09.png)
![image](https://user-images.githubusercontent.com/110099007/183022065-e08dbe5f-96d1-4600-99be-2f322e648752.png)

**Comment by Zimtente** [comment]
thx will be added!
