### ISSUE TITLE
Please add Giacinto to male firstname category please 

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#438]
Hi guys 
Please add this ens domain to male first name list please 

name> giacinto.eth
token id > 30810452628320258365979476145396772842279148790787607260041378514495522473559

please refer to the data >
https://en.wikipedia.org/wiki/Giacinto#:~:text=Giacinto%20is%20a%20masculine%20Italian,the%20priesthood%20for%20sexual%20misconduct

**Comment by Zimtente** [comment]
thx will be added!
