### ISSUE TITLE
Add to firstnames

### ISSUE THREAD

**Issue by D0mainsale** [Zimtente/ens-collections#446]
Bonifacio 
Gheorghe 
Emidio 
Doroteo 
Zacarias 
Laureano 
Gervasio 
Ildefonso 
Ruperto 
Calixto 
Abdel-Rahman 
Leonides 
Cirilo
Romualdo 
Apolonio 
Martiniano 
Aquilino 
Melquiades 
Hermegildo 
Saúl 
Édgar

**Comment by Zimtente** [comment]
hi thx will be added!
