### ISSUE TITLE
Please Add Missing Prepunk Names

### ISSUE THREAD

**Issue by hopefulbeasts** [Zimtente/ens-collections#449]
Hi- Im a mod in the prepunk club discord and am writing to request an update to the names included in the pre-punk club categories. There are a number of names that are currently missing. I've modified the original dune dashboards by Makoto to pull in the correct names for the following 3 categories: All Prepunks, First 1000 Prepunks and First 10k Prepunks. 

1. This list contains all known prepunk names: https://dune.com/embeds/1116234/1908089/5a6ac118-ddeb-46e5-a105-e4ec67bfae89 

2 ,This list contains all known prepunk first1000 names: https://dune.com/embeds/1116243/1908103/aa93b49a-356a-4c42-a60b-60a309e304aa

3. This list contains all known names in the prepunk first 10k: https://dune.com/embeds/1087641/1862636/eb5e08d2-5869-4d9c-b98b-76c4c2de3b49
Note: There are 10,001 names in this list because the last 2 names were finalized in the same block and the rank can't be differentiated. 

I don't have a paid dune membership, so can't pull the lists as csvs. These dashboards are also built so that any blank names that are found going forward will show up as they are registered. If you base your category list on the hashes or TokenIDs, any found names will be included going forward as well. 

I am happy to help support this request in any way that is needed. please don't hesitate to reach out. 
My discord username is  HopefulBeasts#2238 and my twitter account is Kinder_NFT_Art. 

Thank you!

**Comment by Zimtente** [comment]
noted, will be added!!
