### ISSUE TITLE
Add tmi.eth to 3L dictionary category

### ISSUE THREAD

**Issue by MrLegend2** [Zimtente/ens-collections#45]
_Adding or Removing Names from a Collection_
To modify an existing collection, creating an issue.

Explanation why the item should be added/removed from a collection - 
- tmi is found in Oxford dictionary, dictionary.com, Macmillan dictionary, Merriam-webster, Wikipedia, Urban dictionary and many more such authentic and trust worthy dictionaries. So please add it to your 3L dictionary category on ens.vision!

Collection Name
-3 letter dictionary

Name of the item
-tmi.eth

(Optional) Token ID of the item

**Comment by Zimtente** [comment]
noted: will be added.
