### ISSUE TITLE
add to 3 Letter Dictionary

### ISSUE THREAD

**Issue by devilutionz** [Zimtente/ens-collections#457]
ERK is an English word found on dictionary.com, merriam-webster.com, collinsdictionary.com and so on. 

Meaning of ERK:
_British. : a member of the lowest rank in the Royal Air Force (as on the ground crew) : aircraftsman._

Collection Name:
3 Letter Dictionary

Item Name:
erk.eth

Token ID:
10365983549676977743170600630175453847713956626843764225309238495003118331156

**Comment by Zimtente** [comment]
thx will be added
