### ISSUE TITLE
Add Premiering.eth and barbecuing.eth to English verbs category

### ISSUE THREAD

**Issue by MrLegend2** [Zimtente/ens-collections#46]
Adding or Removing Names from a Collection
To modify an existing collection, creating an issue.

Explanation why the item should be added/removed from a collection -

Premiering and barbecuing are clearly actions and are verbs. So please add it to your English verbs category on ens.vision!
Collection Name
-English verbs

Name of the item
-Premiering.eth
-Barbecuing.eth

(Optional) Token ID of the item

**Comment by Zimtente** [comment]
noted: will be added.
