### ISSUE TITLE
Add to Male First name

### ISSUE THREAD

**Issue by mihelson777** [Zimtente/ens-collections#461]
Hello guys, please add moisha.eth to Male Firstnames category

Explanation: The name Moisha its - An ancient Hebrew name, mentioned as early as the Bible

Collection name: Male Firstnames

Name of the item: moisha (moisha.eth)

Token ID of the item: 95659750428303516964029212098088116469331915995378451809400925191269265232461

Thank you!

**Comment by Zimtente** [comment]
thx will be added!
