### ISSUE TITLE
Addition request in Female Firstnames category

### ISSUE THREAD

**Issue by nfthunter007** [Zimtente/ens-collections#469]
Category: Female Firstnames
Domain: **saboohi.eth**
Token ID : 10226112516839740141439522991968112392676152930770385213878623518472730364930

Category: Female Firstnames
Domain: **bilquees.eth**
Token ID : 40308903025015870552597317099319281400366309332600700149848396317983508504850

**Comment by Zimtente** [comment]
thx will be added
