### ISSUE TITLE
Please add Jacintha to female firstnames category

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#470]
Hi there 

please add jacintha to female first names category

ens domain name: jacintha.eth
token id : 62365452368526203486310394017570692665630267827797148047241895372278390209533

data : 
https://www.sheknows.com/baby-names/name/jacintha/#:~:text=Greek%20Baby%20Names%20Meaning%3A,the%20name%20Jacintha%20is%3A%20Beautiful.

**Comment by Zimtente** [comment]
thx will be added!
