### ISSUE TITLE
Please add pickling.eth to English Adjectives and English Nouns categories

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#475]
pickling.eth
38737973620953729902712792041901352156959559874665180393778208342048684196133

Adjective:
- (of food) suitable for being pickled or used in making pickles.
"pickling onions"

Noun:
- An instance of processing something in brine or other solution.
- A process by which the oxide scale on steel (especially stainless steel) is chemically removed (by strong acids).

References (respectively):
https://dictionary.cambridge.org/dictionary/english/pickling
https://en.wiktionary.org/wiki/pickling

Thank you!

**Comment by Zimtente** [comment]
thx will be added!
