### ISSUE TITLE
Add to Collection: 	English Nouns

### ISSUE THREAD

**Issue by sloppyseconds88** [Zimtente/ens-collections#490]
Reason:	These are English Nouns that are currently missing from ENS.Vision.
Add to Collection: 	English Nouns
Name + Token IDs:	
ourselves,46181575371118016767718334028430649631835925908433130457423338911521554069780	
respondent,98309544265510830054628469591289942427687904891157198081902974481602953561357	
circumstance,76422931421106449124222487153198205722527520974784466320840096557848916541853	
comprehensive,21817897137639504616308415431873494108927481506508063240140536466443240324691	
limitation,91155229542343997415903660112408844369810163653505213905253838931557639740353	
biological,76957395638507574156921991905512990530244557929512359428423233767050150768991	
orientation,41135954657184318340327628134766050495822774938220555622219246340458326305526	
frustration,112240174190603335376856926354365448574166522339472932368500219494199062058087	
enforcement,18767717673089835197595565802719527673027456758507932572656531324020820921501	
overlook,1325544422459869642209578508817813523242813469308692620429361208803340282973	
mele,14053100123966690450345717590071865133679903923693137664144011477002947104539	
nomination,5248466705919709123340991555160222814759490753480310022140862526120325440099	
vada,60318428820655863165291331615429263994494200413213971616192336038259805386819	
bryn,80449463369065276373203328755830765014094683208611332650914713883378138404984	
coen,40447277733757736162952281607593487585684614125846146928224724365867858550014	
rear,64900702803699795540800206896825582439605747507381781815109524100862777305615	
ways,13136775141710249887581550512632791589681133765630340244871355206859421879856	
	
Thank you!

**Comment by Zimtente** [comment]
due to https://www.merriam-webster.com/dictionary/ we added them to the following categories:

ourselves - plural pronoun
respondent - noun
circumstance - noun
comprehensive - adj
limitation - noun
biological - adj
orientation - noun
frustration - noun
enforcement - noun
overlook - noun and verb
mele - noun
nomination - noun
rear - verb and noun
ways - pl noun


vada - not a proper word / no noun
same for bryn, coen
