### ISSUE TITLE
Add to Collection: 	English Adjectives

### ISSUE THREAD

**Issue by sloppyseconds88** [Zimtente/ens-collections#491]
Reason:	These are English Adjectives that are currently missing from ENS.Vision.
Add to Collection: 	English Adjectives
Name + Token IDs:	
respondent,98309544265510830054628469591289942427687904891157198081902974481602953561357	
supposed,68037807334177435600908611304095744020460335226584305936247127385303603184029	
apparent,17163846161679602620294563313054021296017505963724312445847427425362507812173	
comprehensive,21817897137639504616308415431873494108927481506508063240140536466443240324691	
biological,76957395638507574156921991905512990530244557929512359428423233767050150768991	
involved,91054114683817688152875842100620584879254550952992694847977379595625564118914	
bess,6842083109232685522899339777433969137278510183200828729068526786406344257450	
	
Thank you!

**Comment by Zimtente** [comment]
respondent - noun and adj
supposed - adj
apparent - adj
comprehensive - adj
biological - adj
involved - adj
bess - noun


 due to https://www.merriam-webster.com/dictionary we will add them to the following categories
