### ISSUE TITLE
Add to Collection: 	4 Letter Dictionary

### ISSUE THREAD

**Issue by sloppyseconds88** [Zimtente/ens-collections#493]
Reason:	These are English 4 Letter Dictionary Words that are currently missing from ENS.Vision.
Add to Collection: 	4 Letter Dictionary
Name + Token IDs:	
alva,15532103382016980608796847640004061192210684362829779256994198517966405431128	
bria,79240431694935417870361753541911483804079347527710100433933314016558312406877	
esme,87620240642495214371731517865765709027755062907868430852442471019920578464262	
inez,15019607617841281082290752627039357891849552289086763907831099151724765703648	
leda,20285598538889168616677415336345986643105144976749098766840435979420370686366	
lexa,15842236227168116603480687524548151605664300297035935437545928912201432692847	
lysa,73762786640420315519658644304222387144635200533869431707764871620285273750935	
maci,16754463782411713586149058655039490845944948572623356654291543293289559106207	
mele,14053100123966690450345717590071865133679903923693137664144011477002947104539	
vada,60318428820655863165291331615429263994494200413213971616192336038259805386819	
zoie,86904003231926972080677312611824009275622484842860436639555418176933676832997	
zuri,44355731462153710622040242466600680523853371515434019589274597604191977997531	
bryn,80449463369065276373203328755830765014094683208611332650914713883378138404984	
coen,40447277733757736162952281607593487585684614125846146928224724365867858550014	
bess,6842083109232685522899339777433969137278510183200828729068526786406344257450	
lois,69950536676080017810007744954787490819720212387843043896514298402265952921970	
myra,87814557449353473593457912440018202351632732960035287227100712452404978846684	
	
Thank you!

**Comment by Zimtente** [comment]
hi as I see those are not dict words (dict words are f.E.: dive, down, skin, etc)
 I added "mele" as it is a noun and real dict word
![image](https://user-images.githubusercontent.com/27185649/185559666-8d779f38-5539-4fb7-a31f-1be09d150c33.png)
