### ISSUE TITLE
Add to Collection: 	Female Firstnames

### ISSUE THREAD

**Issue by sloppyseconds88** [Zimtente/ens-collections#494]
Reason:	These are English Female First Names that are currently missing from ENS.Vision.
Add to Collection: 	Female Firstnames
Name + Token IDs:	
bria,79240431694935417870361753541911483804079347527710100433933314016558312406877	
esme,87620240642495214371731517865765709027755062907868430852442471019920578464262	
lexa,15842236227168116603480687524548151605664300297035935437545928912201432692847	
lysa,73762786640420315519658644304222387144635200533869431707764871620285273750935	
maci,16754463782411713586149058655039490845944948572623356654291543293289559106207	
zoie,86904003231926972080677312611824009275622484842860436639555418176933676832997	
zuri,44355731462153710622040242466600680523853371515434019589274597604191977997531	
bryn,80449463369065276373203328755830765014094683208611332650914713883378138404984"	
	
Thank you!

**Comment by Zimtente** [comment]
thx will be added
