### ISSUE TITLE
Add to Collection: 	English Verbs

### ISSUE THREAD

**Issue by sloppyseconds88** [Zimtente/ens-collections#495]
Reason:	These are English Verbs that are currently missing from ENS.Vision.
Add to Collection: 	English Verbs
Name + Token IDs:	
bombing,54059015045723851974626846580839916070186962820719515622353814045453609502393	
overlook,1325544422459869642209578508817813523242813469308692620429361208803340282973	
proposed,37620284976813089405134787277148451233168010793089403366695332087753631837193	
grew,89014665171940452569387333614053468477398206949537723623319924458531548123826	
	
Thank you!

**Comment by Zimtente** [comment]
bombing - verb
overlook - alr added
proposed - verb
grew - verb

will be added!
