### ISSUE TITLE
Add to Collection: 	Male Firstnames

### ISSUE THREAD

**Issue by sloppyseconds88** [Zimtente/ens-collections#496]
Reason:	These are English Male First Names that are currently missing from ENS.Vision.
Add to Collection: 	Male Firstnames
Name + Token IDs:	
bryn,80449463369065276373203328755830765014094683208611332650914713883378138404984	
coen,40447277733757736162952281607593487585684614125846146928224724365867858550014	
	
Thank you!

**Comment by Zimtente** [comment]
will be added
