### ISSUE TITLE
New ENS collection: Made in Country

### ISSUE THREAD

**Issue by AudriusHelloWorld** [Zimtente/ens-collections#5]
I don't have access, so. add here file.
thank you.
```
{
  "name": "Made in country",
  "slug": "made-in-country",
  "description": "Made in countries",
  "twitter": "",
  "chat": "",
  "website": "",
  "logo": "",
  "csv": ["made-in-country.csv"]
}
```
[made-in-country.csv](https://github.com/Zimtente/ens-collections/files/8838456/made-in-country.csv)

**Comment by AudriusHelloWorld** [comment]
@Zimtente how I can make pull request.
I can create new branch and make pull request or... I can create Issues with data about new collection.

**Comment by AudriusHelloWorld** [comment]
@Zimtente when you added this collection?

**Comment by CryptoGatsu** [comment]
category should be added in pull request now. thank you for providing correct csv.

**Comment by AudriusHelloWorld** [comment]
@CryptoGatsu what is wrong with this csv?
