### ISSUE TITLE
Adding to Surname Collection - (proof) 

### ISSUE THREAD

**Issue by ogcryptokush** [Zimtente/ens-collections#502]
I have an ens domain that is in the pre-punk collection but not in the surname collection. Would like to get it added on there also. 

tennent.eth 

Surname

Token ID : 39113975460862785593257690121155595649308778683709851826577585176097985475969

Proof: 
![image](https://user-images.githubusercontent.com/110641279/182971330-f6d2ba28-c42b-4e21-b37b-2c70e2c3e019.png)

**Comment by Zimtente** [comment]
thx will be added!
