### ISSUE TITLE
Please add Peñaranda and Piñera to surnames category

### ISSUE THREAD

**Issue by papafun** [Zimtente/ens-collections#503]
Hi please add the followings ens domains to surnames category 

name : peñaranda.eth
token id: 81204220899325507306147761893626007757018002071434691765411470556257010077795
data: https://forebears.io/surnames/pe%C3%B1aranda

name : piñeros.eth
token id: 70237700202034013131004240346150737755039757137951987533506054652189573471133
data: https://forebears.io/surnames/pi%C3%B1eros

Thanks in advance

**Comment by Zimtente** [comment]
thx will be added!
