### ISSUE TITLE
Add to Collection: English Adjectives

### ISSUE THREAD

**Issue by hovers1** [Zimtente/ens-collections#505]
Reason: These are English Adjectives that are currently missing from ENS.Vision.
Add to Collection: English Adjectives
Name + Token IDs:

self-disciplined      6167570034722323167534592940706455626109275733576465210051150801929186492298
https://dictionary.cambridge.org/dictionary/english/self-disciplined

self-confident      106086701943562944528491948254178244824144867601324380416802108102348189732571
https://dictionary.cambridge.org/dictionary/english/self-confident

fair-minded         92332211353651340630351674464646368998110681462276158432115907375569795101782
https://dictionary.cambridge.org/dictionary/english/fair-minded

warm-hearted     54168989867972450579417468921038384095486618733042021187653351598994729827834
https://dictionary.cambridge.org/dictionary/english/warm-hearted

warmful              39420719415314695128494947716605064204271445679493794022712935141996827360537
https://www.merriam-webster.com/dictionary/warmful

Thank you!

**Comment by Zimtente** [comment]
thx will be added!
