### ISSUE TITLE
Names to be added to the Male First Names, Female First Names & Surname categories - Thank you!

### ISSUE THREAD

**Issue by Blvxe** [Zimtente/ens-collections#52]
**Adding Names from a Collection**
To modify an existing collection, creating an issue.

**Explanation why the item should be added from a collection:**
The list of male & female forenames below should be added to their respective existing collections as they are all within the top 1000 names in China, top 5000 names worldwide & each have at least 200,000 people that bear the name globally. It’s also a good chance to open the categories up to more regions and further grow ENS & Vision’s reach and markets. Names & data were cross-checked on Forebears.io for incidences / popularity & LinkedIn to double-check gender confirmations for each name.

The final shorter list (2 names) are British surnames that have yet to be added to the Surnames collection. One is of a famous ex-F1 driver, and the other is a surname in the UK / Australia. Both have been confirmed on Forebears.io & LinkedIn to ensure they are in circulation.

I’ve also added token ID’s for each domain to the bottom of this request to hopefully save you some time when adding them as I appreciate there are a few to add.

**Collection name #1: Male First Names**
**Name of item(s):**
Chenglin.eth
Fengming.eth
Guangrong.eth
Guisheng.eth
Guofang.eth
Guozhen.eth
Honghua.eth
Jianchun.eth
Jiasheng.eth
Junling.eth
Shaohong.eth
Shaoqing.eth
Tiejun.eth
Weirong.eth
Wenfang.eth
Xianjun.eth
Xianming.eth
Ximing.eth
Xinsheng.eth
Xuefang.eth
Yanbing.eth
Yaohua.eth
Yueping.eth
Zhiqin.eth
Zhongmin.eth
Zhongping.eth

**Collection #2: Female First Names**
**Name of item(s):**
Chaoxia.eth
Fengqin.eth
Fengxia.eth 
Guimei.eth 
Hongling.eth
Huaying.eth 
Jieping.eth
Liqiong.eth
Qiuhong.eth 
Shuxia.eth
Suping.eth 
Xiuqing.eth
Yajuan.eth
Yuehong.eth

**Collection #3: Surnames**
**Name of item(s):**
Brundle.eth
Retford.eth

**Token ID's:**

**Male First Names:**
**Name of item(s) & Token ID(s):**
**Chenglin.eth:** 72698196050183359134385992476947072762946605126341736417522009876294432518050
**Fengming.eth:** 106772675430116288781563314430774274324231702942083035403501543823627270270063
**Guangrong.eth:** 23298928627055897838299397548910044336361409803946763985424863019906552812391
**Guisheng.eth:** 67944254428086078296979337875593466531677371635835040501264872185708419902956
**Guofang.eth:** 76414740572839031553732567371291721155559623237608436626204568240477345423547
**Guozhen.eth:** 70785260722802069461222418523789624967510303718368968407417292193387472917639
**Honghua.eth:** 91144478853742820149020252226374836675949175779595661386185721036365902306467
**Jianchun.eth:** 81758903208435396379061680129983431369949939012247607194062520272859765148663
**Jiasheng.eth:** 4121771581022162673961367511723048122181392503451294368077426531506600029933
**Junling.eth:** 8076009307064777948099940459429875960793948566018361033560656178797410625717
**Shaohong.eth:** 5712963284566231521356525820513243938979414590811661863630697298740498807406
**Shaoqing.eth:** 67944254428086078296979337875593466531677371635835040501264872185708419902956
**Tiejun.eth:** 35933460358664423063891859838291025473651548149344371315618517199376385444879
**Weirong.eth:** 34837876293592955362892785050971411971027151606854006158119238665884555504267
**Wenfang.eth:** 39711731966793214937974929347902372566052772722798872088285879405059820823121
**Xianjun.eth:** 89058816226320851383659049025150015160124911247833885062589963235376551113068
**Xianming.eth:** 48857620087491649909680803114125309602724219906158775937607786826489817600237
**Ximing.eth:** 25838399010794114655598416103993112760953178622722087025268241029373400742118
**Xinsheng.eth:** 11419338356024909628024222630540866685964743797070299434088175968995122190146
**Xuefang.eth:** 94319590306681919231675537613184222942195761389227198469804178518655808164183
**Yanbing.eth:** 48305524047699786600971135809054804323753911237472554068239389073105951806273
**Yaohua.eth:** 50625297038215368427821170950021869058650664166438703973035452570291741966178
**Yueping.eth:** 94277033597532308757012534459835776652141487906836460723226777036526157181408
**Zhiqin.eth:** 71228887040863982571360747150804581142231209420275979375024999565564355087775
**Zhongmin.eth:** 111110130489031136418290388571098698331806757961236880423707725777404738463741
**Zhongping.eth:** 10618783948321966975060316298258492912445573246964349287288407959352549713102

**Female First Names:**
**Name of item(s) & Token ID(s):**
**Chaoxia.eth:** 99480300642281825150395140669558480492707721404357095429048006143695270457657
**Fengqin.eth:** 90701877183127851626373586755817821384419140856772342519435100444124939792459
**Fengxia.eth:** 58058513701244313634256840553714742296433141907977521811861203757696566144064
**Guimei.eth:** 57282491673595278127609177879963740194728806693145606200123898274204181094502
**Hongling.eth:** 92143217245612096522052770764423985703535150805857857686699199482842559541085
**Huaying.eth:** 99108031429036350278528487335728973740247653203259738187564656776298442426480
**Jieping.eth:** 73844497478575018414954308260310894621881560406347424359075690785235424732332
**Liqiong.eth:** 26061478307456929930901133283789192428288820383413949798958320823991637014120
**Qiuhong.eth:** 57403441443296550931970668501125912823700650221924534908441460091648472316341
**Shuxia.eth:** 34997781397008033719811875746884169208295600107202287684914716724128113142281
**Suping.eth:** 29700234588904886591602181609189215281651166423281362593476624297531066786279
**Xiuqing.eth:** 67504987299458442204416064516406437693675389119115245399669185607797964771881
**Yajuan.eth:** 30728407916070566308611048059467038952837198857265075000094003947370263472220
**Yuehong.eth:** 84163915283741399881193756519212871411084225418129835463075031362937605691844

**Surnames:**
**Name of item(s) & Token ID(s):**
**Brundle.eth:** 32482159064858457346605301148718119314675603134208509298947124237741153483735
**Retford.eth:** 28752391337684482048880485955398324613927913654234430567604088221508945958418

Thanks in advance, appreciate all the amazing work you do for the ENS community ✌

**Comment by CryptoGatsu** [comment]
names have been added!

**Comment by Blvxe** [comment]
Thanks, Gatsu.
