### ISSUE TITLE
Request for Surnames and first names

### ISSUE THREAD

**Issue by Hootie001** [Zimtente/ens-collections#527]
I would like to request to add one first names and some surnames to the exsisting surname and female first name categories.

Surnames:
Blakeney.eth(pre-punk) Token ID 31299962159821037946214648004231374241371998856746821200529253476566232053483
kennett.eth(pre-punk) Token ID 17926777072394678726449713890150260592759531851991223427845493822591471052285
hedberg.eth Token ID 51867415492712967915762865164038335765058302613475399868646909822973857008658
salters.eth Token ID 76140873131345755503198617312651971671594562430659054126594251060205926011120
millsaps.ethToken ID 54871156735450081779184727321665044872742144803877209791045309006282173360417
gambrel.eth(pre-punk)  Token ID 21483552302392195783583146646855804626624602475642145907883678334165976567566

 All are very common surnames

Female First name
Brittan.eth Token ID 45536674065769872654829311744247922379176462626300422353484410816689877261100

Brittan is also a common name

**Comment by Zimtente** [comment]
hi will be added - as brittan is unisex we added it to both categories

**Comment by Hootie001** [comment]
Awesome, thank you so much
