### ISSUE TITLE
Id like to Add tags and category details to ENS .eth domain names 

### ISSUE THREAD

**Issue by Dayo887** [Zimtente/ens-collections#528]
Az520.eth added to a city's and/or Area codes or 5 letter dictionary category with U.S Area codes as tag

602phx.eth to capital cities category with U.S Area code as tag

champsonlynft.eth in English nouns category with English noun, alpha or influencer as tag 

Vaulted.eth added to English adjectives category with tag being English letters

620602.eth added to a 6 digit palindrome category with tag being 6 digit palindrome 

Add new category called "ENS" for any domain beginning with ens, for example-

ensbaycnft.eth with "blue-chip" or O.G NFT tag

ensneotokyo.eth with "gameing" tag

ensdoodlesnft.eth with "blue-chip" or "O.G NFT" tag

enspornography.eth with "noun" tag.  It Could also be added to "English nouns" category 

enselliotrades.eth with "influencer" or "alpha" tag

ensboredapeyachtclub.eth with "blue-chip" or "O.G NFT " tag 

enscryptopunksnft.eth with "blue-chip" or "O.G  NFT" Tag
 
Digitalassetsking.eth in the English nouns category with English noun tag

theetherium.eth in English nouns category with noun tag

deezznuts.eth in English noun category with English noun tag

imronburgandy.eth in English nouns category  with English noun tag

**Comment by Zimtente** [comment]
Az520.eth - we dont have this cat yet
602phx - same here
620602 is not a palindrome (620026 would be a palindrome)
Nouns are only words containing the original noun (not combo names from 3 words)

Rest was added!

Tags will come with next update!
