### ISSUE TITLE
Adding to a Category

### ISSUE THREAD

**Issue by 7664-eth** [Zimtente/ens-collections#53]
GM
asking for a few names to be added to
FirstName
sylv.eth (unisex) (4L ) for sylvester,sylvia,sylvaine, etc
bradynn.eth (unisex) 
janavi.eth(fname)
iarina.eth(fname)
markian.eth (mname)
callee.eth (both a fname & a noun)

tq

**Comment by Zimtente** [comment]
noted: will be added shortly.
