### ISSUE TITLE
Adding name to Female Firstnames collection

### ISSUE THREAD

**Issue by vansorok** [Zimtente/ens-collections#533]
hi, i would like to request the adding of name Roana to your Female Firstnames collection since its a name and its not there yet.

**Comment by vansorok** [comment]
here's a token id if its needed https://opensea.io/assets/ethereum/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/95915862501490900427534179371257514341814436670737726157788341950419744014833

**Comment by Zimtente** [comment]
thank u! will be added!
