### ISSUE TITLE
ADDING SURNAMES

### ISSUE THREAD

**Issue by RoyalOwl** [Zimtente/ens-collections#534]
The following Surnames (mainly top european surnames) are missing in the category surnames: 
kovačević.eth (prepunk aswell) 
wüthrich.eth 
bürgi.eth
bösch.eth
forrer.eth
vögtli.eth
rychner.eth
schiess.eth
flückiger.eth
ruckstuhl.eth
allenspach.eth
scheiwiller.eth
grossenbacher.eth
schönenberger.eth
Kovačević

**Comment by RoyalOwl** [comment]
additional:
muslera.eth
ekström.eth

**Comment by Zimtente** [comment]
thanks will be added!
