### ISSUE TITLE
Words to add to English categories

### ISSUE THREAD

**Issue by ENSfuturist** [Zimtente/ens-collections#54]
Hello, please could you add these words to the English categories on Ensvision. Thanks a lot! 

English Verbs:-
derange.eth

English Nouns:-
forecourt.eth
migrator.eth
inflationist.eth
computist.eth
tiredness.eth
beautifulness.eth
naughtiness.eth
filthiness.eth
litigant.eth
professorship.eth
doctorship.eth

English Adjectives:-
tetchy.eth
erasable.eth
numerable.eth
spiritless.eth

**Comment by CryptoGatsu** [comment]
these names have been added to main branch! 👍
