### ISSUE TITLE
Add names to male first name and female first name

### ISSUE THREAD

**Issue by EnsFlower** [Zimtente/ens-collections#545]
hi, can you add the following male names to male first names :
zhifang
yongjie
dongming
jinxiang
jinliang
haihong
zhichao
zhiqing

and the following female names to femal first name:
meifang
chunling
guixiang
xiufang
cuiping
meizhen
jinghui

(They all have over 300k people who bear this name (forebears.io))
Thank you! :)

**Comment by Zimtente** [comment]
thx will be added!
