### ISSUE TITLE
Add Gen1 Pokemon category

### ISSUE THREAD

**Issue by pzpzpz3** [Zimtente/ens-collections#55]
3 letters all vowels got their own category despite being much less trade volume than Gen1 pokemon. having gen 1 lumped into all gens is ridiculous when it commands the vast majority of trade volume

{
  "name": "Gen1-Pokemon",
  "slug": "Gen1-Pokemon"
  "description": "Pokemon from Gen1 numbers 1-151.",
  "twitter": "https://twitter.com/TrainerDAO",
  "website": "N/A",
  "chat": "https://discord.com/invite/nfWYw9mctW",
  "logo": "pokemon-gen1.png",
  "csv": ["gen1.csv"]
}
![pokemon-gen1](https://user-images.githubusercontent.com/101365809/175836348-aa3d994e-44de-4e15-b0f1-a991e6d12c1a.png)
[gen1.csv](https://github.com/Zimtente/ens-collections/files/8987668/gen1.csv)

**Comment by CryptoGatsu** [comment]
this is very fair. will push this monday

**Comment by CryptoGatsu** [comment]
pushed to main branch! 👍
