### ISSUE TITLE
Please add the following first names:

### ISSUE THREAD

**Issue by ensisfun** [Zimtente/ens-collections#562]
Please add the following first names to the corresponding categories:

Female:
Krissie Token ID: 86764979444202383834783351799670305518744970249685568639377112585805531624561
Bionca Token ID:18209164287686680033512470016694575300590468088480258463647318734477725105777
Eisha Token ID: 9727585577102750300152678726862128102047144157140637650962401222470372866251
Errica Token ID: 2682814395942063159768975642678041412831599941757401371997679131213267271913

Male:
Geofrey Token ID: 107059983429846570427646282577469765304197408194115296153080181323837241538471

All are popular first names within their respective group! Thank you!

**Comment by Zimtente** [comment]
thx will be added!
