### ISSUE TITLE
Please add the following male-firstname and surname.

### ISSUE THREAD

**Issue by yutt1115** [Zimtente/ens-collections#563]
- male firstname
bertolt.eth
token id : 15123823526855495908701175240629828432442435817695338404714241214615462628204
(It is also famous as the name of a major character in the anime 'Attack on Titan'. Bertolt Hoover)

- surname
brightman.eth
token id : 98861262949676596948047880805220330009970823108344119185987100643301150395669
(It is also famous as the name of Sarah Brightman.)

- surname
considine.eth
token id : 30383616611020201279523777200867609898509335208538479777917313355208635661998
(It is also famous as the name of Paddy Considine.)

- surname
grint.eth
token id : 35298650117640729764654858959906934555198488392728621835447465118065888812557
(It is also famous as the name of Rupert Grint.)

- surname
laswell.eth
token id : 30531286947163533373936716432908197826106792703573805889475239570005253793204
(It is also famous as the name of Bill Laswell.)

thank you.

**Comment by Zimtente** [comment]
thx will be added!
