### ISSUE TITLE
Include "insensible.eth" in English Adjectives category

### ISSUE THREAD

**Issue by Gubbss** [Zimtente/ens-collections#564]
Hi all
I kindly request to include "insensible.eth" in English Adjectives category, as this word can be found in any dictionary as an adjective.

token id: 49167412821797867236221216975282716968646036831400610684017875702232158545186

Cheers

**Comment by Zimtente** [comment]
hi thx this was already added:
![image](https://user-images.githubusercontent.com/27185649/185599592-b8d8bd84-fa65-4b61-baf4-dc3506f4c52b.png)

**Comment by Gubbss** [comment]
Thank you !!!

Em sex., 19 de ago. de 2022 07:27, Zimtente ***@***.***>
escreveu:
