### ISSUE TITLE
Adding preston.eth + others to Male Firstnames

### ISSUE THREAD

**Issue by prestonhao** [Zimtente/ens-collections#578]
Hopefully I'm doing this right but requesting to add preston.eth in Male Firstnames category.

Some others names that I would like to suggest are as followed. Majority of names are Hawaiian.
MALE:
kuhao
kainalu
kaulana
kelii
kahele
imua
kapena
onipaa
pomai
tanioka
ganryu
soejima
karisu

FEMALE:
nohea
nohealani
pauahi
haunani
kealohi
kealakai
aulii
pomai
shanlee
lanida
karianna

Thank you for your consideration

**Comment by Zimtente** [comment]
hi thx will be added and on with our next update today!
