### ISSUE TITLE
Add name 'Roydon' to ENS Vision group Male Firstnames

### ISSUE THREAD

**Issue by PM2022** [Zimtente/ens-collections#580]
I own roydon.eth   It is registered and it is for sale on opensea yet is is not visible (nor searchable) on the ENS Vision group 'Male Firstnames'

It is not an uncommon name, it is quite common, i know a Roy (full name roydon)

Can you please add it to 'Male Firstname' group, and any other appropriate group 

you can view it at roydon.eth

thank you 
pmatthew.eth

**Comment by Zimtente** [comment]
hi thx I added it, will be on with our next update today!

**Comment by PM2022** [comment]
Perfect, thank you very much for the prompt response
