### ISSUE TITLE
Please add this domain to 3 letter dictionary category

### ISSUE THREAD

**Issue by fractionedeth** [Zimtente/ens-collections#583]
Please add dof (dof.eth) to the 3 letter dictionary word category. 

This is a dictionary word meaning: lacking in common sense, perception, or normal intelligence.

Collection name: 3 letter dictionary
Name of the item: dof.eth
Token ID: 69535883809865103731370486769966749513248879648448486186439475110193417452109

Thanks!

**Comment by Zimtente** [comment]
Hi thx will be added with next update 24/08/2022!

**Comment by fractionedeth** [comment]
Hi Zimtente did the update happen on 24/08? Still not showing up in 3 letter dictionary words, Thanks!

**Comment by fractionedeth** [comment]
> Hi thx will be added with next update 24/08/2022!

Hi Zimtente did the update happen on 24/08? Still not showing up in 3 letter dictionary words, Thanks!
