### ISSUE TITLE
Names and surnames category’s 

### ISSUE THREAD

**Issue by Isariyer** [Zimtente/ens-collections#586]
names 

ilai.eth
xanthos.eth
igora.eth

![56BECFA7-91C2-496B-9780-31D1E1A207B6](https://user-images.githubusercontent.com/95149360/185903058-6168591d-17e3-4266-bcaa-e030a02d3dcb.png)
![64C1FABD-F922-469E-B0EF-CF604D541B45](https://user-images.githubusercontent.com/95149360/185903078-4fbabcf0-f04b-423c-8627-765de8511424.png)
![5071EB2D-A959-41D8-A2AD-9766C7AEDE8B](https://user-images.githubusercontent.com/95149360/185903084-b8fe6e5c-9dda-4015-8bc9-ffd3ce776c35.png)
![180B4BC2-7A34-4389-9203-C210F48BB543](https://user-images.githubusercontent.com/95149360/185903094-18c99112-4021-4fe9-a3c2-8ca7266542e6.png)
![042F9A5C-F8A5-4A9C-A13F-555C99E3114E](https://user-images.githubusercontent.com/95149360/185903099-09f3c9fb-3dcf-4b17-81b8-a1d7ca8bc9c7.png)

surnames 
doblo.eth
bonz.eth

**Comment by Zimtente** [comment]
Hi thx for the detailed screenshots - that helps a lot!
I added them to the categories - will be up with our next update tomorrow (wed, 24/08/2022)

Greets
zim

**Comment by Isariyer** [comment]
Thank you ser

You have a great team !

Thanks in advance

Zimtente ***@***.***> şunları yazdı (23 Ağu 2022 15:00):

﻿

Hi thx for the detailed screenshots - that helps a lot!
I added them to the categories - will be up with our next update tomorrow (wed, 24/08/2022)

Greets
zim

**Comment by Isariyer** [comment]
Dear zimtente

Still i cant see my collections , should i do something ?

İsmail SARIYER ***@***.***> şunları yazdı (23 Ağu 2022 15:08):

﻿
Thank you ser

You have a great team !

Thanks in advance

Zimtente ***@***.***> şunları yazdı (23 Ağu 2022 15:00):

﻿

Hi thx for the detailed screenshots - that helps a lot!
I added them to the categories - will be up with our next update tomorrow (wed, 24/08/2022)

Greets
zim
