### ISSUE TITLE
ADD BALNEARY AT ENGLISH NOUNS

### ISSUE THREAD

**Issue by MrNice10** [Zimtente/ens-collections#597]
- Balneary is used to be considered as a Noun with that definition "A room for bathing". Also that's the etimology of the word: from Latin balnearium, from balneum (“bath”), from Ancient Greek βαλανεῖον (balaneîon).
- English Nouns
- Balneary
- 4907997999058057952511829706935754820683387212572412357851244298738176848755

**Comment by Zimtente** [comment]
hi thx will be added
