### ISSUE TITLE
ADD BALNEAL AT ENGLISH ADJECTIVES

### ISSUE THREAD

**Issue by MrNice10** [Zimtente/ens-collections#598]
-Balneary is used to be considered as an Adjective with that definition "Of or pertaining to baths or to bathing ". Also that's the etimology of the word: from Latin balneum (“bath, bathing place”).
-English Adjectives
-Balneal
-43396968590090155728998023632039879627894469172792313789062781564923686815975

**Comment by Zimtente** [comment]
will be added!
