### ISSUE TITLE
Adding ENS to 3-Letter First Name and Male/Female First Names

### ISSUE THREAD

**Issue by SalimStoudamire** [Zimtente/ens-collections#60]
Hello, I have two 3 letter ens domains I'd love to add to some categories -- **KIE.ETH and TYI.ETH**

When able would really appreciate you adding **KIE.ETH** to the categories of: 

**3-letter first name**
proof - https://duckduckgo.com/?q=is+kie+a+name%3F&atb=v314-1&ia=web

**Male First Names**
https://www.bounty.com/pregnancy-and-birth/baby-names/baby-name-search/k/kie#:~:text=Meaning%20of%20the%20name%20Kie&text=May%20derive%20from%20the%20Germanic,%2C%20meaning%20%3B%20war%20horn'.

**Female First Names**
https://babynames.com/name/kie

And **TYI.ETH** to the categories of:

**3-letter first name**
https://www.espn.com/womens-college-basketball/player/_/id/4704510/tyi-skinner

**Female First Name**

Thank you!

**Comment by Zimtente** [comment]
thank you for your patience - will be added.
