### ISSUE TITLE
Update Countries & Capitals list. 

### ISSUE THREAD

**Issue by snail-wtf** [Zimtente/ens-collections#600]
**Countries**

Abkhazia - recognized by 5 different countries; should be included in the Countries category. 
Link: [WIKI](https://en.wikipedia.org/wiki/Abkhazia) Link: [RECOGNITION](https://en.wikipedia.org/wiki/Abkhazia#Recognition)

São Tomé and Príncipe - not included in the list at all or incorrect spelling/no accents. São Tomé is included in the Capital Cities category with correct spelling and accents. 
Link: [WIKI](https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe)

**Capitals**

Saint Helier - capital city of Jersey
Link: [britannica](https://www.britannica.com/place/Saint-Helier)
Link: [WIKI](https://en.wikipedia.org/wiki/St_Helier)

Mamoudzou - capital city of Mayotte
Link: [britannica](https://www.britannica.com/place/Mamoudzou)
Link: [WIKI](https://en.wikipedia.org/wiki/Mamoudzou)

Nouméa - capital city of New Caledonia
Link: [britannica](https://www.britannica.com/place/Noumea)
Link: [WIKI](https://en.wikipedia.org/wiki/Noum%C3%A9a)

Fort-de-France - capital city of Martinique
Link: [britannica](https://www.britannica.com/place/Fort-de-France)
Link: [WIKI](https://en.wikipedia.org/wiki/Fort-de-France)

St Georges - capital city of Grenada
Link: [britannica](https://www.britannica.com/place/Saint-Georges)
Link: [WIKI](https://en.wikipedia.org/wiki/St._George%27s,_Grenada)

City of San Marino - capital city of San Marino
Link: [WIKI](https://en.wikipedia.org/wiki/San_Marino)
Link: [WIKI](https://en.wikipedia.org/wiki/City_of_San_Marino)

**Comment by Zimtente** [comment]
thx for providing all the sources! will add them!
