### ISSUE TITLE
Please add Zealotism.eth to English Nouns

### ISSUE THREAD

**Issue by xcraftediv** [Zimtente/ens-collections#602]
Zealotism.eth TokenID: 46049626093941148689534677609606849632829471309758629147026409743803575895825

Zealotism - NOUN
another word for [zealotry] - extreme or excessive zeal or devotion.
(https://www.collinsdictionary.com/us/dictionary/english/zealotry)

**Comment by shukaeth** [comment]
thx will be added =)
