### ISSUE TITLE
Please add Disturber.eth to English Nouns

### ISSUE THREAD

**Issue by xcraftediv** [Zimtente/ens-collections#603]
Disturber.eth TokenID: 49245873058755874556507826258278179200731756845799965687033108183514320982598

Disturber - NOUN
 /dɪˈstɜːbə(r)/
 /dɪˈstɜːrbər/
​a person or thing that causes trouble or interrupts something
disturbers of the public peace

https://www.oxfordlearnersdictionaries.com/us/definition/english/disturber#:~:text=%2Fd%C9%AA%CB%88st%C9%9C%CB%90rb%C9%99r%2F,disturbers%20of%20the%20public%20peace

**Comment by shukaeth** [comment]
thx will be added
