### ISSUE TITLE
Add Avivah to Female First Name 

### ISSUE THREAD

**Issue by sus1001** [Zimtente/ens-collections#604]
I have included example on why I believe Avivah should be listed on Female First names. Their is a couple public figure that first name is Avivah. Included on the Forbes website. Also a block chain enthusiast named Avivah. Their handles have been included and a simple search will show authors named avivah. Thank you for your time and consideration. 
![AAA88380-AA9C-4CA7-8D5A-603E736FDBC9](https://user-images.githubusercontent.com/112279765/187046386-38d55148-6749-49f1-a693-b1a538a2d2c1.jpeg)
![7CD6E3BA-3421-4485-AEC7-9B3BBBA9DB9E](https://user-images.githubusercontent.com/112279765/187046388-cd05dd2d-2520-462f-a73e-7dca32269970.png)
![E44DA74A-0383-4295-A7F6-43CDAD41C4F9](https://user-images.githubusercontent.com/112279765/187046389-a8dbd36c-cba9-4d9f-b1ec-b315acd2128e.png)

**Comment by shukaeth** [comment]
perfect! thx for the sources! will be added :)
