### ISSUE TITLE
Adding two names to respective English word categories

### ISSUE THREAD

**Issue by gitadrink** [Zimtente/ens-collections#605]
Request: Please add to English nouns, because it is an English noun as defined by most popular dictionaries.  
Name: spitfire.eth
Collection:  English Nouns
Token ID: 11985120848563894024412851194851963425902833433652708749535176401883672519989

Request: Please add to English adjectives, because it is an English adjective as defined by most popular dictionaries.  
Name: intergalactic.eth
Collection: English Adjectives
Token ID: 10482709286781914928370971885468564361020498900652851696151663164438584815529

Thank you

**Comment by shukaeth** [comment]
thanks will be added!
