### ISSUE TITLE
Add "kaid.eth" to 4 Letter Dictionary

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#606]
Explanation why the item should be added/removed from a collection: Kaid.eth should be added to the collection because it is a word in the english language. 

Collection Name: 4 Letter Dictionary

Item Name: kaid.eth
(Optional) Token ID of the item: 35411125930536648667630766203280558348391835721291013154987307524263393261162

![image](https://user-images.githubusercontent.com/103213586/187052949-5395f01f-cc70-43fb-b4ae-1873c409025f.png)

**Comment by shukaeth** [comment]
thank you - will be added!
