### ISSUE TITLE
Add "Ainu.eth" to 4 Letter Dictionary, and English Nouns

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#607]
Explanation why the item should be added/removed from a collection: Ainu.eth should be added to these collections because it is a real word in the English language that describes a group of indigenous people from Japan. It is also a noun. 

Collection Name(s): 4 Letter Dictionary, English Nouns

Name of the item: Ainu.eth

(Optional) Token ID of the item: 30655279686895463251396760709325407730390252967676989032675949290815124524030

![image](https://user-images.githubusercontent.com/103213586/187053053-77466530-fc38-4e13-aff6-2117e4866567.png)

**Comment by shukaeth** [comment]
thanks - will be added!
