### ISSUE TITLE
Add seps.eth to 4 Letter Dictionary, and English Nouns

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#608]
Explanation why the item should be added/removed from a collection: seps.eth should be added to 4 letter dictionary because it is in fact a 4 letter word in the english dictionary and as well is a noun.

Collection Name: 4 Letter Dictionary, English Nouns

Name of the item: seps.eth

(Optional) Token ID of the item: 102022920839779814258339260007783497069072170650237099080776371056621156021472

![image](https://user-images.githubusercontent.com/103213586/187053071-b024b9e4-ff91-44f1-b619-28b78fbd4bf7.png)

**Comment by shukaeth** [comment]
thx will be added!
