### ISSUE TITLE
Please ADD missing items to the corresponding collections

### ISSUE THREAD

**Issue by Bold-maverick** [Zimtente/ens-collections#611]
1. **Name of the item**: Servile.eth 

**Why**: Servile (adjective) Meaning: Submissive . Commonly used among SM communities. [](https://www.merriam-webster.com/dictionary/servile)
**Collection Name**: English Adjectives
**Token ID:** "59786536123458199952603296822738424963496776000776674739849894917762523071818"

2. **Name of the item**: Forswear.eth 

**Why**: Forswear (verb) is an English Verb that means Denying under oath  [](https://www.merriam-webster.com/dictionary/forswear  )
**Collection name:** English Verbs  
  **Token ID:** "82719264343956483923919670711145094821609107448451840601593459183705456463537"

3. **Name of the item:** Cannabinol.eth 

**Why**: Cannabinol (noun) is a psychoactive found in Cannabis plants  [](https://www.merriam-webster.com/dictionary/cannabinol  )
**Collection name:** English nouns  
**Token ID:** "107876181671616447618555432430193619101176657052723322819349291278991125844467"

4. **Name of the item:** Atefa.eth
 
 **Why**: Atefa is a popular middle eastern female first name []( https://angelsname.com/girl/atefa/meaning-origin-numerology-personality-traits-horoscope-detailed-information-about-name-atefa)
**Collection name:** Female First names  	
**Token ID:** "19000176954355393990977406964589513838193479436984947819033845740598592210909"

5. **Name of the item:** Oxime.eth 

**Why:** Oxime (noun) is the second most important antidote in the treatment of nerve agent poisoning  [](https://www.merriam-webster.com/dictionary/oxime  )
**Collection name:** English nouns
  **Token ID:** "68209305047953954502764380776866699818776371046416411436714906907946426097397"

6. **Name of the item:** 0xime.eth

 **Why:** missing entry from the 3 Hex Club  
 **Collection name:** 3 Hex Club
   **Token ID:** "71181139952399175571355582202683452141559722033151185333606865763296249832340"

7. **Name of the item:** Insentient.eth

 **Why:** Insentient (adjective) lacking perception, consciousness. Also used in CS to describe dumb AI. 
[]( https://www.merriam-webster.com/dictionary/insentient)
   **Collection name:** English Adjectives
**Token ID:**  "8078969517622460157258602252012551646049210979985292906479879134292211770166"

**Comment by shukaeth** [comment]
thx for providing all the sources! :) will be added!
