### ISSUE TITLE
Please add domain to 3LW and 3LFN

### ISSUE THREAD

**Issue by serginsurge** [Zimtente/ens-collections#612]
Explanation: upa has several meanings https://www.cancer.gov/publications/dictionaries/cancer-terms/def/upa https://en.wikipedia.org/wiki/Upa
Collection Name: 3 Letter Dictionary
Name of the item: upa.eth
Token ID: 41752650336716815579548076629823951729417725125035462178508545597009991013649

Explanation: Upa is used as a first name in India and several other places across the world with 5062 people using that name in India https://firstnam.es/name-upa 
Collection Name: 3 Letter First Names
Name of the item: upa.eth
Token ID: 41752650336716815579548076629823951729417725125035462178508545597009991013649

**Comment by shukaeth** [comment]
thx will be added!
