### ISSUE TITLE
Add voc.eth to 3L Dictionary

### ISSUE THREAD

**Issue by adds-eth** [Zimtente/ens-collections#615]
- **Collection Name:** 3 Letter _Dictionary_
- **Name of the item:** voc.eth
- **Token ID of the item:** 96083176652525560679778960877650613839191965755556266197123658786683532741344

- **Rationale:**
Voc is a scientific term for a type of organic compound and the definition of voc can be found in common dictionaries such as Cambridge and Mariam-Webster. The current 3L _Dictionary_ category on ENS.Vision contains other specialised abbreviations/acronyms such as _[gif.eth](https://dictionary.cambridge.org/dictionary/english/gif)_ and _[moc.eth](https://www.merriam-webster.com/dictionary/moc)_ but doesn't seem to include _[voc.eth](https://dictionary.cambridge.org/dictionary/english/voc)_.

![1E8714D1-331C-41E1-A181-3F15A65BB2F5](https://user-images.githubusercontent.com/17359636/187266729-90242a73-18e3-4632-89d9-20c58eb38a01.jpeg)
![603E27C0-F2E9-435E-9F6B-01313B29A7E9](https://user-images.githubusercontent.com/17359636/187266753-5d685011-7ade-46fd-9bdd-481426c2d185.jpeg)
![CCE017AC-3BBE-4E6B-AB99-E8B6061D0750](https://user-images.githubusercontent.com/17359636/187266755-da117c62-edd9-42bb-a9e3-07eb46fbf197.jpeg)

**Comment by shukaeth** [comment]
thx will be added!
