### ISSUE TITLE
4 LETTER PALINDROME CLUB REQUEST

### ISSUE THREAD

**Issue by prestonhao** [Zimtente/ens-collections#616]
Aloha!

Requesting a 4 Letter Palindrome Club. Would have the same amount of items compared to the 3 Letter Palindrome club. Perhaps even a 5 Letter Palindrome Club further down the road.

Thank you guys for all the hard work that you folks do! It doesn't go unnoticed one bit. Take care!

**Comment by shukaeth** [comment]
Will be added to clubs soon! :) stay tuned
