### ISSUE TITLE
Please add "ingratitude.eth" to English Nouns

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#618]
Explanation why the item should be added/removed from a collection: I believe Ingratitude,eth should be added to English nouns because it is a very common noun used in the English Language

Collection Name: English Nouns

Name of the item: ingratitude.eth

(Optional) Token ID of the item: 68698237286118322804880220395492613581179481147595560957914264455719763225258

![image](https://user-images.githubusercontent.com/103213586/187342252-8da2d57a-998f-4972-9316-4f814d1c1b67.png)

**Comment by shukaeth** [comment]
thx will be added!
