### ISSUE TITLE
Please add "degu.eth" to English Nouns and 4 Letter Dictionary

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#620]
Explanation why the item should be added/removed from a collection: Degu should be added to the English Nouns because it is a noun that means "a ratlike rodent with a long silky coat" and it is also a 4 Letter real word in the dictionary.

Collection Name: English Nouns, 4 Letter Dictionary

Name of the item: Degu.eth

(Optional) Token ID of the item: 53387039556997838127762337388272106917455707936537833957414582916777654610906

![image](https://user-images.githubusercontent.com/103213586/187344064-0a5dfb9a-0863-4cd2-bd1f-a876176e27d0.png)

**Comment by shukaeth** [comment]
thx will be added :)
