### ISSUE TITLE
Please add "sut" to 3 Letter First Name - 20k registered name

### ISSUE THREAD

**Issue by punk420** [Zimtente/ens-collections#623]
https://babynameseasy.com/jamaican-boy-name/sut

TOKEN ID: 53915223035620149786208991009841880068147894743685270977236780378995158532750

![sut first name](https://user-images.githubusercontent.com/107779297/187528359-6e3ac308-6e7c-443e-91eb-8f305caed947.png)

![sut first name 2](https://user-images.githubusercontent.com/107779297/187528372-be28ee45-8d27-49af-8493-ce00e3be74d7.png)

**Comment by punk420** [comment]
Can you please add sut into the 3 Letter First Name category. thank you

**Comment by shukaeth** [comment]
hi thx will be added!
