### ISSUE TITLE
4L Palindrome Club

### ISSUE THREAD

**Issue by adds-eth** [Zimtente/ens-collections#624]
**Please can we add tags for 4L Palindromes?**

_Rationale:_
- 3Ls pose significant long term value to both end users and companies due to their acronym value, but are currently struggling due high premiums for renewal
- 3LPs are showing material success recently with significant volume being traded through ENS.vision, following the general "pali meta" from digits
- Overall, letters are struggling to match the success of digits due to relatively low supply with high premiums in comparison
- 4 LPs could provide significant trading volume to the Letters market with the combination of larger volume, lower premiums, and pali meta attraction to end users 

_Rationale for urgency:_
- 4 LPs have recently been minted out and are holding a floor price at a premium to their registration price, proving a noteworthy level of demand, inspite of them being hard to search for
- Creating a 4 LP club tag would enable a more transparent market at a time when 4 LPs are still fresh, potentially uplifting the Letters market as a whole and also avoiding interest cooling and grace periods kicking in

**Comment by shukaeth** [comment]
Will be added to clubs! :) stay tuned - we'll try to publish them today

**Comment by adds-eth** [comment]
Sweeeeeeet! Thank you for everything, you guys are amazing
