### ISSUE TITLE
3L first name Request for KMY.eth

### ISSUE THREAD

**Issue by gweiman** [Zimtente/ens-collections#625]
KMY is short for Kimmy. Was hoping we could get it added to the 3L first name category instead of just the 3L. Thank you for your time

**Comment by shukaeth** [comment]
will be added - thx

**Comment by gweiman** [comment]
Awesome! Thank you for speedy response i look forward to seeing kmy.eth
added to the 3L names category

**Comment by gweiman** [comment]
Hey! Thank you for adding KMY to the first name category! It seems it wasn't added to the "3L first names" i was hoping to get that fixed considering it is 3 letters. Thank you again! ![image](https://user-images.githubusercontent.com/95380176/189447119-d66e4036-d282-4daf-87ad-b5a98db712d0.jpeg)
