### ISSUE TITLE
ADD new names to ENS Vision 4LD (4 Letter Dictionary) please

### ISSUE THREAD

**Issue by PM2022** [Zimtente/ens-collections#629]
Hi team,

I have minted three ENS names for the ENS Vision group 4LD (4 Letter Dictionary English) 

The names are currently not visible (nor searchable) on the ENS Vision group 4LD

Can you please add the following ENS names to the group

SWLK.ETH
WTFK.ETH
PZAZ.ETH

thank you
pmatthew.eth

**Comment by shukaeth** [comment]
hi can u link us sources (dict) that those are properly spelled words?

thanks!

**Comment by PM2022** [comment]
Thanks Shukaeth
WTFK is Who The Flip Knows (see attached)
PZAZ is the shortening of PZAZZ to fit in 4 letter shortening (same phonetics) (see attached)
SWLK is shortening of SWALK for four letter form (same meaning) (see attached)
![2022-09-05_WTFK Dictionary](https://user-images.githubusercontent.com/78894667/188521854-c9bcd7f9-1625-46c8-bba6-625efd4168ff.jpg)
![2022-09-05_PZAZZ Dictionary](https://user-images.githubusercontent.com/78894667/188521858-879e0561-4e3c-4c8f-a657-3aedc2a47f31.jpg)
![2022-09-06_SWLK Dictionary](https://user-images.githubusercontent.com/78894667/188521868-cbcc43bf-183e-4daa-b2ae-7b5683d60440.jpg)

**Comment by shukaeth** [comment]
thanks for the sources :) will be added!

**Comment by PM2022** [comment]
Thanks bro! Appreciated

**Comment by PM2022** [comment]
Hi Team,  We closed this because we thought all done and actioned, but my four letter words have still not been added to the ENS vision group 4Letter dictionary. (4LD)

Also as an addendum, for completeness SWLK is just the plural of SWALK  ie Sealed With Loving Kisses
