### ISSUE TITLE
Please add holroyd.eth to surname category

### ISSUE THREAD

**Issue by q4220** [Zimtente/ens-collections#638]
Hello. Can you please add Holroyd.eth to the SURNAME category. It is a surname with most located in England, Australia, Ireland, US.

It also has a local government area named after it in Australia. Thank you.

I think this is the token ID if I did it correctly. Thank you.
"113864810429012116001204040487079215572607792633362208163955213288669291874337"

**Comment by shukaeth** [comment]
hi thx will be added!

**Comment by q4220** [comment]
Thanks so much. Appreciate it.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
