### ISSUE TITLE
add tamarah.eth to Female Firstnames

### ISSUE THREAD

**Issue by DevNadd** [Zimtente/ens-collections#639]
Explanation: Tamarah is a common female name, many celebrities has it ( exp: Tamarah Benima, Tamarah Park, 
Collection Name: Female Firstnames
Name of the item: tamarah
(Optional) Token ID of the item: 79375142641994836571445986825732602388349505174452565085021756090360354556660

**Comment by shukaeth** [comment]
hey thx will be added soon!
