### ISSUE TITLE
male first name and surnames request

### ISSUE THREAD

**Issue by Soloxbt** [Zimtente/ens-collections#649]
Male First names:
rivalz.eth
Diethard.eth
touta.eth
kanzo.eth
shigekiyo.eth
hirohiko.eth

reason:
Rivalz Cardemonde
Diethard Ried
touta matsuda
kanzo mogi
Shigekiyo Yangu
Hirohiko Araki

Surnames:
gioro.eth
mitsunari.eth

reason:
Aisin Gioro
Ishida Mitsunari

**Comment by shukaeth** [comment]
hi thx will be added!
