### ISSUE TITLE
Please add "degu.eth" to 4 Letter Dictionary

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#651]
Explanation why the item should be added/removed from a collection: Degu should be added to the English Nouns because it is a noun that means "a ratlike rodent with a long silky coat" and it is also a 4 Letter real word in the dictionary.

Collection Name: English Nouns, 4 Letter Dictionary

Name of the item: Degu.eth

(Optional) Token ID of the item: 53387039556997838127762337388272106917455707936537833957414582916777654610906

![image](https://user-images.githubusercontent.com/103213586/188648626-339bbebe-f2db-4260-9a10-39ffb624d81a.png)

**Comment by shukaeth** [comment]
Hi already added degu:
![image](https://user-images.githubusercontent.com/107618056/189106863-e77eba37-6f95-46b4-b3d5-b977061e41f9.png)
:)
