### ISSUE TITLE
Please add "wootz" to 5L Dictionary

### ISSUE THREAD

**Issue by dirtyscalper** [Zimtente/ens-collections#652]
**Collection Name:**
5 Letter Dictionary (5LD)

**Name of the Item:**
wootz.eth

**Token ID:**
14491226865629545316631628567558855269305876267341847704443456408188414976719

**Explanation:**
This is a valid word in the English dictionary.  It refers to a type of steel.  You can type it into Microsoft Word and it will not display as a typo.  Some additional justification below:

https://www.merriam-webster.com/dictionary/wootz
"a steel made anciently in India by crude methods in small crucibles according to the oldest known process for making fused steel"

https://en.wikipedia.org/wiki/Wootz_steel

https://www.britannica.com/technology/wootz-steel

https://word.tips/unscramble/_/words-start-with/woo/length/5/?type=extended_fields

**Comment by shukaeth** [comment]
thx will be added!
