### ISSUE TITLE
Please add "bundt" to 5L Dictionary

### ISSUE THREAD

**Issue by dirtyscalper** [Zimtente/ens-collections#653]
**Collection Name:**
5 Letter Dictionary (5LD)

**Name of the Item:**
bundt.eth

**Token ID:**
59275554653368070471073135451951191354553404132014581155384960270822451161306

**Explanation:**
"Bundt" is a valid English word.  You can type it into Microsoft Word (capitalized) and it will not show as a typo.  Furthermore, it is a valid Scrabble word.  Scrabble defines it as "a type of cake pan."

Some additional info below:

https://en.wikipedia.org/wiki/Bundt_cake

https://word.tips/unscramble/_/words-start-with/bun/length/5/?type=extended_fields

**Comment by shukaeth** [comment]
thx will be added!
