### ISSUE TITLE
Please add "kiloliter.eth" to English Nouns

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#660]
Explanation why the item should be added/removed from a collection: This item should be added to English nouns because it is a common noun used in the English metric system. It means 1,000 liters.

Collection Name: English Nouns

Name of the item: Kiloliter.eth

(Optional) Token ID of the item: 11879764823950881849627639382910829018332796197505686537365755533844748837923

![image](https://user-images.githubusercontent.com/103213586/189057421-127afb58-b717-48d8-8996-a3f9c91ce515.png)

**Comment by shukaeth** [comment]
Hi thx will be added!
