### ISSUE TITLE
Add "bolk.eth" to 4 Letter Dictionary, English Nouns

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#663]
Explanation why the item should be added/removed from a collection: Bolk should be added to 4 letter dictionary because it is in fact a English Noun meaning "a belch"

Collection Name(s): 4 Letter Dictionary, English Nouns

Name of the item: bolk.eth

(Optional) Token ID of the item: 24319967493477090256847046398010563083395863911920844110190873690760888494163

![image](https://user-images.githubusercontent.com/103213586/189175489-979eceed-2612-4e6a-8b56-23380ad4f067.png)

**Comment by shukaeth** [comment]
thx will be added!
