### ISSUE TITLE
ADDITIONAL NAMES TO CATEGORIES

### ISSUE THREAD

**Issue by prestonhao** [Zimtente/ens-collections#664]
Aloha!

Just wanted to submit some requests with adding names to categories. Provided a few examples of who carries those names. Thank you for your time and much love and appreciation for your guys hard work!

MALE FIRST NAMES:
kaliko (Hawaiian Name)
kamalu (Hawaiian Name)

FEMALE FIRST NAMES:
moani (Hawaiian Name)
puanani (Hawaiian Name)
haunani (Haunani-Kay Trask - Hawaiian Activist / Educator)
pegge (Pegge Hopper - Artist)
nikela (nikela.com directs to a LinkedIn profile | African Name)

SURNAMES:
pegge (Edward Pegge - Rugby Player)
kawananakoa (David Kawananakoa - Prince of Hawaii)
kahele (Kaiali'i Kahele - Politician)
gehringer (Charlie Gehringer - Baseball Player)
kiner (Ralph Kiner - Baseball Player)
sisler (George Sisler - Baseball Player)
eckersley (Dennis Eckersley - Baseball Player)
kurkjian (Tim Kurkjian - MLB Analyst)
rottet (Lauren Rottet - Architect / Designer)
ossipoff (Vladimir Ossipoff - Architect)

Mahalo

**Comment by shukaeth** [comment]
Hi mahalo! 
Thx I will add them to the categories :)
