### ISSUE TITLE
Domain-Category

### ISSUE THREAD

**Issue by yourdesignerbogd** [Zimtente/ens-collections#665]
Hi!

I just wanted to ask you to add a domain **excude.eth** to the category of **verbs**.

Thank you in advance and good luck in your business

**Comment by shukaeth** [comment]
Hi, I can't find excude in dict - only "exude" - did you mean this one?

![image](https://user-images.githubusercontent.com/107618056/189525551-3470cd90-882e-4d15-87ce-abd00c40af54.png)

**Comment by yourdesignerbogd** [comment]
> Привет, я не могу найти excude в dict - только "exude" - ты имел в виду этот?
> 
> ![изображение](https://user-images.githubusercontent.com/107618056/189525551-3470cd90-882e-4d15-87ce-abd00c40af54.png)
<img width="670" alt="Снимок экрана 2022-09-11 в 16 47 48" src="https://user-images.githubusercontent.com/113144573/189525900-6e9246bf-1cd8-426a-9c31-dd1943d3227d.png">

heey! I found this when I was looking for rare verbs (https://bookstr.com/list/12-obscure-verbs-youve-never-heard-of/)

**Comment by shukaeth** [comment]
nice thank you! :)
