### ISSUE TITLE
Please add "Goll.eth" to 4-letter dictionary, surnames. 

### ISSUE THREAD

**Issue by NicholasBelardo919** [Zimtente/ens-collections#666]
Explanation why the item should be added/removed from a collection- Becasue it is in fact a surname to many people and it is indeed a 4-letter word. 

Collection Name- 4-letter dictionary, surnames

Name of the item- "Goll.eth"

(Optional) Token ID of the item- 108771458461342115264547935891961103025281602743939053124417050639799466513235

![image](https://user-images.githubusercontent.com/113144918/189235372-6561f643-f5f0-4cf3-be43-fe419c935026.png)

**Comment by shukaeth** [comment]
hi thx for screenshots and source :) will be added
