### ISSUE TITLE
Add "ced.eth" to 3 Letter First Names, Male First Names, Female First Names

### ISSUE THREAD

**Issue by andy8888miles** [Zimtente/ens-collections#667]
Explanation why the item should be added/removed from a collection: 
Ced should be added to 3 Letter First Names' and 'Male First Names' and 'Female First Names' because it is a first name with three letters and both a Male & Female first name. It is a given name & a shortened version of (Cedric or Cedrick)

Collection Name(s): First Names, Male First Names, Female First Names
Name of the item: ced.eth

(Optional) Token ID of the item: [114018566238393226557411537248715009106208541655794969171762392349486009448908](https://etherscan.io/token/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85?a=114018566238393226557411537248715009106208541655794969171762392349486009448908)

Other details:
Pronunciation: (sed)
Form of: Cedric
The name Ced is used mostly in English speaking countries but also in a few other countries and languages of the world. Old English origin, and the name Ced means "kind and loved". Ced is a variant form of [Cedric](http://www.thinkbabynames.com/meaning/1/Cedric) (Old English).

THANK YOU! :)
<img width="683" alt="Screenshot 2022-09-08 at 11 46 40 PM" src="https://user-images.githubusercontent.com/113157985/189267669-4d697cec-8583-4b08-8d1b-72ae8b7e8b84.png">

**Comment by shukaeth** [comment]
hi thx for including the source - helps a lot! will be added :)
