### ISSUE TITLE
Add domains to categories 

### ISSUE THREAD

**Issue by bly99** [Zimtente/ens-collections#670]
Hello team!  I have been waiting for a long time and there is no answer to my pull requests.
So should I reduce the number of domains or send issues instead of a pull requests? Or will my requests be processed later? I just need an answer so that I can make everything more convenient for you and speed up the process, cause don't really want to wait for months. thanks for understanding and thanks in advance for your reply.
Pull requests: 
https://github.com/Zimtente/ens-collections/pull/628
https://github.com/Zimtente/ens-collections/pull/635
https://github.com/Zimtente/ens-collections/pull/637

**Comment by shukaeth** [comment]
hello, sorry for the long waiting time, we have some catching up to do here and there is still a long way to go - we will be looking at the pull requests over the next week! thx for your patience :)

**Comment by bly99** [comment]
thank you very much! ))
