### ISSUE TITLE
Please add "cottman.eth" to Surnames

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#671]
Explanation why the item should be added/removed from a collection: Cottman should be added to surnames because it is a common last name and is also the name of multiple bridges in the United States and streets.

Collection Name: Surnames

Name of the item: Cottman.eth
(Optional) Token ID of the item: 23652888085954892150775667620120314112914167836718611133679328373006806442

![image](https://user-images.githubusercontent.com/103213586/189466477-da3b9c07-714f-40a0-949e-684e87c13d9d.png)

**Comment by shukaeth** [comment]
thx will be added too!
