### ISSUE TITLE
Please add "gallman.eth" to Surnames

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#672]
Explanation why the item should be added/removed from a collection: Gallman should be added to the Surname collection because it is a centuries old surname which has scottish ties and scottish origin.
Collection Name: Surnames

Name of the item: Gallman.eth

(Optional) Token ID of the item: 80219733802977558409343409537889895892344177282400373995266544256177102780570

![image](https://user-images.githubusercontent.com/103213586/189466839-3f803c1d-277e-490e-bb29-f16949fcfb6d.png)

**Comment by shukaeth** [comment]
thx will be added!
