### ISSUE TITLE
Add “hox.eth” to 3 letters words, english nouns and english verbs.

### ISSUE THREAD

**Issue by subwd** [Zimtente/ens-collections#673]
hox

Verb (transitive)

1.  archaic, dialect
to hamstring, to hock

Noun

2.  anatomy archaic, rare
a hamstring
3.  genetics
a homeobox or homeotic gene
A team searched the genome of the zebrafish for Hox genes, which control development of the head-to-tail axis of the body.

**Comment by shukaeth** [comment]
thx will be added
