### ISSUE TITLE
Please add "yapok.eth" to 5 Letter Dictionary, English Nouns

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#684]
Why the item should be added/removed from a collection: It is a word in the English Language that is indeed 5 letter and also an English Noun, screenshot shown below vvv.

Collection Name(s): 5 Letter Dictionary, English Nouns

Name of the Item: yapok.eth

Token ID of the Item: 60735816303015937340765152819790897328651501808062910527338810292861307009775

![image](https://user-images.githubusercontent.com/103213586/189506491-56daaa87-15a2-4d70-86f3-b290a943afdd.png)

**Comment by shukaeth** [comment]
thx will be added!
