### ISSUE TITLE
Please add "serer.eth" to the 5 Letter Dictionary, English Nouns

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#685]
Why the item should be added/removed from a collection: It is a word in the English Language that is indeed 5 letter and also an English Noun, screenshot shown below vvv.

Collection Name(s): 5 Letter Dictionary, English Nouns

Name of the Item: serer.eth

Token ID of the Item: 108286223235279507163530141946064263812275010807907438630657249810564242856035

![image](https://user-images.githubusercontent.com/103213586/189506474-6d079dae-cf06-45ef-9e6a-96e831bea58d.png)

**Comment by shukaeth** [comment]
thx will be added!
