### ISSUE TITLE
Add to Collection 5LD (5 Letter Dictionary) - English word list

### ISSUE THREAD

**Issue by eselby84** [Zimtente/ens-collections#686]
Listed here are five-letter English words to add to the collection 5LD (5 Letter Dictionary). Definitions and part of speech included for support. CSV file attached as well.

[Word List - 5 Letter Dictionary.csv](https://github.com/Zimtente/ens-collections/files/9541670/Word.List.-.5.Letter.Dictionary.csv)

## ENS Domain List ##
balop.eth; bejel.eth; couru.eth; cropt.eth; cruor.eth; culch.eth; cupel.eth; cymar.eth; decyl.eth; degut.eth; dhuti.eth; droke.eth; drouk.eth; eusol.eth; ewery.eth; faugh.eth; fauld.eth; ghaut.eth; glomi.eth; gulae.eth; hapuu.eth; hoked.eth; ileac.eth; ileal.eth; inurn.eth; irids.eth; iteas.eth; izars.eth; izbas.eth; jirds.eth; kaons.eth; kelep.eth; khoja.eth; kibei.eth; kibes.eth; kilij.eth; kinin.eth; kists.eth; kiyis.eth; knars.eth; knurs.eth; kobos.eth; kyats.eth; laics.eth; lathy.eth; laxes.eth; loids.eth; luged.eth; lyase.eth; mahwa.eth; maneb.eth; moits.eth

## Explanation & Support ##
Item Name: **balop.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 82799917156192455714729978917644193565920460275839471400160471090997090724799
Part of Speech: noun
Definition: a photographic print made on smooth, matte, double-weight paper, used especially in television advertisements.

Item Name: **bejel.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 95203157643033482126372613917279150314834859263667320273981491871903930971346
Part of Speech: noun
Definition: a nonvenereal syphilis occurring mainly among children

Item Name: **couru.eth**
Collection: 5 Letter Dictionary; English Adjectives
Token ID: 76743265220972944580997403349761650817169670221836436509389497853672044643561
Part of Speech: adjective
Definition: done or executed with a running step.

Item Name: **cropt.eth**
Collection: 5 Letter Dictionary; English Verbs
Token ID: 10415433857117980954135137462171641249224761907303053259354744331833368127045
Part of Speech: verb
Definition: a simple past tense and past participle of crop.

Item Name: **cruor.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 101791531073609939067519600372481886777524321971271363389604177958230253995509
Part of Speech: noun
Definition: coagulated blood, or the portion of the blood that forms the clot.

Item Name: **culch.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 2721798515544297851601277323473046749947810254292491087653163657955397843985
Part of Speech: noun
Definition: the stones, old shells, etc., forming an oyster bed and furnishing points of attachment for the spawn of oysters.

Item Name: **cupel.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 71915884460612385340119330401000449175053738751836524339446440490724274537641
Part of Speech: noun
Definition: a small, cuplike, porous container, usually made of bone ash, used in assaying, as for separating gold and silver from lead.

Item Name: **cymar.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 111106067839644630020852029408787532234772440857014470102433779535939678424124
Part of Speech: noun
Definition: a woman's short fur-trimmed jacket, popular in the 17th and 18th centuries

Item Name: **decyl.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 36833654407320134774840687704106473963128644872145775581062678006975811125933
Part of Speech: noun
Definition: a group of isomeric univalent radicals, C10H21, derived from the decanes by removing one hydrogen atom.

Item Name: **degut.eth**
Collection: 5 Letter Dictionary; English Verbs
Token ID: 3704405536680452781577352748703284692911791901250141307918137699337498769056
Part of Speech: verb
Definition: to remove the entrails of; disembowel; gut.

Item Name: **dhuti.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 58046005296481428707555591148744408721937930936184658169996581003047825280904
Part of Speech: noun
Definition: the cotton fabric, sometimes patterned, of which the loincloth is made.

Item Name: **droke.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 56621037425276273868369093877981282198077605937220091755196383382595829612029
Part of Speech: noun
Definition: a valley with steeply sloping sides.

Item Name: **drouk.eth**
Collection: 5 Letter Dictionary; English Verbs
Token ID: 35113865681114312221696952064676575303692529888736938563129461700269645043238
Part of Speech: verb
Definition: to wet thoroughly; drench.

Item Name: **eusol.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 87735867394595372702410673150429960353753403689874534978997279914151427232757
Part of Speech: noun
Definition: an antiseptic solution prepared from chlorinated lime and boric acid, formerly used in treating wounds.

Item Name: **ewery.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 90268579744621899794365661586369803250767199854813080381114914745533061792828
Part of Speech: noun
Definition: a room for storing ewers, towels, napkins, etc.

Item Name: **faugh.eth**
Collection: 5 Letter Dictionary; 
Token ID: 46735683175892387294724875611157015526567736547381982442842972653868777498425
Part of Speech: interjection
Definition: (used to express contempt or disgust.)

Item Name: **fauld.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 60091005375415021161558799548087412158458552796471644851823592491267903960523
Part of Speech: noun
Definition: a piece below the breastplate, composed of lames and corresponding to the culet in back.

Item Name: **ghaut.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 55595052790467751939162787189292348980803491065434733096087712324626955436253
Part of Speech: noun
Definition: Caribbean a small cleft in a hill through which a rivulet runs down to the sea

Item Name: **glomi.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 65184925052800405187898006995618563943737194227617439914800396868266353386570
Part of Speech: noun
Definition: a small globular body.

Item Name: **gulae.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 45669867637401104906260149200927105981444916260043012908109961435563245481411
Part of Speech: noun
Definition: the upper part of the throat or gullet.

Item Name: **hapuu.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 100142228693164920339985315198553252502826533278877196747407807247990483664247
Part of Speech: noun
Definition: a Hawaiian tree fern, Cibotium splendens, the cut trunks of which are used in horticulture as pots and planters.

Item Name: **hoked.eth**
Collection: 5 Letter Dictionary; English Verbs
Token ID: 80439451920173157055977970446659137583376563544308471975546731465648098345271
Part of Speech: verb
Definition: to alter or manipulate so as to give a deceptively or superficially improved quality or value

Item Name: **ileac.eth**
Collection: 5 Letter Dictionary; English Adjectives
Token ID: 37630442855318301420476337586306895420329954427038048833167922666921982354419
Part of Speech: adjective
Definition: of or relating to the ileum.

Item Name: **ileal.eth**
Collection: 5 Letter Dictionary; English Adjectives
Token ID: 51654375967891470403285731235935257839838126114137423835993298694954768187279
Part of Speech: adjective
Definition: Of or relating to the ileum.

Item Name: **inurn.eth**
Collection: 5 Letter Dictionary; English Verbs
Token ID: 71998647528079534499465661782351359366145476853000613053052971233979141416022
Part of Speech: verb
Definition: to put into an urn, especially ashes after cremation.

Item Name: **irids.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 61367878718026654276074919751489349046884846751862776413916988599238597692147
Part of Speech: noun
Definition: any plant belonging to the Iridaceae, the iris family.

Item Name: **iteas.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 115622564400679366016542945813308760723606251751998529233887749506953574492278
Part of Speech: noun
Definition: any tree or shrub belonging to the genus Itea, of the saxifrage family

Item Name: **izars.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 4593525127227905816859675454232801863364254733632829619640199074743239245260
Part of Speech: noun
Definition: a long, usually white cotton dress that covers the body completely, worn by women of North Africa and the Middle East.

Item Name: **izbas.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 6370225932099040357599639111833745858511047149485382495414033673197331804620
Part of Speech: noun
Definition: the traditional log house of rural Russia, with an unheated entrance room and a single living and sleeping room heated by a clay or brick stove.

Item Name: **jirds.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 33288264269385261237717605563570699160539305067900739883333850722876759155877
Part of Speech: noun
Definition: any of several species of small, burrowing rodents of the genus Meriones, subfamily Gerbillinae, inhabiting dry regions of Asia and northern Africa.

Item Name: **kaons.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 92043859847170234559645976594976833265282974587246630585991726868264771518245
Part of Speech: noun
Definition: a meson with strangeness +1 and either positive or zero electric charge, or its antiparticle, with strangeness −1 and either negative or zero electric charge.

Item Name: **kelep.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 109028458484545011325129584097713671150795805593044862308583521067045327375337
Part of Speech: noun
Definition: a stinging ant, Ectatomma tuberculatum, introduced into the U.S. from Guatemala, that preys on the boll weevil.

Item Name: **khoja.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 10807446153439206902268036785261751162386544932005846808467468821258166117031
Part of Speech: noun
Definition: a teacher in a Muslim school.

Item Name: **kibei.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 71886860712742276110461754368366093706016736369448326705269272509794222245391
Part of Speech: noun
Definition: a person of Japanese descent, born in the U.S. but educated in Japan.

Item Name: **kibes.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 2115657240748564816334860792781139144365720450728802340046344399218191903987
Part of Speech: noun
Definition: a chapped or ulcerated chilblain, especially on the heel.

Item Name: **kilij.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 87135234908718432820819140817034355991351782033667319204820264271071724636861
Part of Speech: noun
Definition: a Turkish saber with a crescent-shaped blade, sharp on the entire convex edge and sharp on the opposite edge for about 8 inches (20 centimeters) back from the point.

Item Name: **kinin.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 91040965275120767695803187260310855748873567926222745685962131905948886737652
Part of Speech: noun
Definition: any of a group of hormones, formed in body tissues, that cause dilation of blood vessels and influence capillary permeability.

Item Name: **kists.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 3821831455674068536327123123582636645778076049641844192274299281135438482487
Part of Speech: noun
Definition: a coffer; a money chest.

Item Name: **kiyis.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 63963443091858145297492642712871198283325176220850898028241069821253783410693
Part of Speech: noun
Definition: a small whitefish, Coregonus kiyi, found in the deeper waters of the Great Lakes.

Item Name: **knars.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 48453678857602667049943380097678655029446994859537590386492381686793735060052
Part of Speech: noun
Definition: a knot on a tree or in wood.

Item Name: **knurs.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 72259570510965641977729647788781024476385123970490986025666891023958867646966
Part of Speech: noun
Definition: a knotty or hard protuberance or growth, as on a tree.

Item Name: **kobos.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 28666517507162774287002957689078694357022713216105383098774164316676320949482
Part of Speech: noun
Definition: a bronze coin and monetary unit of Nigeria, one 100th of a naira.

Item Name: **kyats.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 26432645751577512099466329884138237426824728660691521153501140181857502569433
Part of Speech: noun
Definition: a paper money, cupronickel coin, and monetary unit of Myanmar (Burma), equal to 100 pyas.

Item Name: **laics.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 92991411387172124670425806797312956377833218026259205609774653962469629600536
Part of Speech: noun
Definition: one of the laity.

Item Name: **lathy.eth**
Collection: 5 Letter Dictionary; English Adjectives
Token ID: 47523456313189688162195832683494065271140373183603429045576102582983894953230
Part of Speech: adjective
Definition: lathlike; long and thin.

Item Name: **laxes.eth**
Collection: 5 Letter Dictionary; English Adjectives
Token ID: 33117491590485007053530143744022674651366123241273999732452554893977186338635
Part of Speech: adjective
Definition: not strict or severe; careless or negligent:

Item Name: **loids.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 100287485740773657137904297138685180512251417894949464099400186729500918127754
Part of Speech: noun
Definition: a thin piece of celluloid or plastic so used, as by a burglar.

Item Name: **luged.eth**
Collection: 5 Letter Dictionary; English Verbs
Token ID: 10415844754056935679755754684480122134882389196860823234321211873697523604480
Part of Speech: verb
Definition: to go or race on a luge:

Item Name: **lyase.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 65448801819697223922342653769686470714239578469152947221314384602395355488352
Part of Speech: noun
Definition: any of various enzymes, as decarboxylase, that catalyze reactions involving the formation of or addition to a double bond.

Item Name: **mahwa.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 102389239205470202213522040519223723029729032063857681094338354673340579592123
Part of Speech: noun
Definition: any of several trees of the genus Madhuca, of the sapodilla family

Item Name: **maneb.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 107021404290641638048201492606783061076778026017776102149980556011466805476849
Part of Speech: noun
Definition: a carbamate fungicide, C4H6MnN2S4, used for control of numerous crop diseases.

Item Name: **moits.eth**
Collection: 5 Letter Dictionary; English Nouns
Token ID: 49905426825661406181796302375085625739939753880397509146014948335722945107630
Part of Speech: noun
Definition: a foreign particle found in wool, as a burr, twig, or seed.

**Comment by shukaeth** [comment]
hi thx - I will add them!
