### ISSUE TITLE
Thai 999 Club

### ISSUE THREAD

**Issue by Ousterrr** [Zimtente/ens-collections#69]
Thai Numbers 000-999

List: https://pastebin.com/jpCYA2GW

Logo: https://cdn.discordapp.com/attachments/992978748322353242/993035253948108800/thai.jpg

Twitter: https://twitter.com/Thai999club

Slug: thai-999-club

Description: An exclusive club for ๐๐๐-๙๙๙.eth Thai ENS holders

**Comment by tunnckoCore** [comment]
Already added.
