### ISSUE TITLE
Please add these names to SURNAMES

### ISSUE THREAD

**Issue by basestation-eth** [Zimtente/ens-collections#692]
Hi There, please add these domains

SURNAME

taggard, 11867697882265025841908754089817963029838979078883719538927637827964259222743
smithee, 38704143695392363798345233416548403044551581432718032402729056060294222307472
engberg, 71203775526824721367915118779278580388924425036933164838617522023496927051552

![image](https://user-images.githubusercontent.com/110099007/189522907-d37ed5c1-d10f-4070-816f-be8e84fa23db.png)
![image](https://user-images.githubusercontent.com/110099007/189522916-8f23be7c-2b8c-4f13-9d4e-5e7dfbdf1d25.png)
![image](https://user-images.githubusercontent.com/110099007/189522928-5b3076e5-6b51-4fa0-9149-c0c8f74e45f8.png)

**Comment by shukaeth** [comment]
thx will also be added!
