### ISSUE TITLE
Please add this name to FEMALE FIRSTNAME

### ISSUE THREAD

**Issue by basestation-eth** [Zimtente/ens-collections#693]
Hi there, please add this domains

FEMALE FIRST NAME

laifeng, 36866952477817144309441342298585294518166251991048587351835988437623824638513

![image](https://user-images.githubusercontent.com/110099007/189523101-d727c8cc-f8e8-43d4-b6b7-547409cd456c.png)

**Comment by shukaeth** [comment]
Hi thx, will be added!
