### ISSUE TITLE
Please add this name to MALE FIRSTNAME

### ISSUE THREAD

**Issue by basestation-eth** [Zimtente/ens-collections#694]
Hi there, please add this domain

MALE FIRST NAME

kunhang, 59993294629360299453302348349202940742054102179829606776128187731582147209151

![image](https://user-images.githubusercontent.com/110099007/189523213-f13bbcd4-e83e-437d-9d84-cc90070f927f.png)

**Comment by shukaeth** [comment]
Hi thx will be added!
