### ISSUE TITLE
Add to Surnames category

### ISSUE THREAD

**Issue by echoghi** [Zimtente/ens-collections#695]
- Collection: Surnames
---

- Name of Item: sandhagen.eth
- Token ID: 53939938147536373860009198506573984101484938958320401993848680175934302142111

---
- Name of Item: chikadze.eth
- Token ID: 100469197873560582466202990378002896323205880940626735806940314240595518740301
---
- Name of Item: cannonier.eth
- Token ID: 84396396656348357491418629461967016032885183626745819670889277130129368971703
---
- Name of Item: rakić.eth
- Token ID: 22944391707431231766599057976572730245343838039046525562888564707230375909212
---
- Name of Item: royval.eth
- Token ID: 112393954504133871965972938737434602594435085154670351576734258664788655781347
---
- Name of Item: dvalishvili.eth
- Token ID: 101712180564210315390057671706084094337216748287166137589558636414982312693446
---
- Name of Item: askarov.eth
- Token ID: 92957621750629967444106992928431520384376109417476552223125845911991791592894
---
- Name of Item: ankalaev.eth
- Token ID: 88322490291409957416094240263544707790122086041902161852209029799922634417116

**Comment by shukaeth** [comment]
thx will be added!
