### ISSUE TITLE
Please add 1 Word to the 4L dictionary

### ISSUE THREAD

**Issue by monkeydluffy-eth** [Zimtente/ens-collections#698]
https://www.ens.vision/categories/4-letter-dictionary

Explanation: Was cross referencing the Webster Dictionary of 4L vs the list and found owie.eth, I figure that Webster is legit enough. 
Collection Name: 4 Letter Dictionary
Name of the item: owie
(Optional) Token ID of the item: 79709949127900439444398468802119822022153579764576672109366944699777130924494

**Comment by shukaeth** [comment]
thx will be added to nouns as well!
