### ISSUE TITLE
Male Firstnames - PLEASE ADD - mpho.eth | vusi.eth | tokollo.eth

### ISSUE THREAD

**Issue by xin-xinusu** [Zimtente/ens-collections#699]
Hi Please add the following to Male Firstnames

*************************************************************************

name: mpho.eth 
tokenId: 74323614153362604038175589480005850086944514784097598314420688237422594274106

*************************************************************************

name: vusi.eth
tokenId: 107949305314964775029199195052811806270101520764792227089363357259575676059617

*************************************************************************

name: tokollo.eth
tokenId: 33265339656580344236185081017455376810911827503809903312976815026141811704595

**Comment by shukaeth** [comment]
thx will be added
