### ISSUE TITLE
Female Firstnames - PLEASE ADD - cathee.eth | roxee.eth

### ISSUE THREAD

**Issue by xin-xinusu** [Zimtente/ens-collections#700]
Hi Please add the following to Female FirstNames

*************************************************************************

name: cathee.eth 
tokenId: 31461815162462526861314375740908370212298765846492329494307285464587201550377

*************************************************************************

name: roxee.eth
tokenId: 108752811701659886689345529004654825659391135041799509116493103869851961552484

**Comment by shukaeth** [comment]
thx will be added!
