### ISSUE TITLE
Surnames - PLEASE ADD - wantsai.eth | wan-tsai.eth

### ISSUE THREAD

**Issue by xin-xinusu** [Zimtente/ens-collections#701]
Hi Please add the following to Surnames

*****************************************
name: wantsai.eth
tokenId: 18418583308053559761701396165054481036545789121682736219461081451801916270364

*****************************************

name: wan-tsai.eth
tokenId: 10731631965359535803829471243909864035234470352518408360731086579963158828708

**Comment by shukaeth** [comment]
thx will be added!
