### ISSUE TITLE
Male First Names - Please Add

### ISSUE THREAD

**Issue by 064eth** [Zimtente/ens-collections#707]
yonglin.eth
shuyan.eth
satty.eth
jinder.eth
harps.eth
mingyang.eth
manj.eth
ammy.eth
harj.eth
mandip.eth
shubdeep.eth
gurnam.eth
diljeet.eth
tajinder.eth
navpreet.eth
gurmail.eth
jeeti.eth
gurveen.eth
amarpreet.eth
malkit.eth
parmjit.eth

**Comment by shukaeth** [comment]
thx will be added!
