### ISSUE TITLE
wrong twitter

### ISSUE THREAD

**Issue by shnmvn** [Zimtente/ens-collections#71]
Hi, there is a collection that got an inactive twitter, as an holder I create an active page of the collection and I am now working on it promoting on the social media.Can you change the twitter page of the collection with mine? I can send my twitter page I will open discord soon
so people know that I am active as a page social media, and not the inactive page
999 CN Club
零零零 - 九九九 (simplified)
the inactive page is:@999CNClub
my page, that one that is active for the community is:@999cndigit
we are getting volume so it's better for people if they know the real page in my opinion

**Comment by tunnckoCore** [comment]
eeerm.. i commented on that issue.. what happened..

Seems like it's already updated on the site for some reason: https://www.ens.vision/categories/999-cn-club
