### ISSUE TITLE
Please add these three words to 4-letter dictionary 

### ISSUE THREAD

**Issue by NicholasBelardo919** [Zimtente/ens-collections#710]
Explanation why the item should be added/removed from a collection- These words do in fact have definitions, a meaning, and are 4 letters long.

Collection Name- 4-letter dictionary 

Name of the item- Kide    Qaly     Mank 

(Optional) Token ID of the item-             
Kide- 37600494519724785884978028062193832284751666553300422784103502162333918374306
Qaly- 50262597254385957451081577759284162893883088779042637949354421822554076703377
Mank- 48474990296723769482567268448984934695001165374820573186228907646616202096437

![Screenshot 2022-09-12 150904](https://user-images.githubusercontent.com/113144918/189736140-3209972d-f3d3-4ca5-8ca0-4a632b32bf1e.png)

![Screenshot 2022-09-12 150931](https://user-images.githubusercontent.com/113144918/189736148-71f6a3c3-3c7c-4951-98dd-37fa2f82d811.png)

![Screenshot 2022-09-12 151002](https://user-images.githubusercontent.com/113144918/189736157-2c4e991c-4167-4159-adb9-a78f1b7eadf8.png)

Thank you!

**Comment by shukaeth** [comment]
hey thx will be added!
