### ISSUE TITLE
Please add “Siss.eth” to 4 Letter Palindromes 

### ISSUE THREAD

**Issue by cykapizdetz** [Zimtente/ens-collections#711]
Please add “siss.eth” which starts with the letter ‘s’ and ends with ‘s’. 
Collection: 4 Letter Palindromes 
Name: siss.eth
ID: 109135081902184372256839945766567237768174722940383828918035981986857427407060

**Comment by shukaeth** [comment]
hey, siss is not a palindrome, apalindrome is a word, phrase, number, or sequence of words that reads the same backward as forward - so it would be siis or ssss or issi ...

**Comment by cykapizdetz** [comment]
I see now, thank you for your time.
