### ISSUE TITLE
Please add "esos.eth" to 4 Letter Dictionary

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#713]
Explanation why the item should be added/removed from a collection: Is a 4 letter word in English and Spanish as well.

Collection Name: 4 Letter Dictionary

Name of the item: Esos.eth

(Optional) Token ID of the item: 86652595075539002719166415692068079151119075149682563556060649445926176430461

**Comment by shukaeth** [comment]
hey, sorry I can't find it as a proper word in a dict - can u send me the source? (for english)

thanks!

**Comment by zo16950** [comment]
> hey, sorry I can't find it as a proper word in a dict - can u send me the source? (for english)
> 
> thanks!


I believe it means an Executive share option scheme but I'm not quite sure. Thank you for the quick response though! Appreciate it. 
![image](https://user-images.githubusercontent.com/103213586/190141513-5f6a0494-fc24-474b-a7e3-d3254c43862d.png)

**Comment by shukaeth** [comment]
perfect thx! will be added :)

**Comment by zo16950** [comment]
Does this count? Not quite sure. Thank you.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
