### ISSUE TITLE
Please add Benefactress.eth to English Nouns

### ISSUE THREAD

**Issue by xcraftediv** [Zimtente/ens-collections#715]
Benefactress.eth - ID: 39562990837993113313351158677424747198322781461230897004103407555634659876259

ben·​e·​fac·​tress | \ ˈbe-nə-ˌfak-tris  \ Noun
Definition of benefactress
: a woman who is a [benefactor](https://www.merriam-webster.com/dictionary/benefactor)

https://www.merriam-webster.com/dictionary/benefactress

**Comment by shukaeth** [comment]
thx will be added!
