### ISSUE TITLE
Please add Pertinence.eth to English Nouns

### ISSUE THREAD

**Issue by xcraftediv** [Zimtente/ens-collections#716]
Pertinence.eth - ID: 44822413397140930227341696061039287435344567890810045841099388944771323832254

per·​ti·​nence | \ ˈpər-tə-nən(t)s  , ˈpərt-nən(t)s \ Noun
Definition of pertinence
: the quality or state of being [pertinent](https://www.merriam-webster.com/dictionary/pertinent) 

https://www.merriam-webster.com/dictionary/pertinence

**Comment by shukaeth** [comment]
thx will be added!
