### ISSUE TITLE
Please add Layin.eth to English Nouns

### ISSUE THREAD

**Issue by xcraftediv** [Zimtente/ens-collections#717]
Layin.eth - ID: 108356098940897815258055996078911635948687136513000971116832411779630408054010

Definition of layin (Entry 1 of 2) Noun
: [LAYUP sense 2](https://www.merriam-webster.com/dictionary/layup)

https://www.merriam-webster.com/dictionary/layin

**Comment by shukaeth** [comment]
thx will be added!
