### ISSUE TITLE
Please add "joll.eth" to 4 Letter Dictionary 

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#719]
Explanation why the item should be added/removed from a collection: Joll.eth should be added to 4 Letter Dictionary, because it is in fact a real word in English with a meaning.

Collection Name: 4 Letter Dictionary

Name of the item: Joll.eth

(Optional) Token ID of the item: 8709141777516290768756576535701691598455639913330559984748064665107723127973

![image](https://user-images.githubusercontent.com/103213586/189840145-019dc323-9a01-4f47-89cd-7d31e230ff96.png)

**Comment by shukaeth** [comment]
hi thx will be added!
