### ISSUE TITLE
Please add "roop.eth" to 4 Letter Dictionary, English Nouns

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#720]
Explanation why the item should be added/removed from a collection: "Roop.eth" should be added to 4 Letter Dictionary and English Nouns because it is indeed an English noun and contains 4 letters.

Collection Name: 4 Letter Dictionary, English Nouns

Name of the item: Roop.eth

(Optional) Token ID of the item: 101272913896397166791038282898226326119114057506834992590511784151984274424840

![image](https://user-images.githubusercontent.com/103213586/189840911-ee2315cc-498c-48b6-a9e6-0e92390e8919.png)

**Comment by shukaeth** [comment]
thx will be added!
