### ISSUE TITLE
Add "TWP" to 3 Letter Dictionary Words category

### ISSUE THREAD

**Issue by vinod-veera** [Zimtente/ens-collections#722]
TWP.eth needs to be added into 3LW (3 Letter Dictionary Words) https://www.ens.vision/categories/3-letter-dictionary
As it is a valid scrabble and dictionary word.

Definition of 'twp'
in British English
ADJECTIVE
(predicative) South Wales dialect
[foolish] [daft]
Word origin
Welsh

Reference:
https://www.collinsdictionary.com/dictionary/english/twp
https://word-finder.mobi/is-twp-valid-scrabble-word
https://scrabble-word.com/dictionary/twp

twp.eth
Token ID: 105081018997422319528462444824527343451616345931687457195569073115783635797420

Collection:
https://www.ens.vision/categories/3-letter-dictionary
3 Letter Dictionary
English 3 letter dictionary words.
3LW

**Comment by shukaeth** [comment]
hey thx, will be added!
