### ISSUE TITLE
Please add these to Emoji list 

### ISSUE THREAD

**Issue by NicholasBelardo919** [Zimtente/ens-collections#725]
Explanation why the item should be added/removed from a collection- these are indeed emojis, one is a triple, and one is a double 

Collection Name- Triple emoji/double emoji 

Name of the item-
Triple- 💇🏻‍♀💇🏻💇🏻‍♀
Double-🤽🏻‍♂🤽🏻

(Optional) Token ID of the item
💇🏻‍♀💇🏻💇🏻‍♀- 53393071816961471563238287909266042176601582955283600619999967821213066927773
🤽🏻‍♂🤽🏻- 69796315642259440208611946226706624933249582554032355730435531376983749532904

![Screenshot 2022-09-13 181203](https://user-images.githubusercontent.com/113144918/190018589-13e4e42b-274f-4142-908a-19f97332d483.png)
![Screenshot 2022-09-13 181138](https://user-images.githubusercontent.com/113144918/190018601-4c073eb1-7323-414c-9f1a-189507f32b5e.png)

Thank you!

**Comment by shukaeth** [comment]
Hi those are also not valid Double and Triple Emojis as they consist of 10 chars and 6 chars.
Double Ethmojis consist of **4** / Triple Ethmojis of **3** characters.
![image](https://user-images.githubusercontent.com/107618056/202914806-c370bfd5-7d5d-47e7-a5b7-23d189036253.png)
![image](https://user-images.githubusercontent.com/107618056/202914820-f3a1359e-d610-4d5b-91e6-fdc49743d2e3.png)
