### ISSUE TITLE
Please add this emoji to triple list

### ISSUE THREAD

**Issue by NicholasBelardo919** [Zimtente/ens-collections#726]
Explanation why the item should be added/removed from a collection- this emoji is one of the true emojis and can be added to the list. 

Collection Name- Triple ethmoji 

Name of the item- 🏃‍♀️🏃‍♀️🏃‍♀️  

(Optional) Token ID of the item- 94896766619984752174124171183333139421778183677522954601971686008103674619014

Thank you!

**Comment by shukaeth** [comment]
Hi same here, this is not a triple ethmoji, as it cosists of **9 characters.** Triple Ethmojis consist of **3** characters.
![image](https://user-images.githubusercontent.com/107618056/202914722-1855f096-9b6f-4099-8443-956704917f44.png)
