### ISSUE TITLE
Please add this emoji to triple list

### ISSUE THREAD

**Issue by NicholasBelardo919** [Zimtente/ens-collections#727]
Explanation why the item should be added/removed from a collection- This emoji is also one of the true emojis. 

Collection Name- Triple ethmoji

Name of the item- 👩‍🦽👩‍🦽👩‍🦽 

(Optional) Token ID of the item- 76814001582618949380123413021480522311439475532210540683862372057157761718348

Thank you!

**Comment by shukaeth** [comment]
Hi this is not a valid triple emoji. Explanation: To be a valid triple Ethmoji the name must have a length of **3 characters.**. Your address consists of 12 characters. 
![image](https://user-images.githubusercontent.com/107618056/202914341-f78f9410-bb6d-4646-b413-64427b0db4aa.png)

Please always check before buying such names / raising a ticket. Here is a valid Triple Ethmoji for comparison.
![image](https://user-images.githubusercontent.com/107618056/202914425-9e05becf-8a83-4d19-a10c-b2201071c1b3.png)

All the best,

shuka.eth
