### ISSUE TITLE
Please add to english nouns category

### ISSUE THREAD

**Issue by Kups2323** [Zimtente/ens-collections#729]
Hello, I have several english nouns that I would appreciate if they were added to the category. Thank you.

chandlery.eth
digitalconsulting.eth
yachtchandler.eth
yachtchandlers.eth
digitaldoctor.eth
cryptoscience.eth
executiveconsultant.eth
principalconsultant.eth
legislativedirector.eth
virtualautomobile.eth
floridasolar.eth
californiasolar.eth

**Comment by shukaeth** [comment]
hey, I only could find chandlery in dict - added this to nouns - all others exist of two words and are not proper nouns - there will be a category for 2-word domains soon :)
