### ISSUE TITLE
Add 3L Word Request

### ISSUE THREAD

**Issue by BarryMacockiner** [Zimtente/ens-collections#739]
mup.eth should be added because it is a 3L word. Mup:noun. DEFINITIONS1. 1. minimum unit pricing: a measure banning retailers from selling alcoholic drinks at less than 50p per unit of alcohol.

3L Dictionary

Mup.eth

12618091303018381378570562966812641777896418838593768435739662897881499400261

**Comment by shukaeth** [comment]
thx I will add it!
