### ISSUE TITLE
Add 69 Ambigram

### ISSUE THREAD

**Issue by fatbastardeth** [Zimtente/ens-collections#74]
{
   "name" : "69 Ambigram"
   "slug" : "69-ambigram"
   "description" : "Ambigrams containing 69 between 3 and 8 digit length."
   "logo" : "69-ambigram.png"
      ![69-ambigram](https://user-images.githubusercontent.com/108626453/177050658-06fdf77e-142e-4dac-883a-68f9f1da402b.png)
   "csv" : "69-ambigram.csv"
      [69-ambigram.csv](https://github.com/Zimtente/ens-collections/files/9035221/69-ambigram.csv)
}

**Comment by tunnckoCore** [comment]
Maybe better would be to have all the `69`s of 999, 10k and 100k instead.

**Comment by fatbastardeth** [comment]
I agree we should also have a basic 999, 10k, and 100k "69" category.  However, I feel these numbers are hardly random. An ambigram means it can be rotated 180 degrees and still read the same. "69" being the simplest example. This csv has every example of an ambigram 8 digits or less that has 69 in it

**Comment by tunnckoCore** [comment]
Yea, they are palindromes too.. But.. they seem random too.

I don't know, sorry. Soon we will have some sort of page for procedure of listing, and voting. We may bring that up there soon.

**Comment by fatbastardeth** [comment]
I appreciate it. You are right tho, offering a general 69 category first makes more sense. I have the info for 3 digit and 4 digit 69, and will make a fresh submission for those shortly. If you guys want to revisit the ambigrams later on please don't hesitate to ask if you need anything.
