### ISSUE TITLE
Please add "puh.eth" to 3 Letter Dictionary

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#740]
Explanation why the item should be added/removed from a collection: It should be added because puh is a valid scrabble word and also has a definition in the English Language.

Collection Name: 3 Letter Dictionary

Name of the item: Puh.eth

(Optional) Token ID of the item: 50158576806322649743952516842576001334603612666681886228847068851477394999270

![image](https://user-images.githubusercontent.com/103213586/190488027-28a46c28-263f-4633-af8e-54e565205e8d.png)

![image](https://user-images.githubusercontent.com/103213586/190488129-a447036c-bb9d-4ae8-aa0c-f9bad059b1ad.png)

**Comment by shukaeth** [comment]
nice one! will be added :)
