### ISSUE TITLE
List of Surnames - Members of the Media

### ISSUE THREAD

**Issue by eselby84** [Zimtente/ens-collections#741]
Please add the provided list of domains to the Surnames Category. Names were sourced from members of the media, celebrities, and politicians.

The attached CSV includes the same information listed below in an easier-to-read format.
[Surnames 09-15-2022.csv](https://github.com/Zimtente/ens-collections/files/9578463/Surnames.09-15-2022.csv)

## Domain List
midler.eth; pelissero.eth; garafolo.eth; mcginest.eth; sessler.eth; moynahan.eth; sisolak.eth; hanzus.eth; zierlein.eth; giardi.eth; chasmar.eth; pabriks.eth; edholm.eth; jeffri.eth; chadiha.eth; maccormack.eth;

## Support
midler.eth
Bette **Midler**
Occupation: Actress
https://twitter.com/BetteMidler
Followers: 2100000

pelissero.eth
Tom **Pelissero**
Occupation: NFL Author
https://twitter.com/TomPelissero
Followers: 466400

garafolo.eth
Mike **Garafolo**
Occupation: NFL Author
https://twitter.com/MikeGarafolo
Followers: 438100

mcginest.eth
Willie **McGinest**
Occupation: NFL Author
https://twitter.com/WillieMcGinest
Followers: 151400

sessler.eth
Marc **Marc Sessler**
Occupation: NFL Author
https://twitter.com/MarcSessler
Followers: 115900

moynahan.eth
Bridget **Moyhnahan**
Occupation: Model
https://twitter.com/bridgetmoynahan
Followers: 109100

sisolak.eth
Steve **Sisolak**
Occupation: Governor
https://twitter.com/GovSisolak
Followers: 100200

hanzus.eth
Dac **Hanzus**
Occupation: NFL Author
https://twitter.com/DanHanzus
Followers: 98300

zierlein.eth
Lance **Zierlein**
Occupation: NFL Author
https://twitter.com/LanceZierlein
Followers: 93200

giardi.eth
Mike **Giardi**
Occupation: NFL Author
https://twitter.com/MikeGiardi
Followers: 82500

chasmar.eth
Jessica **Chasmar**
Occupation: Fox News Reporter
https://twitter.com/JessicaChasmar
Followers: 80100

pabriks.eth
Artis **Pabricks**
Occupation: Minister of Defence
https://twitter.com/Pabriks
Followers: 43100

edholm.eth
Eric **Edholm**
Occupation: NFL Author
https://twitter.com/Eric_Edholm
Followers: 33500

jeffri.eth [male firstnames]
chadiha.eth
**Jeffri Chadiha**
Occupation: NFL Author
https://twitter.com/jeffrichadiha
Followers: 8110

maccormack.eth
Terry **Maccormack**
Occupation: Press Secretary
https://twitter.com/terrymaccormack
Followers: 941

**Comment by shukaeth** [comment]
Hi thank you for this detailed list! will be added :)
