### ISSUE TITLE
add Bhārat at Countries collection

### ISSUE THREAD

**Issue by MrNice10** [Zimtente/ens-collections#742]
- "Bhārat", is the name for India in Hindi and other several Indian languages
- Countries
- bhārat.eth
- 26567310077102771325701883906561937520705048070954681460240791293876574309565

**Comment by shukaeth** [comment]
Hi I need to do research about this, as currently we just have "english" country names in that category... But I know what you mean, it should also count...

**Comment by shukaeth** [comment]
Hi we go for english versions for now! sry,

greetings, shuka
