### ISSUE TITLE
ADD QEN AT 3 LETTERS FIRST NAMES

### ISSUE THREAD

**Issue by MrNice10** [Zimtente/ens-collections#743]
- "Qen" is a 3 letters word, and is a recognised name, as proof, you can see that "Qen" was an Ancient Egyptian Artisan that provided for many monuments in and around Deir el-Medina.
- 3 Letter First Names
- qen.eth
- 86651592235050347252034013243423339045388825994729875388652386136345410390053

**Comment by shukaeth** [comment]
thx for your input! will be added =)
