### ISSUE TITLE
Please add afn to 3 letter dictionary 

### ISSUE THREAD

**Issue by NicholasBelardo919** [Zimtente/ens-collections#746]
Explanation why the item should be added/removed from a collection- After some searching, I have looked up afn in many different dictionary's online and have seen multiple reports that it is indeed an English valid word. It is indeed a word that means "Assembly of First Nations" although it may not seem it, many websites and worldwide resources do determine this word to exist and be described as a word itself. 

Collection Name- 3 letter dictionary 

Name of the item- afn 

(Optional) Token ID of the item- 15055375367467465791409544309683481050101104093858486733374310150556615130330
 
Here are some resources I found that determine it being a word:

![Screenshot 2022-09-16 174854](https://user-images.githubusercontent.com/113144918/190801563-4dcae4c0-3acf-47b4-ac6e-8a0d9096da6e.png)

![Screenshot 2022-09-16 174915](https://user-images.githubusercontent.com/113144918/190801624-de88a9be-e5cd-4d4f-a13a-4a061ec640f9.png)

![Screenshot 2022-09-16 174928](https://user-images.githubusercontent.com/113144918/190801673-f350ad55-73a5-47be-8533-d37e32fec2ca.png)

Thank you!

**Comment by shukaeth** [comment]
thx will be added!
