### ISSUE TITLE
Add "orv.eth" to 3 Letter dictionary

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#751]
Explanation why the item should be added/removed from a collection: It should be added to the 3 Letter Dictionary because it is in fact a common word that has to deal with English automobiles.

Collection Name: 3 Letter Dictionary

Name of the item: orv.eth

(Optional) Token ID of the item: 32135095843169809916354029781883489917404023771147681414572849302483764633900

![image](https://user-images.githubusercontent.com/103213586/190883573-fe880759-316a-4c2e-9add-a89cd0fb48b4.png)

![image](https://user-images.githubusercontent.com/103213586/190883623-89ec352f-1807-4c96-889c-da14ab4f385b.png)

![image](https://user-images.githubusercontent.com/103213586/190883638-0fe259d6-621a-4047-b4bc-bf9f5cb68731.png)

**Comment by shukaeth** [comment]
thx will be added!
