### ISSUE TITLE
Add "isolationist.eth" to English Nouns

### ISSUE THREAD

**Issue by mamelives** [Zimtente/ens-collections#753]
Explanation why the item should be added/removed from a collection---from Dictionary.com---noun
a person who favors or works for isolationism.

Collection Name---English Nouns

Name of the item---isolationist.eth

Token ID of the item 84800041544206718251225356211084996485434676784532675975706941027256204592376

![Screenshot_20220918-073622](https://user-images.githubusercontent.com/113834432/190900196-f46c28b0-bade-41e8-8c12-8928db3840c2.png)

**Comment by shukaeth** [comment]
thx will be added!

**Comment by mamelives** [comment]
Thank you!!!
