### ISSUE TITLE
Add "commemorating.eth" to English Verbs

### ISSUE THREAD

**Issue by mamelives** [Zimtente/ens-collections#754]
Explanation why the item should be added/removed from a collection---from Dictionary.com---verb (used with object), com·mem·o·rat·ed, com·mem·o·rat·ing.
to serve as a memorial or reminder of:
The monument commemorates the signing of the Declaration of Independence.

Collection Name---English Verbs

Name of the item---commemorating.eth

Token ID of the item 13387963815518271087044462629025509787240175931781400037716685908277734784040
![Screenshot_20220918-074121](https://user-images.githubusercontent.com/113834432/190900345-2cfd746f-bcc5-452a-bcd1-0a0e141c63d7.png)
![Screenshot_20220918-074130](https://user-images.githubusercontent.com/113834432/190900357-c3e52cef-a0ef-45e2-8674-3b421c5f5a90.png)

**Comment by shukaeth** [comment]
thx will be added!
