### ISSUE TITLE
Add "smearcampaign.eth" to English Nouns

### ISSUE THREAD

**Issue by mamelives** [Zimtente/ens-collections#755]
Explanation why the item should be added/removed from a collection---from Dictionary.com---noun;
a campaign to tarnish the reputation of a public figure, especially by vilification or innuendo.

Collection Name---English Nouns

Name of the item---smearcampaign.eth

Token ID of the item
55671480065027179563733070316389247390223079361836494881904008372526163057752
![Screenshot_20220918-074702](https://user-images.githubusercontent.com/113834432/190900569-fcd14e49-b18b-4046-a196-1c655c69ea4f.png)

**Comment by shukaeth** [comment]
thx will be added :)
