### ISSUE TITLE
Add "closedminded.eth" to English Adjectives 

### ISSUE THREAD

**Issue by mamelives** [Zimtente/ens-collections#756]
Explanation why the item should be added/removed from a collection---from merriam-webster.com---adjective
variants: or close-minded
Definition of closed-minded
chiefly US, disapproving
: not willing to consider different ideas or opinions : having or showing a closed mind
He's becoming increasingly closed-minded in his old age.
a very close-minded attitude

Collection Name---English Adjectives

Name of the item---closedminded.eth

Token ID of the item
99541782612169786821872906388564841586143615310674825621247629640523640095963
![Screenshot_20220918-075436](https://user-images.githubusercontent.com/113834432/190900852-dd2682f9-46ac-4d3e-8a36-18dc48963764.png)

**Comment by shukaeth** [comment]
perfect thx for incl. the source! will be added :)

**Comment by mamelives** [comment]
Thank you!!!
