### ISSUE TITLE
Add to Collection: English Nouns

### ISSUE THREAD

**Issue by nilromab** [Zimtente/ens-collections#758]
Reason: These are English nouns that are currently missing from ENS.Vision.
Add to Collection: English nouns
Name + Token IDs:

orangeness   18001668039885750638621129388833760480522691624162697031263969060502851764417
https://dictionary.cambridge.org/dictionary/english/orangeness

purpleness     32201753781767370814730640431993237985966796094965559458382333421483278185708 
https://dictionary.cambridge.org/dictionary/english/purpleness

purple-heart     59020244810133602222003980218600090700573882484176632644557056509450603370911
https://www.merriam-webster.com/dictionary/purpleheart

**Comment by shukaeth** [comment]
thx will be added :)
