### ISSUE TITLE
Please kindly add ENS domain names to relevant categories

### ISSUE THREAD

**Issue by Web3trish** [Zimtente/ens-collections#766]
Hi there,
I have recently listed a total of 150 domain names and only my x10 five digits are currently in categories. Would you please help put the below items in categories as follows and advise if there is an easy way to categorise all my remaining names? May thanks

**Category: Double ethmoji**
Item:🤦‍♂🤦🏻‍♂.eth / Token ID: 48695001769638156625759300676054195314937107722524322592585172338275246372649
Item:🤦🏼‍♂🤦🏻‍♂.eth / Token ID: 51785628160675904502286430006368053520598988881172477108614787047987449587804
Item: 🤷🏾‍♀🤷🏾‍♀.eth / Token ID: 71294610322258312893830321015336359025985636430488054626166428694481543474785
Item: 👰‍♀🤷‍♂.eth / Token ID: 104358973143299693961190543745400766490629015823494583055503589735350119745536
Item: 🙅‍♂🙅🏼‍♂.eth / Token ID: 104739052492686291409232062591485205022027182004860088863062581570683815965758
Item: 🙋🏻‍♂🙋🏼‍♂.eth / Token ID: 54106445851105831387636246918496515575698014416272331494875723113242920628294
Item: 🤷🏾‍♂🤷🏽‍♂.eth / Token ID: 7283335946674430560654211731756698666047998597199511298649084479518920657935
Item: 🤷🏾‍♂🤷🏽‍♂.eth / Token ID: 7283335946674430560654211731756698666047998597199511298649084479518920657935
Item: 🚣🏼‍♂🚣🏼‍♂.eth / Token ID: 7353883776179611634883643095451931339004377037056420550836025903937601396604
Item: 🕵🏼‍♂🕵🏼‍♂.eth / Token ID: 18094652416856199394733521500366280738343548037564828135365607499572116292640
Item: ❤‍🔥💔.eth / Token ID: 96580014812405796045817192274527802276405390588655474791337292244147406983258
Item: 🚬😮‍💨.eth / Token ID: 31861219072165445145758266646105463451248809142897271751387845755072469273351

**4 letter dictionary**
Item: oups.eth / 92141414354735362189646584007137107418376909078579667112068163610463558819126

Many thanks

**Comment by Web3trish** [comment]
Hi there, I recently purchased the following triple emojis domain names on Opensea and listed them both on Opensea and ENS.Vision. None are currently listed in a category. Would it be possible to add these to the Triple Emojis category please? Thank you

Item: 👩🏾‍🦯👩🏾‍🦯👩🏾‍🦯.eth / Token ID: 87501512284292844078067237025767578143874963072667052452806564303468633221857
Item: 🚶🏼🚶🏼🚶🏼.eth / Token ID: 65716101152876561926330605785542717246079568850012342604634864524340692569473
Item: 🏌🏾🏌🏿🏌🏿.eth / Token ID: 46679610414759034955279052154072795697809801940785200967957295200362010096278
Item: 🚴🏻‍♀🚴🏻‍♀🚴🏻‍♀.eth / Token ID:63898309035725201222549428795143523961839580015028202906656184018618573414573

**Comment by shukaeth** [comment]
Hi, 
unfortunately these emojis look like they only are 4 characters long, but they are actually not. For Example this one has a length of 7 characters. To be a valid Double Ethmoji, they have to consist only of **4 characters.**
![image](https://user-images.githubusercontent.com/107618056/202912852-899ad453-3f49-4ac0-a209-5b35827be8c7.png)

Here is how a real Double Ethmoji would look like on ens.vision:
![image](https://user-images.githubusercontent.com/107618056/202912950-aa73855b-377b-46e4-a001-d3266dc208a0.png)

The same standard is for the Triple Ethmoji, you address here consists of 12 characters.
![image](https://user-images.githubusercontent.com/107618056/202913012-ce816c03-60ab-4665-b2ba-d35b943caa70.png)
To be a valid Triple Ethmoji, it has to consist of 3 characters.
![image](https://user-images.githubusercontent.com/107618056/202913069-3983b1b1-db55-42c5-87aa-050e1476e8c6.png)
Thats a technical term that defines those categories.

All the best,

shuka.eth

**Comment by shukaeth** [comment]
If you have any more questions regarding emoji names, feel free to contact the official Ethmoji Club for further information:
https://discord.gg/W2KPYSQT
