### ISSUE TITLE
Adding name to English-Words, Adjective category

### ISSUE THREAD

**Issue by gitadrink** [Zimtente/ens-collections#772]
Request: Please add to English adjectives, because it is an English adjective as defined by most popular dictionaries.
Name: sporadic.eth
Collection: English Adjectives
Token ID: 74296821080124389906591635345168789854673723905473492765022904747567701720534

Thank you

**Comment by shukaeth** [comment]
hi -> approved
![image](https://user-images.githubusercontent.com/107618056/191830366-f8798511-715e-4715-ba2d-69a4ec4911d3.png)


will be added!
