### ISSUE TITLE
Please add "Bradwell.eth" to Surnames

### ISSUE THREAD

**Issue by zo16950** [Zimtente/ens-collections#774]
Explanation why the item should be added/removed from a collection: Bradwell.eth should be added to surnames because it is a common last name and is also the name of multiple bridges in the United States and streets.

Collection Name: Surnames

Name of the item: Bradwell.eth

Token ID: 6038098803488191929902228025620366381011440793139850983869705723208699118736

![image](https://user-images.githubusercontent.com/103213586/191151459-5efb970e-b49d-411c-b9ce-c33359496722.png)

![image](https://user-images.githubusercontent.com/103213586/191151504-3a258b10-1742-4655-ba34-9b2f4a545f08.png)

**Comment by shukaeth** [comment]
thx will be added!
