### ISSUE TITLE
names to be added

### ISSUE THREAD

**Issue by 3pnord** [Zimtente/ens-collections#778]
sorry I'm new to github and have zero knowledge on coding stuff

male first names:
carlitos.eth
amin.eth
amirali.eth

female first names:
darya.eth
franciny.eth

capital city:
asgabat.eth

**Comment by shukaeth** [comment]
thx names will be added - asgabat is not correct english spelling -> see screenshot below - ashgabat would be correct english dict spelling: 
![image](https://user-images.githubusercontent.com/107618056/191829241-6e2f2002-1162-487a-a5cb-00626b1f7416.png)
