### ISSUE TITLE
CN 10k Club

### ISSUE THREAD

**Issue by golddub** [Zimtente/ens-collections#78]
"name": "CN 10k Club",
  "slug": "cn-10k-club"
  "description": "Simplified Chinese, 0000-9999.",
  "twitter": "https://twitter.com/10kclubcn?s=21&t=1ReIz2vPnZp5MCq63AZTsA",
  "website": "-",
  "chat": "https://discord.gg/EGQy6zmR",
  "logo": https://i.imgur.com/J9Jb0PL.png
  "csv": https://pastebin.com/9fQWRZ7X

**Comment by tunnckoCore** [comment]
It's already listed on the site for some reason.
