### ISSUE TITLE
Please add my pre-punk to pre-punk collection

### ISSUE THREAD

**Issue by fractionedeth** [Zimtente/ens-collections#781]
For some reason one of my pre-punk domains isn’t showing up in the pre-punk section.

I’ve attached a screenshot from the ENS app to show the original registration date of 5/23/17. 

The domain is vitalize.eth

Thanks!

<img width="1164" alt="8A91B14B-8F54-491B-B981-51696E7D0E01" src="https://user-images.githubusercontent.com/111700547/191364682-f1a1fba0-8335-4078-9f65-6c4047a562b5.png">

**Comment by Zimtente** [comment]
Hey this is not a pre punk. If you check it on etherscan you will see that the auction was not "FINALIZED" (which is the way on how to determine if its a pre punk or not) was never done. the auction was started in fact in may 2017 but the first real registration was: https://etherscan.io/tx/0x84774712ff73b1fd3cc4d6b3d782985f430ea625d8e27ae95079e411f4a6433e which is 2022.

**Comment by fractionedeth** [comment]
> 

Thanks Zimtente you are correct! Glad to learn something new every day.
