### ISSUE TITLE
add "port-louis.eth" to capital cities.

### ISSUE THREAD

**Issue by sansansan712** [Zimtente/ens-collections#782]
Explanation - Port Louis is the capital city of Mauritius
Collection Name - Capital Cities
Name of the item - port-louis.eth
Token ID: 21342846108543010102439390786093089474326196083058028280686322234231067452307

**Comment by shukaeth** [comment]
thx, approved - will be added:

![image](https://user-images.githubusercontent.com/107618056/191829633-3ee1a85b-735d-4ac2-a5a5-b086d0006bc3.png)

**Comment by sansansan712** [comment]
Thank you much,
