### ISSUE TITLE
3 letter first name requests

### ISSUE THREAD

**Issue by Soloxbt** [Zimtente/ens-collections#788]
Liy.eth
![image](https://user-images.githubusercontent.com/108774719/191646116-4dabb444-9e60-4299-92bf-8c4583aefa98.png)
zyg.eth
![image](https://user-images.githubusercontent.com/108774719/191646194-658477fc-be90-4120-b06c-87679908e757.png)
suy.eth
![image](https://user-images.githubusercontent.com/108774719/191646251-1772ea64-a368-4c60-b29f-b7a9a8b88951.png)

**Comment by shukaeth** [comment]
thx will be added
