### ISSUE TITLE
Please add Capital Cities and Countries to the existing categories

### ISSUE THREAD

**Issue by sansansan712** [Zimtente/ens-collections#789]
Hello, 
Please add the following:

1.
Explanation: https://www.merriam-webster.com/dictionary/st.%20john's
Collection Name: Capital Cities
Name of the item: st-johns.eth
Token ID: 29557041544933257963365780994421178511055944005623649191442776160966337220475

2.
Explanation: https://www.merriam-webster.com/dictionary/st.%20john's
Collection Name: Capital Cities
Name of the item: saint-johns.eth
Token ID: 40031977055492938468770862264481976802593611508420623844164247595434686469384

3.
Explanation: https://symbolhunt.com/cocos-keeling-islands/capital-city/
Collection Name: Capital Cities
Name of the item: west-island.eth
Token ID: 90342881723005454192365118000594219389379222552911595151209735258425461211654

4.
Explanation: https://en.wikipedia.org/wiki/The_Valley,_Anguilla
Collection Name: Capital Cities
Name of the item: the-valley.eth
Token ID: 35224909216861926620030592475671026880615151490146131152014428716053477792131

5.
Explanation: https://en.wikipedia.org/wiki/Sejong_City
Collection Name: Capital Cities
Name of the item: sejong-city.eth
Token ID: 75775604437675518716229040196857536154464451885898479210257827783959494377941

6.
Explanation: https://www.merriam-webster.com/dictionary/Port%20Moresby
Collection Name: Capital Cities
Name of the item: port-moresby.eth
Token ID: 87376200507989992692655783039119634823026565225125791830647774653804778512394

7.
Explanation: https://www.merriam-webster.com/dictionary/Pago%20Pago
Collection Name: Capital Cities 
Name of the item: pago-pago.eth
Token ID: 11896106136386279708095873375005383642127776714727469671702122868437166743956

8.
Explanation: https://en.wikipedia.org/wiki/Ivory_Coast
Collection Name:  Countries
Name of the item: ivory-coast.eth
Token ID: 39235235327980878620103165996695329897761621278455688778735752965721924393634

9.
Explanation: https://www.merriam-webster.com/dictionary/Gambia
Collection Name: Countries
Name of the item: the-gambia.eth
Token ID: 103907727768675775836032795818260385464643911856864082654938785638893421348495

10.
Explanation: https://www.merriam-webster.com/dictionary/East%20Timor
Collection Name: Countries
Name of the item: east-timor.eth
Token ID: 84852103728576530249829850590769458180835702673404979301128583684076216087035

11.
Explanation: https://en.wikipedia.org/wiki/Pitcairn_Island
Collection Name: Countries
Name of the item: pitcairn-islands.eth
Token ID: 26920262979735202547476226019929455738268709526466351836986089784518862424307

**Thank you so much,**

**Comment by shukaeth** [comment]
Hey following versions will be added:

saint-johns
west-island
the-valley
sejong-city
port-moresby
pago-pago

names will be added after we release the new database
greets, shuka.eth
