### ISSUE TITLE
Add Farsi 999 Club

### ISSUE THREAD

**Issue by Remolten** [Zimtente/ens-collections#79]
"name": "Farsi 999 Club",
"slug": "farsi-999-club"
"description": "۰۰۰-۹۹۹ (Farsi)",
"twitter": "https://twitter.com/999Farsiens",
"website": "",
"chat": "https://discord.gg/vkah2ufd",
"logo": "https://imgur.com/a/5ehcZQt"
"csv": "https://pastebin.com/dHYtuSMz"

**Comment by Whippsie** [comment]
Some changes :

Metadata
{
  "name": "Farsi 999 Club",
  "slug": "farsi-999-club"
  "description": "۰۰۰ - ۹۹۹ (Farsi)",
  "twitter": "999Farsi",
  "logo": "farsi-999-logo.png",
  "csv": ["farsi-999-club.csv"]
}

Reason 1 : The twitter is missing
Reason 2 : Your image is a bit small. We won't see the name. I would like to propose this one instead
Reason 3 : You didn't upload a .csv

New logo :
![farsi-999-logo](https://user-images.githubusercontent.com/24740373/177080956-c2b6a58d-e37b-477f-b8d2-4e32855ba00b.png)

CSV : 
[farsi-999-club.csv](https://github.com/Zimtente/ens-collections/files/9036426/farsi-999-club.csv)


CSV with corresponding number : 
[farsi-999-club - withNumbers.csv](https://github.com/Zimtente/ens-collections/files/9036427/farsi-999-club.-.withNumbers.csv)

**Comment by Remolten** [comment]
> Some changes :
> 
> Metadata { "name": "Farsi 999 Club", "slug": "farsi-999-club" "description": "۰۰۰ - ۹۹۹ (Farsi)", "twitter": "999Farsi", "logo": "farsi-999-logo.png", "csv": ["farsi-999-club.csv"] }
> 
> Reason 1 : The twitter is missing Reason 2 : Your image is a bit small. We won't see the name. I would like to propose this one instead Reason 3 : You didn't upload a .csv
> 
> New logo : ![farsi-999-logo](https://user-images.githubusercontent.com/24740373/177080956-c2b6a58d-e37b-477f-b8d2-4e32855ba00b.png)
> 
> CSV : [farsi-999-club.csv](https://github.com/Zimtente/ens-collections/files/9036426/farsi-999-club.csv)
> 
> CSV with corresponding number : [farsi-999-club - withNumbers.csv](https://github.com/Zimtente/ens-collections/files/9036427/farsi-999-club.-.withNumbers.csv)

Looks great!

**Comment by tunnckoCore** [comment]
You're completely missing the point of Arabic and Chinese clubs, stop making such clubs for every single thing.

Plus, the "new" logo seems a lot like the Arabic's 999 club.

**Comment by Whippsie** [comment]
@tunnckoCore 

Please consider the following post posted on ens.vision discord
If the logo is too similar, we will change it to make it very clear it's not arabic club

goatgang.eth — Today at 9:20 AM
While being against adding too much clubs/category I think its necessary to create a separate category for Persian digits considering they are identical in real world but different Unicode causing confusions for people who wanna invest into just Arabic digits or vica versa, eg: ۰۰۰.eth ٠٠٠.eth are different Unicode/give different token IDs while being identical.

*Persian keyboard/Arabic keyboard using different Unicode can be the main cause of this confusion. Here are some more information below:

Arabic Numbers:
١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩ ٠
Persian numbers:
۰ ۹ ۸ ۷ ۶ ۵ ۴ ۳ ۲ ۱

Letters:
Identical except Persian has 4 extra letters: گ چ پ ژ
Therefore names like Samsung or Google can be spelled how they are pronounced in Persian unlike Arabic.
Google=>
Arabic: جوجل
Persian: گوگل

Worth mentioning:
- Persian language is historically older and more complete than Arabic. 
- Both native speakers of each community can 'read' both Arabic and Persian alphabets as they are identical. Creating a category for Persian digits will be extremely helpful to avoid confusion as it's extremely hard for new investors to distinguish.

I speak both languages, if @choji.eth needed more information on the exact unicode type and difference between the two to accelerate the listing please let me know.

**Comment by Remolten** [comment]
@tunnckoCore How is it missing the point? Copying a [message from the ENS Vision Discord](https://discord.com/channels/949974613046210610/989632947281874964/993506604102209626) by goatgang.eth:

> While being against adding too much clubs/category I think its necessary to create a separate category for Persian digits considering they are identical in real world but different Unicode causing confusions for people who wanna invest into just Arabic digits or vica versa, eg: ۰۰۰.eth ٠٠٠.eth are different Unicode/give different token IDs while being identical.
> 
> *Persian keyboard/Arabic keyboard using different Unicode can be the main cause of this confusion. Here are some more information below:
> 
> Arabic Numbers:
> ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩ ٠
> Persian numbers:
> ۰ ۹ ۸ ۷ ۶ ۵ ۴ ۳ ۲ ۱
> 
> Letters:
> Identical except Persian has 4 extra letters: گ چ پ ژ
> Therefore names like Samsung or Google can be spelled how they are pronounced in Persian unlike Arabic.
> Google=>
> Arabic: جوجل
> Persian: گوگل
> 
> Worth mentioning:
> - Persian language is historically older and more complete than Arabic. 
> - Both native speakers of each community can 'read' both Arabic and Persian alphabets as they are identical. Creating a category for Persian digits will be extremely helpful to avoid confusion as it's extremely hard for new investors to distinguish.
> 
> I speak both languages, if @choji.eth needed more information on the exact unicode type and difference between the two to accelerate the listing please let me know.

**Comment by sahsm** [comment]
Hi guys! 
Im building the Twitter @999Persiens and the community. Id like to connect with you guys asap! Thank you!

**Comment by Remolten** [comment]
I've added a Discord, Twitter, and updated logo to the OP.

**Comment by Remolten** [comment]
It's also worth noting from the discussion in the Discord, that Persian + Farsi are both names for the same thing (endonyms). Maybe we put that in the club name. More info: https://en.wikipedia.org/wiki/Persian_language

**Comment by tunnckoCore** [comment]
I have nothing against anyone and anything, and don't want to offense anyone.

I know and understand the differences. Thing is, if it's up to me I won't include it. Of course it's not only up to me, first. And second, I don't think _anything_ should be included without community vote in the first place. That's what I can do as one of the broad community, and as one with a little bit more permissions. It doesn't mean it cannot get in. 

Call me prophet or just dumb hater, but there's no value (or atleast not that much as the original 10k digits) in such clubs. The "english numbers", are also generally called arabic numeral system, so I don't get the point of having Arabic clubs in the first place too, but okay.

Evenmore having both similar things. It's like having bulgarian and macedonian language - "macedonian" is nothing more than pure a cyrillic and bulgarian, with some latin additions & merges, just because serbian influence for 30 years. Such things doesn't signify language or existence of it.

I'm not saying it's the same case with Arabic and Persian. Not at all. Just saying it won't be good, in my opinion, to have two identical things.

Some may say  "who's you to say and decide?". No one. Just a man with ton of open source work in the past 10 years and software with billions of downloads. I'm just expressing my position. And one that is part of the broad crypto and ens community. Too much clubs and choice isn't good either and is/will lead to confusion too.

**Comment by Remolten** [comment]
@tunnckoCore I'm not a part of this project, but to me one of the primary value-adds of ENS Vision/collections is to provide discovery for domains people may want. Categories serve to _eliminate_ confusion, so that people aren't duped into buying the wrong thing. In that light, I see adding categories as primarily a UX problem. It's positive to add collections, but the front-end needs a good way to organize them. I don't think that collections should be declined, provided there's sufficient community desire for it to be added. I'd be curious to hear more from you about why adding this category would cause more confusion, since to me, it provides some clarity and discovery for Farsi speakers/readers. Hopefully my thoughts are cogent, but feel free to show me where I'm wrong.

How do we let the community decide? Discord vote? Vote here?

**Comment by sahsm** [comment]
Totally agree with you @Remolten!

And just reminding everyone; we are sold out since yesterday!

**Comment by Soocus** [comment]
wen listtt

**Comment by Goatan2** [comment]
The logo and the whole thing is too similar to 999arabic, 50 clubs are popping up every day, we must draw the line somewhere no?

**Comment by tunnckoCore** [comment]
@Goatan2 exactly. I'm fighting that fight.

If it's up to me, i reject them. If someone else or some community vote bring them back then OK, but it won't be through me.

**Comment by Remolten** [comment]
@tunnckoCore The logo can be changed for further clarity; we are currently working on it in our Discord. Can you explain why you're "fighting that fight"? What is the _harm_ in adding this category?

@Zimtente @CryptoGatsu I think it would be fair to reopen this issue, so the entire community can continue discussion. It was closed back when there was still confusion about Farsi being identical to Arabic (they are different).

**Comment by sahsm** [comment]
Our new logo: 
![999FarsiEns](https://user-images.githubusercontent.com/107327500/177227795-9531486e-868c-4980-bea7-6463ab17f395.jpeg)

Our twitter @999Farsiens is growing fast. 
We are not understanding how there's no demand if the collection is sold out.

When we get listed is going to be more clear & safe for the community if we are buying an Arabic or a Farsi ens digit.


Of the major languages spoken/used around the world, three meet these four metrics best (in this order):

English
Arabic
Farsi

The next major language numbers run is going to be in Farsi numbers. This is actually very healthy for the Arabic numbers (Farsi and Arabic numbers look very alike - but have different Unicode characters). It creates a distinct and separate "family" for them.

The Farsi numbers are:
۰۱۲۳۴۵۶۷۸۹

Unicodes U+06F0 to U+06F9

Iranian society is very crypto-friendly and flexing is a part of the culture. Farsi digits will inevitably follow the pattern of Arabic digits.

**Comment by Goatan2** [comment]
No, you are trying to hussle here. When people from your own community and your own official twitter account are posting on arabic members twitter posts saying people should come to your arabic extended club it is misleading but here you call it Farsi.
The same people come to the arabic discord & twitter trying to scam sell theirs as genuine arabic numbers.

**Comment by sahsm** [comment]
Sorry! Who is misleading Sr? I posted educating if you have an extended Arabic Indic digit you're part of Farsi digit club. Am I lying? whats misleading?

I can't control everybody, but listing the collection will prevent these people from doing it as well!.

**Comment by Goatan2** [comment]
When you are posting from your official "Farsi" club on tweets from community members from the official 999ENSarabic to wheel in new buyers/members and calling yourself arabic extended then it is obvious what you are doing, it is toxic and it shows a bad example to the people in your community and they obviously follow your lead and do the same, you are not building a Farsi club with people who speak Farsi or enjoy the language.

This was my last post, no reason to entertain this anymore.

**Comment by sahsm** [comment]
Well, you are having a wrong perception of what I am doing. 

What I AM doing is trying to find all the Farsi holders.. a lot of people these last days minted Farsi digits trying to mint Arabic ones. It's simple like that, stop accusing, please. 

This listing will help every Collection, we are not fake Arabic.. We are another language that millions of people use daily!

**Comment by nastyens** [comment]
Hi all. I am Arabic speaking and can tell you that Farsi is completely different to Arabic. To help keep the community safe from scammers & also protect people from themselves (errors translating from google) the two languages need to be separated. The ens community should be inclusive and diverse. Adding Persian (Farsi) is a no brainer.

**Comment by yingxiayin** [comment]
nice work, hope to add this soon

**Comment by yingxiayin** [comment]
just finished a space in twitter

**Comment by yingxiayin** [comment]
Thanks to the efforts of the community, we kept a major tweet!

**Comment by 0xAntler** [comment]
Hope we all can get a good news soon

**Comment by Octexor** [comment]
I believe listing Arabic and Persian digits separately is the only way to avoid confusion and have a source of truth for both languages.
Any names that mix the two sets of numbers will be seen as invalid, and that's the way to go.

@Zimtente 
I'm helping this community to get listed soon.
They will choose one main twitter account, and a proper logo. Discord link is available too.

**Comment by yingxiayin** [comment]
> I believe listing Arabic and Persian digits separately is the only way to avoid confusion and have a source of truth for both languages. Any names that mix the two sets of numbers will be seen as invalid, and that's the way to go.
> 
> @Zimtente I'm helping this community to get listed soon. They will choose one main twitter account, and a proper logo. Discord link is available too.

now tw dc and logo are ready now!!!

**Comment by tunnckoCore** [comment]
> Farsi is a completely different language from Arabic.

No one is opposing that.

**Comment by CryptoGatsu** [comment]
@Octexor logo?

**Comment by Octexor** [comment]
@CryptoGatsu 
It's ready.
Check the commit please: https://github.com/Zimtente/ens-collections/commit/f499a3450dce317006b27de3f5388a54f5f01874

**Comment by CryptoGatsu** [comment]
got it just seen. should be up soon!
