### ISSUE TITLE
Please add the following, thank you in advance for your hard work! 

### ISSUE THREAD

**Issue by sansansan712** [Zimtente/ens-collections#790]
several adjectives, nouns, verbs and 2 female first names.  

1. 
Explanation: https://www.merriam-webster.com/dictionary/conspirant
Collection Name: English Adjectives
Name of the item: conspirant.eth
Token ID: 51061531871185976874804577624268528432157319258215670978965974029757987522988

2.
Explanation: https://www.merriam-webster.com/dictionary/navigable
Collection Name: English Adjectives
Name of the item: navigable.eth
Token ID: 108322761796967580309194724555085192919063641538490791126577309354856403524425

3.
Explanation: https://www.merriam-webster.com/dictionary/intellection
Collection Name: English Nouns
Name of the item: intellection.eth
Token ID: 5901751052548374971001296148715233864663921093889482325395220578066535425607

4.
Explanation: https://www.merriam-webster.com/dictionary/disciplinal
Collection Name: English Adjectives
Name of the item: disciplinal.eth
Token ID: 18352842565661782443643177417980770404350224300303107435046338009338648448940

5.
Explanation: https://www.merriam-webster.com/dictionary/deactivator
Collection Name: English Nouns
Name of the item: deactivator.eth
Token ID: 23255522167613983876185183068486079853677370807958003720364700330676937873365

6.
Explanation: https://ens.vision/name/formalist
Collection Name: noun and/or adjective
Name of the item: formalist.eth
Token ID: 42950142263353776553126624234872616413274219960936166104919939711141848974177

7.
Explanation: https://www.merriam-webster.com/dictionary/cooperant
Collection Name: English Adjectives
Name of the item: cooperant.eth
Token ID: 63800069849165388468070345490550046715627690064106196380047343848682040699413

8.
Explanation: https://www.merriam-webster.com/dictionary/cleanable
Collection Name: English Adjectives
Name of the item: cleanable.eth
Token ID: 110797466112239841185152145519006302209831664320860760797229367082696177071915

9.
Explanation: https://www.merriam-webster.com/dictionary/advocation
Collection Name: English Nouns
Name of the item: advocation
Token ID: 25492043903295516301479039231243877224985277492672748620063777099750520627630

10.
Explanation: https://www.merriam-webster.com/dictionary/affectable
Collection Name: English Adjectives
Name of the item: affectable.eth
Token ID: 38432217637653117157679204492369648941821368126958623703232631393404200157436

11.
Explanation: https://www.merriam-webster.com/dictionary/reparable
Collection Name: English Adjectives
Name of the item: reparable.eth
Token ID: 101101053581974049581048242098999630231489521513128044814800462037134749477914

12.
Explanation: https://www.merriam-webster.com/dictionary/cosmically
Collection Name: English Adjectives
Name of the item: cosmically.eth
Token ID: 392193527678843106460816461573947708957873459086158138828111580788326544221

13.
Explanation: https://www.merriam-webster.com/dictionary/uncuff
Collection Name: English Verbs
Name of the item: uncuff.eth
Token ID: 41655816334071433336577089687486656967963565506135076362437165453293523363293

14.
Explanation: https://www.merriam-webster.com/dictionary/replaying
Collection Name: English Verbs
Name of the item: replaying.eth
Token ID: 49008318716026792815967940137548190173558563846471120881299074900933710751290

15.
Explanation: https://www.merriam-webster.com/dictionary/saluting
Collection Name: English Verbs
Name of the item: saluting.eth
Token ID: 66409742165005945476102599045296685731717361339568824115808860899875552083292

16.
Explanation: https://www.merriam-webster.com/dictionary/excusing
Collection Name  English Verbs
Name of the item: excusing.eth
Token ID: 80953717519585796769422424590282688868074989312764020803251038956646226172471

17.
Explanation: https://www.merriam-webster.com/dictionary/contesting
Collection Name: English Verbs
Name of the item: contesting.eth
Token ID: 87899652235777005858189897334151292415015763336839309999323034566243586499857

18.
Explanation: https://www.merriam-webster.com/dictionary/disapproves
Collection Name: English Verbs
Name of the item: disapproves.eth
Token ID: 90995679145320137477442859659442344341843057584477216450401623640705485361963

19.
Explanation: https://www.merriam-webster.com/dictionary/fluffed  
Collection Name: English Verbs
Name of the item: fluffed.eth
Token ID: 95861837102666280427592059750564350334731372030994949520676008764258573718004

20.
Explanation: https://www.merriam-webster.com/dictionary/principial
Collection Name: English Adjectives
Name of the item: principial.eth
Token ID: 101945578636193463158127832707590171249374024250192847403911985196592284139880

21.
Explanation: https://www.merriam-webster.com/dictionary/musicale
Collection Name: English Nouns
Name of the item: musicale.eth
Token ID: 106776543412901422746263924747121628400229485604905026342929694935719157542779

22.
Explanation: https://www.merriam-webster.com/dictionary/nicknaming
Collection Name: English Verbs
Name of the item: nicknaming.eth
Token ID: 23401878229310328658295763075886047197693584375701205506967762102593424973719

23.
Explanation: https://www.merriam-webster.com/dictionary/pilotage
Collection Name: English Nouns
Name of the item: pilotage
Token ID: 23947172453073260194244746164164796934772560761776438903637806760215589500445

24.
Explanation: https://www.merriam-webster.com/dictionary/prohibitor
Collection Name: English Nouns
Name of the item: prohibitor.eth
Token ID: 46266078727609186288438822325680544646327591466124957623718329808180139483527

25.
Explanation: https://www.merriam-webster.com/dictionary/pedagogist
Collection Name: English Nouns
Name of the item: pedagogist.eth
Token ID: 52856890568463023674332083662215209258153883822940398109987557849705972591208

26.
Explanation: https://www.merriam-webster.com/dictionary/godkin
Collection Name: English Nouns
Name of the item: godkin.eth
Token ID: 66480912896624466246039748054035944742692127725567282450428217189642109812168

27.
Explanation: https://www.merriam-webster.com/dictionary/licensable
Collection Name: English Adjectives
Name of the item: licensable.eth
Token ID: 69569800875401732983641439614689018183463103355902100407511741089727895894516

28.
Explanation: https://www.merriam-webster.com/dictionary/lotting
Collection Name: English Verbs
Name of the item: lotting.eth
Token ID: 72500483610954805430922278802791336038972264898133783207737221017612685552581

29.
Explanation: https://www.merriam-webster.com/dictionary/pennyland
Collection Name: English Nouns
Name of the item: pennyland.eth
Token ID: 76044619004646429585072410528505775871348132581932145349351994712529198442797

30.
Explanation: https://www.merriam-webster.com/dictionary/prizer
Collection Name: English Nouns
Name of the item: prizer.eth
Token ID: 78680296356799906793555774678764916740029921235839873048859777946868581329990

31.
Explanation: https://www.merriam-webster.com/dictionary/honorarily
Collection Name: English Adjectives
Name of the item: honorarily.eth
Token ID: 107080028983938817450757720331765379672469359851544332197831045049184279231273

32.
Explanation: https://www.merriam-webster.com/dictionary/legislated
Collection Name: English Verbs
Name of the item: legislated.eth
Token ID: 49832169710180356313631711124294112387582582926472577351964782892642670149341

33.
Explanation: https://www.merriam-webster.com/dictionary/intellection
Collection Name: English Nouns
Name of the item: intellection.eth
Token ID: 5901751052548374971001296148715233864663921093889482325395220578066535425607

34.
Explanation: https://www.merriam-webster.com/dictionary/lyrist
Collection Name: English Nouns
Name of the item: lyrist.eth
Token ID: 76998181822126727999676692469858898788102465659313522547227243015501017437276

35.
Explanation: https://www.merriam-webster.com/dictionary/knowledged
Collection Name: English Adjectives
Name of the item: knowledged.eth
Token ID: 59837460220997502535669914595671822782249405786478136842501663313983990360963

36.
Explanation: https://www.merriam-webster.com/dictionary/energetical
Collection Name: English Adjectives
Name of the item: energetical.eth
Token ID: 19215937635339012360864497160044005505380030272979533436776492825703675899942

37.
Explanation: https://www.merriam-webster.com/dictionary/doctoress
Collection Name: English Nouns
Name of the item: doctoress.eth
Token ID: 2261185728360981087262594482497812531304578651974688078439177888503416705956

38.
Explanation: https://www.merriam-webster.com/dictionary/donable
Collection Name: English Adjectives
Name of the item: donable.eth
Token ID: 31670703865435150625263184575471907623029728692872349982292395436892288117645

39.
Explanation: https://www.merriam-webster.com/dictionary/finlander
Collection Name: English Nouns
Name of the item: finlander.eth
Token ID: 42939738462608295893431360139001849902009710989710102665855313258600113738889

40.
Explanation: https://www.merriam-webster.com/dictionary/divinest
Collection Name: English Adjectives
Name of the item: divinest.eth
Token ID: 77320892694514382635542282443268914814603680479764446618025998860904963858574

41.
Explanation: https://www.merriam-webster.com/dictionary/durity
Collection Name: English Nouns
Name of the item: durity.eth 
Token ID: 79805987028429042334121110049095362373705257581937321595818150940317357575438

42.
Explanation: https://www.merriam-webster.com/dictionary/Ethiopic
Collection Name: English Adjectives
Name of the item: ethiopic.eth
Token ID: 85069221608268118184061780579446953419599369904260322319993917635385261091230

43.
Explanation: https://www.merriam-webster.com/dictionary/democratically
Collection Name: English Adjectives
Name of the item: democratically.eth
Token ID: 87974807604743780507056622737460936556507003383767641763591912466517829820528

44.
Explanation: https://www.merriam-webster.com/dictionary/freeborn
Collection Name: English Adjectives
Name of the item: free-born.eth
Token ID: 58069953919098098414446171279684291892651854466688672879672775322790882673303

45.
Explanation: https://www.merriam-webster.com/medical/alcoholist
Collection Name: English Nouns
Name of the item: alcoholist.eth
Token ID: 101753414343589847817951128723803960433663577117033773089671035666691879677066

46.
Explanation: https://www.merriam-webster.com/dictionary/Americanization
Collection Name: English Nouns
Name of the item: americanization.eth
Token ID: 103242029000473633985391394932536204381547264652912200549622749226958626606382

47.
Explanation: https://www.merriam-webster.com/dictionary/approvable
Collection Name: English Adjectives
Name of the item: approvable.eth
Token ID: 15029871473830679234304161108895146620274939581738365014499936009970290901140

48.
Explanation: https://www.merriam-webster.com/dictionary/blackjacking
Collection Name English Verbs
Name of the item: blackjacking.eth
Token ID: 28174626510267523442577088596466674392770638121073212166024540663213274940014

49.
Explanation: https://www.merriam-webster.com/dictionary/carabinero
Collection Name: English Nouns
Name of the item: carabinero.eth
Token ID: 32201771646439589421245408077079285897428141844267856966823666164671082174034

50.
Explanation: https://www.merriam-webster.com/dictionary/anti-crime
Collection Name: English Adjectives
Name of the item: anticrime.eth
Token ID: 44806109899606682553668200690906014589221054041272620950359260980158994406463

61.
Explanation: https://www.merriam-webster.com/dictionary/actory
Collection Name: English Adjectives
Name of the item: actory.eth 
Token ID: 54661844734151915373862121129154750027324722405212637307374386055597725916222

62.
Explanation: https://www.merriam-webster.com/dictionary/afternight
Collection Name: English Nouns
Name of the item: afternight.eth
Token ID: 69309623900960003890782841186945928092216569249381634336078631961509806997249

63.
Explanation: https://www.merriam-webster.com/dictionary/All-father
Collection Name English Nouns
Name of the item: all-father.eth
Token ID: 83254240840130106028068318975407775164815508329909066114219729889770157644453

64.
Explanation: https://www.babycenter.com/baby-names/details/jeryn-100645
Collection Name: Female First Names
Name of the item: jeryn.eth
Token ID: 104892027623200600054896187088677498076971757655991316722958592595142280677724

65.
Explanation: https://www.merriam-webster.com/dictionary/guardsmen
Collection Name: English Nouns
Name of the item: guardsmen.eth
Token ID: 101836204434245097986203197471239478138817020534868376590951244422562080535167

66.
Explanation: https://www.merriam-webster.com/dictionary/neglective
Collection Name English Adjectives
Name of the item: neglective.eth
Token ID: 100458638852415164887138645905021564068951134280394174971197329919023992744986

67.
Explanation: https://www.babynamespedia.com/meaning/Aleska
Collection Name Female First Names
Name of the item: aleska.eth
Token ID: 63722350937722976076077926177140788767059651291972788385232138074089840923924

68.
Explanation: https://www.merriam-webster.com/dictionary/nival
Collection Name English Adjectives
Name of the item: nival.eth
Token ID: 63699046253542419504275844307000562432045282663462400905004439948186121578095

69.
Explanation: https://www.merriam-webster.com/dictionary/obeying
Collection Name English Verbs
Name of the item: obeying.eth
Token ID: 58359493864364280018028575694333450696233877368987451576964882327325854942777

70.
Explanation: https://www.merriam-webster.com/dictionary/recoverable
Collection Name English Adjectives
Name of the item: recoverable.eth
Token ID: 57546762208618475061741766064667544332772426876286633310725750742318884993457

**Thank you for you hard work on this!!**

**Comment by shukaeth** [comment]
Thanks for providing all the sources :) will be added !
