### ISSUE TITLE
Issue with set of Single Emoji's

### ISSUE THREAD

**Issue by vinod-veera** [Zimtente/ens-collections#793]
About 5 months back I registered a set of single emoji ENS domains.
In this set 3 of them show up as malformed while others are fine, though I am unable to see a difference in them.

Can you please check the following 3 and tell me if they will be fine with the normalization or if there is a problem with them.
Thanks

[👨🏿‍❤‍👩🏻.eth](https://app.ens.domains/name/%F0%9F%91%A8%F0%9F%8F%BF%E2%80%8D%E2%9D%A4%E2%80%8D%F0%9F%91%A9%F0%9F%8F%BB.eth/details)
[👨🏿‍👨🏿‍👧🏿‍👧🏿.eth](https://app.ens.domains/name/%F0%9F%91%A8%F0%9F%8F%BF%E2%80%8D%F0%9F%91%A8%F0%9F%8F%BF%E2%80%8D%F0%9F%91%A7%F0%9F%8F%BF%E2%80%8D%F0%9F%91%A7%F0%9F%8F%BF.eth/details)
[👩🏿‍❤‍👨.eth](https://app.ens.domains/name/%F0%9F%91%A9%F0%9F%8F%BF%E2%80%8D%E2%9D%A4%E2%80%8D%F0%9F%91%A8.eth/details)

**Comment by toniodlab** [comment]
Maybe removed with https://github.com/Zimtente/ens-collections/pull/492 ?
Thoses are unofficials and not displaying fine on Linux.

**Comment by vinod-veera** [comment]
Not sure. Lets see if there is any change with normalization. If not no problem. Thanks...
