### ISSUE TITLE
Add names to female fisrtnames

### ISSUE THREAD

**Issue by Petardopy** [Zimtente/ens-collections#794]
Hi guys thank you for your hard work

I would like you to add these names to the following collections please

FEMALE FIRSTNAMES:
Aylén.eth
Purifación.eth

Thanks in advance, keep the good work on

**Comment by Petardopy** [comment]
I made a mistake 

Its purificación not purifacion

**Comment by Petardopy** [comment]
Token ids
Aylén https://app.ens.domains/name/ayl%C3%A9n.eth/details

Purificación https://app.ens.domains/name/purificaci%C3%B3n.eth/details

**Comment by shukaeth** [comment]
thx approved, found them on forebears.io =) will be added
