### ISSUE TITLE
Add names to surnames

### ISSUE THREAD

**Issue by Petardopy** [Zimtente/ens-collections#797]
Yo my bois can you please add these names to the surnames collection please

almirón.eth https://app.ens.domains/name/almir%C3%B3n.eth/details

colmán.eth https://app.ens.domains/name/colm%C3%A1n.eth/details

Thanks!

**Comment by shukaeth** [comment]
Hi I can add almirón as I found it on forebears for official surname: https://forebears.io/surnames/almir%C3%B3n
also colmán: https://forebears.io/surnames/colm%C3%A1n

will be added!
