### ISSUE TITLE
Category Request "365 Club"

### ISSUE THREAD

**Issue by armankremer** [Zimtente/ens-collections#8]
name: "365 Club"
slug: "365-Club"
description: A web3 social club for ENS holders January1st-December31st. No roadmap. There is only 365 days with suffix on the ethereum blockchain. #weowntheyear
twitter: @365clubofficial
website: none
chat: https://discord.gg/8BTT7nre 
logo: 
<img width="153" alt="365-Club" src="https://user-images.githubusercontent.com/106930230/172068241-dc6b30ec-a4d1-4935-9bf4-5e5e511d61a4.png">
csv: 
[365-Club.csv](https://github.com/Zimtente/ens-collections/files/8840661/365-Club.csv)

**Comment by CryptoGatsu** [comment]
a pull request has been created with this club. thank you for providing the csv.
