### ISSUE TITLE
Please add these names in male and female names and one surname

### ISSUE THREAD

**Issue by SKYDARTIST** [Zimtente/ens-collections#800]
Male names - 

aabish.eth
Abtal.eth
Agatino.eth
Swapnesh.eth

Female - aghnia.eth

Surname - baldinger.eth

Thankyou 💚

**Comment by shukaeth** [comment]
hi thx - approved as I found all on forebears :) will be added

**Comment by SKYDARTIST** [comment]
Thank you so much ser
