### ISSUE TITLE
ADDITIONAL SURNAMES

### ISSUE THREAD

**Issue by prestonhao** [Zimtente/ens-collections#802]
Aloha!

To whom it may concern I'm contacting in regards of adding some domains into the Surnames categories. All names are provided with an example.

urlacher - Brian Urlacher (HOF Football Player)
lasorda - Tommy Lasorda (HOF Baseball Manager)
newhouser - Hal Newhouser (HOF Baseball Player)
selee - Frank Selee (HOF Baseball Manager)
rusie - Amos Rusie (HOF Baseball Player)
unseld - Wes Unseld (HOF Basketball Player)
wanzer - Bobby Wanzer (HOF Basketball Player)
dumars - Joe Dumars (HOF Basketball Player)
hepbron - George Hepbron (HOF Basketball Referee)
trester - Arthur Trester (HOF Basketball Contributer)
catchings - Tamika Catchings (HOF Basketball Player)
hatchell - Sylvia Hatchell (HOF Basketball Coach)
caponi - Donna Caponi (HOF Golfer)
carner - JoAnne Carner (HOF Golfer)
wadkins - Lanny Wadkins (HOF Golfer)

Mahalo and thank you for your time and hard work!

**Comment by shukaeth** [comment]
thx for providing the examples =) will be added
