### ISSUE TITLE
firstname and surname requests

### ISSUE THREAD

**Issue by nuevas2012** [Zimtente/ens-collections#803]
Female first name
lebby.eth < !╌firstname and surname╌>
Token ID: 9390175356991596358240663568833402649373147078107245421734467866589803066463
janese.eth < !╌First name╌>
Token ID: 58896949343380848063346396037274383615011344402520207886224382615568084587473

![image](https://user-images.githubusercontent.com/79742932/192157318-830d22e2-93d1-4e62-9b8b-ce25c9f145a2.png)

![image](https://user-images.githubusercontent.com/79742932/192157179-620c4d06-1f4f-4834-8727-5c58dba3553d.png)

Male first name:
radric.eth
Token ID: 7591970228296149808986053997336023403647368066614492496963578500644220377854

Surname:
locsin.eth
Token ID: 5561507952737043305583778464549582366778876242006831711286370739141034480947

![image](https://user-images.githubusercontent.com/79742932/192157336-2405a9f3-a099-43ef-9286-5d43c2f8a650.png)

< !╌ These first names and surname have many results on any search engine and are used in any country. 
One of the example is Radric. Radric is the real first name of Gucci Mane.╌>
![Screenshot_6](https://user-images.githubusercontent.com/79742932/192156731-4708a53b-cbf1-4be9-83a1-366245595e3e.png)

**Comment by shukaeth** [comment]
Hi thx will be added :)

**Comment by shukaeth** [comment]
hi thats because we were not able to make updates - your names are on the list to be added! 


thx for your patience
