### ISSUE TITLE
English and Spanish Nouns

### ISSUE THREAD

**Issue by 0xza0707** [Zimtente/ens-collections#805]
Hi guys thank you for your work. I would like you to add these word to the following collection please: 

English Nouns
petithotel.eth

Also we need a Spanish Nouns Category. I would like to add there:

Pileta.eth
Mudanza.eth
Cochecito.eth
Fraternidad.eth
Absenta.eth
Pincel.eth

Thanks a lot

**Comment by shukaeth** [comment]
Hi, sadly I could't find petithotel on https://www.merriam-webster.com/.

also we have no spanish nouns category atm! sorry :/
