### ISSUE TITLE
My emoji ens  needs to be in  "Double Ethmoji" category .! please review and fix it!

### ISSUE THREAD

**Issue by web3folk** [Zimtente/ens-collections#808]
Hello EnsVision team, I recently registered a Double Ethmoji ens but in EnsVision, it is not showing in Double Ethmoji category.!
I beleive it needs to be in "Double Ethmoji" category as this emoji has a length of 4 which makes it a double emojis.
Here is the Token ID of the item : 69216462386432107027256187162500906081865641433858665291122930223284218630488
I am also attaching the secreenshot of it. 
Thank You .!
![IMG_20220926_123903 (3)](https://user-images.githubusercontent.com/114356494/192235676-e7a35aca-39fb-44b1-954e-c88cc954fb9e.jpg)

**Comment by web3folk** [comment]
Or may be it needs to be in singleEthmoji category. ! As i have seen many emojis having a length of 4 are in singleEthmoji category.! I'm sure it can be fixed after you review it.!
Token id : 69216462386432107027256187162500906081865641433858665291122930223284218630488

**Comment by shukaeth** [comment]
Hi, I am sorry but it does not belong to double ethmoji category. It has to be the same emoji 2 times, then it belongs to double ethmoji category. See screenshot below:

**Comment by shukaeth** [comment]
![image](https://user-images.githubusercontent.com/107618056/193241612-1c087675-e2f8-47cd-b77e-4a29b932c8b5.png)
