### ISSUE TITLE
request to add 3 Letter Dictionary, Male First name and 4 letter dictionary

### ISSUE THREAD

**Issue by rylanvault** [Zimtente/ens-collections#809]
Hello,

I am writing in to request your consideration to add the following to 

3 letter dictionary 

lvd.eth - https://acronyms.thefreedictionary.com/LVD 
Token ID: 24953847475435462333508684971779289138595100410535609222805942145441457476553
lve.eth - https://www.urbandictionary.com/define.php?term=LVE
Token ID : 67119686700586453393091594139428548429705800987737062336512351721578676442827

Male First Names and 4 Letter Dictionary 

zyga.eth - https://www.explorebabynames.com/meaning-of-zyga
Token ID : 59136029364999896423256404503365140441079204760522888480350188579259052309811

4 letter Dictionary 

domy.eth - https://www.thefreedictionary.com/domy
Token ID : 35896922701914035235851580160065117828070863725638152124104017589103423212294
 
thank you!

**Comment by shukaeth** [comment]
Hi, thank you - according to merriem webster words will be added to:

zyga - male first names
domy - male first names, adjectives, 4-letter-dict


shuka =)
