### ISSUE TITLE
Please add the following verbs, adjectives, nouns. 

### ISSUE THREAD

**Issue by sansansan712** [Zimtente/ens-collections#810]
1.
Explanation: https://www.merriam-webster.com/dictionary/skyscrape
Collection Name: English Verb
Name of the item: skyscrape.eth
Token ID: 86451169512026182159423179445135023973438391279448357178180434140820302284703

2.
Explanation: https://www.merriam-webster.com/dictionary/adrenalized 
Collection Name: English Adjectives
Name of the item: adrenalized.eth
Token ID: 95331494042361351309198296923294239899968879877694512876479649473097486883880

3.
Explanation: https://www.merriam-webster.com/dictionary/unfilled
Collection Name: English Adjectives
Name of the item: unfilled.eth
Token ID: 113380938832192223283650314163627793388225868207876664751771698958099350276587

4.
Explanation: https://www.merriam-webster.com/dictionary/mutative
Collection Name: English Adjectives
Name of the item: mutative.eth
Token ID: 63464339285264676485114813315320380121730067031521476325633829672996558756273

5.
Explanation: https://www.merriam-webster.com/dictionary/dramshop
Collection Name: English Noun
Name of the item: dramshop.eth
Token ID: 61790682101657789556757654723606854521137382864618069371323189423024023976587

6.
Explanation: https://www.merriam-webster.com/dictionary/tuneless
Collection Name: English Adjectives
Name of the item: tuneless.eth
Token ID: 55580338767762192013439639088621179952085009244607580334066585258259242527910
7.
Explanation: https://www.merriam-webster.com/dictionary/alterable
Collection Name: English Adjectives
Name of the item: alterable.eth
Token ID: 83371488284520413260715101004975462169546736346469137307786987232735111631215

8.
Explanation: https://www.merriam-webster.com/dictionary/hyperaware
Collection Name: English Adjectives
Name of the item: hyperaware.eth
Token ID: 18742865564060208430201007322005671635103261262013837285600623557472563945308

9.
Explanation:  https://www.merriam-webster.com/dictionary/autobiographic
Collection Name: English Adjectives
Name of the item: autobiographic.eth
Token ID: 13978815175999079877156303219507950125289338368204057167597203008802954423226

10.
Explanation: https://www.merriam-webster.com/dictionary/referential
Collection Name: English Adjectives
Name of the item: referential.eth
Token ID: 113221183345618239785642911673589668850920644241622934207868523856611069359618

Thank you,

**Comment by shukaeth** [comment]
Thanks for sending the merriam webster links :) Will be added soon!
