### ISSUE TITLE
Issue #629 was resolved but not actioned

### ISSUE THREAD

**Issue by PM2022** [Zimtente/ens-collections#812]
Issue #629  where I wanted three 4 letter dictionary names  added to ENS Vision group 4letter Dictionary  group was approved and  resolved so ticket closed, but the names have never been added to the ENS Vision group, CAN THEY PLEASE BE ADDED THANKS

SWLK
PZAZ
WTFK

eg SWLK is the plural for  SWALK  ie Sealed With Loving Kisses

**Comment by shukaeth** [comment]
Hi pls check again, they all have been already added! See Screenshots below:

![image](https://user-images.githubusercontent.com/107618056/193211607-48770171-239b-491d-8023-384d20c5a482.png)
![image](https://user-images.githubusercontent.com/107618056/193211776-00720d8f-af12-4fc5-8a72-8f98969f37d7.png)
![image](https://user-images.githubusercontent.com/107618056/193211871-bec6c430-d4bd-47c6-9eee-c02dc23fbd0a.png)

**Comment by PM2022** [comment]
ok thx! My bad, i didn't realise that I had to separately list on Ens
vision, it didn't just come on automatically, all good now, thanks very
much!
Pete
