### ISSUE TITLE
English Nouns / Adjectives / Verbs : words request to be added to categories

### ISSUE THREAD

**Issue by ENSfuturist** [Zimtente/ens-collections#816]
bleary (adjective)
Token ID: 26214867873161238806795954607285607396893564811515018037592855850908863344829

unacknowledged (adjective)
Token ID: 58258847992292341548320061120873771853480300367780879870625851290576146269570

cybertronic (adjective)
Token ID: 52790921072944701588833772842125279475127549350569846769274685235242000586028

viperous (adjective)
Token ID: 10137855897938868274834634360513923469762345904828002897778864646686169569407

-------

lubricating (verb)
Token ID: 32725859769101727760230253295954741832302179073357422680663046622563332816099

splintered (verb)
Token ID: 58918885823512024273462372872218384748555866179194754458772441417607941567131

wooing (verb)
Token ID: 28646294064770434101974743990824431542923983102319789563213985917484276933195

hostelling (verb)
Token ID: 86285307181630354203869510070864545456869121419132010480823208428159273232393

-----

musicologist (noun)
Token ID: 10053654405036792116637119425225319780383807658047041920297598231324846364451

lubricator (noun)
Token ID: 69408867979519909999413456269847682596461884084077144350831558227022130266833

motormouth (noun)
Token ID: 83980051393557948535269908724256565774357201139806687295986731356318065783861

regality (noun)
Token ID: 108346783860560946466345604631447746530968513447206479333823040689211369247538

motorman (noun)
Token ID: 96557431520112068972296676733907987694580793638952753022816741719498132660252

gamesman (noun)
Token ID: 59387853711330736435364313069673411949513793038319701707159465755866740150193

trons (noun)
Token ID: 65892884616712788134873025520337069832218870545628059374048330174338126574637

beauts (noun)
Token ID: 7008540407260279428128086204597362757807171189642209010475178576247402778732

**Comment by shukaeth** [comment]
Hi thx will be added - only ones I couldnt approve with merriam webster dict are those two:

cybertronic
trons

others will be added. 

shuka =)
