### ISSUE TITLE
Harry Potter Club Additions

### ISSUE THREAD

**Issue by forzaphil** [Zimtente/ens-collections#818]
Can you please add the following names to the Harry Potter ENS Club

"angelinajohnson": "59842584909772425794748437917757864649527510034572730335403778224916832709110",
"arianadumbledore": "83524544768028361949215288391071396976552484503875457231428785578251286903456",
"nicolasflamel": "91953526830178941592468836633299245789321642512780647244553968959267586512127",
"sircadogan": "3977206065243206305289253616043527051952638906251177556649115729625851673948",
"susanbones": "103166561224525553632298208738733507104133936666417575435288071016234273616746",
"thefatfriar": "61508494498370413200402397684692503754075430949895393103848804506261602522095",
"waldenmacnair": "3006602570487504272733588484099015281859174950773798880471462965497878143152"

**Comment by shukaeth** [comment]
Hi, thank you - I googled them all and I see no reason why they shouldn't be added as they are all harry potter characters :)  added it to our addition list!

Greetings,

shuka.eth

**Comment by forzaphil** [comment]
Thanks for making these changes. Can I ask what are the criteria you apply for deciding whether to make changes or not?

For both of the fandom clubs I submitted, Harry Potter and Tolkien, there are quite specific character entry requirements that are described in the pinned tweets for each account. If anyone is able to suggest a change without consideration by the club members then the collections could turn into a bit of a mess. 

Thanks

Phil
