### ISSUE TITLE
Please add this to capital city list

### ISSUE THREAD

**Issue by NicholasBelardo919** [Zimtente/ens-collections#821]
Explanation why the item should be added/removed from a collection- Volubilis was known by many archaeologists the capital of the Kingdom of Mauretania. 

Collection Name- Capital cities

Name of the item- Volubilis

(Optional) Token ID of the item- 47573608083216552989421638295643459085309674176166601866787347456938719101497

![bbbbbbbbbbbbbbb](https://user-images.githubusercontent.com/113144918/193106263-f2a10648-a5e9-446e-8216-2655a4d480eb.png)

![mbmbmnmbmnnm](https://user-images.githubusercontent.com/113144918/193106282-219b158a-652d-49a2-b90b-333e5d9be01d.png)

Thank you for all your help and I hope you have a great day!

**Comment by shukaeth** [comment]
sorry but we only add "active" capital cities, like current cities not historical capital cities :)

**Comment by NicholasBelardo919** [comment]
> sorry but we only add "active" capital cities, like current cities not historical capital cities :)

Gotcha, thank you didn't know
