### ISSUE TITLE
Please add the following English verbs, nouns and adjectives

### ISSUE THREAD

**Issue by dmarine1074** [Zimtente/ens-collections#822]
Good afternoon. Please add the following verbs, nouns and adjectives, confirmed from the Merriam-Webster English Dictionary.

Thanks!!

1.
Explanation: https://www.merriam-webster.com/dictionary/skewered
Collection Name: English Verb
Name of the item: skewered.eth
Token ID: 92068068287973719075938522367551895861746155028682504151304056494644789076574

2.
Explanation: https://www.merriam-webster.com/dictionary/scooted
Collection Name: English Verb
Name of the item: scooted.eth
Token ID: 87745594095165945871466192881996100341203349226582813665731418440443317383357

3.
Explanation: https://www.merriam-webster.com/dictionary/decadently
Collection Name: English Adjective
Name of the item: decadently.eth
Token ID: 68416507027340117850546166018708885978612801658492982808404850727959861447009

4.
Explanation: https://www.merriam-webster.com/dictionary/protectant
Collection Name: English Noun
Name of the item: protectant.eth
Token ID: 20100990265925129561586533414895830765913659876893183170549068217585655715615

5.
Explanation: https://www.merriam-webster.com/dictionary/beautifying
Collection Name: English Adjective
Name of the item: beautifying.eth
Token ID: 40490243402339809716350292081857162137697924544156758690521987009802901788343

6.
Explanation: https://www.merriam-webster.com/dictionary/subfreezing
Collection Name: English Adjective
Name of the item: subfreezing.eth
Token ID: 114381294256815430204265440342754668837894864283385213577067958173945974805093

7.
Explanation: https://www.merriam-webster.com/dictionary/freeholds
Collection Name: English Noun
Name of the item: freeholds.eth
Token ID: 107489095847198637321846800222098198959677413547744113352476778647037356824217

8.
Explanation: https://www.merriam-webster.com/dictionary/freehearted
Collection Name: English Adjective
Name of the item: freehearted.eth
Token ID: 60467060508350651885889810040646953688428125599675730866786533545767060861956

9.
Explanation: https://www.merriam-webster.com/dictionary/nonfreezing
Collection Name: English Adjective
Name of the item: nonfreezing.eth
Token ID: 19990960770366048798522673328919947771038747672244880974369151640360872229944

**Comment by shukaeth** [comment]
thx will be added =) also thanks, for providing merriam webster source :)
