### ISSUE TITLE
Please add the following English verbs, nouns and adjectives to existing categories

### ISSUE THREAD

**Issue by dmarine1074** [Zimtente/ens-collections#823]
Good evening. Apologies for not including these with my previous submission. I will submit once a month going forward to cut down on the number of open tickets you have to manage. 

1. 
Explanation: https://www.merriam-webster.com/legal/aggravator
Collection Name: English Noun
Name of the item: aggravator.eth
Token ID: 22995447515687611763928495502519951373907508637991717491660196288700853975061

2.
Explanation: https://www.merriam-webster.com/dictionary/swilling
Collection Name: English Verb
Name of the item: swilling.eth
Token ID: 49704916448486372297858047683614412701862422871860810545835712049436413384639

3.
Explanation: https://www.merriam-webster.com/dictionary/unfulfilling
Collection Name: English Adjective
Name of the item: unfulfilling.eth
Token ID: 75404311996818062286554935249927296422958004766641228593565491270989414824882

4.
Explanation: https://www.merriam-webster.com/dictionary/fortifying
Collection Name: English Verb
Name of the item: fortifying.eth
Token ID: 

5.
Explanation: https://www.merriam-webster.com/dictionary/intensifying
Collection Name: English Verb
Name of the item: intensifying.eth
Token ID: 13312622699138311414065845648298360838932672136073798693589433064208028114318

6.
Explanation: https://www.merriam-webster.com/dictionary/picnicking
Collection Name: English Verb
Name of the item: picnicking.eth
Token ID: 82301146337707167455415129209607894485296883715671274986234931463181713042450

7.
Explanation: https://www.merriam-webster.com/dictionary/frolicking
Collection Name: English Verb
Name of the item: frolicking.eth
Token ID: 19900447532671106982774080029203097964176766664060270952080148568202854361713

8.
Explanation: https://www.merriam-webster.com/dictionary/nonvisual
Collection Name: English Adjective
Name of the item: nonvisual.eth
Token ID: 49999400113075754260539154949695167752311483874958551328503946056126806046569

9.
Explanation: https://www.merriam-webster.com/dictionary/stupefied
Collection Name: English Verb
Name of the item: stupefied.eth
Token ID: 24083647772511747897392661657647406037895826469807806682900782937979836640866

10. 
Explanation: https://www.merriam-webster.com/dictionary/affectual
Collection Name: English Adjective
Name of the item: affectual.eth
Token ID: 

11.
Explanation: https://www.merriam-webster.com/dictionary/flagellation
Collection Name: English Noun
Name of the item: flagellation.eth
Token ID: 18309087928870519090272006627944500989750716846622938116336493716801274315865

12.
Explanation: https://www.merriam-webster.com/dictionary/unvanquished
Collection Name: English Adjective
Name of the item: unvanquished.eth
Token ID: 49890648948277035371116159876111881619659893171882311963962738004048977834404

13.
Explanation: https://www.merriam-webster.com/dictionary/unquantifiable
Collection Name: English Adjective
Name of the item: unquantifiable.eth
Token ID: 100545636827659737415836506532145774673110825015357459753756817427357758642570

14.
Explanation: https://www.merriam-webster.com/dictionary/indemnified
Collection Name: English Verb
Name of the item: indemnified.eth
Token ID: 26284893271343578176779315902503615382965166831979620866871375475369570002501

Thank you for all of your hard work! 

Best regards,

DMarine1074

**Comment by shukaeth** [comment]
Hi thx will be added!
