### ISSUE TITLE
Please add to existing category ❤️ (arabic 10k)

### ISSUE THREAD

**Issue by Razzledazzle20** [Zimtente/ens-collections#825]
1) 
Collection Name: Arabic 10k
If possible adding the following tags as well: Arabic and numbers
Name of the item: ۰۱۲۰.eth
Token ID: 50293442709721922169586460211689560891152855460748824841884176507938531540657

**Comment by shukaeth** [comment]
Hi, Arabic 10k numbers collection is already pre-defined - you cannot add numbers to that, as all 10k numbers are already  deposited in that club. Your number also is a "arabic extendet index" :
![image](https://user-images.githubusercontent.com/107618056/194754561-49352746-fd54-46fb-bc0a-70cd6d49207a.png)

original arabic 10k numbers are "ARABIC-INDIC DIGIT" as shown below:

![image](https://user-images.githubusercontent.com/107618056/194754618-769b6919-6f62-49fd-84f6-f8c238c80bf1.png)


Hope this helps!

greetings shuka.eth
