### ISSUE TITLE
Add to Female First Names

### ISSUE THREAD

**Issue by echoghi** [Zimtente/ens-collections#829]
- Collection: Female Firstnames
---
- Name of Item: maege.eth
- Token ID: 9932260336210789403746138656904021818467990675493222816874662728418512904550
---
- Name of Item: shiera.eth
- Token ID: 43331782392360917013038259115499369392820530834897571737226376086685005808585
---
- Name of Item: eleyna.eth
- Token ID: 80060846847947954046116260964487637406974341117900254570397233880425288181657
---
- Name of Item: jeyne.eth
- Token ID: 85928977881425337792288355051876145149967196701890897658081228246263943996559
---
- Name of Item: elaena.eth
- Token ID: 89263489992118197856543226514109511404749184550761309809093632742207235995078

**Comment by shukaeth** [comment]
Hi thx, names will be added after we release the new database - will be added then!
