### ISSUE TITLE
Add to female firstnames category

### ISSUE THREAD

**Issue by Petardopy** [Zimtente/ens-collections#830]
Hi guys just amazing work with the bull renew tool. AMAZING

Thank you for that 

I want to Add this names to the female firstnames category please

Jhenifer https://app.ens.domains/name/jhenifer.eth/details

Jheniffer https://app.ens.domains/name/jheniffer.eth/details

**Comment by shukaeth** [comment]
Hi thx! 

names will be added after we release the new database - will be added then!
