### ISSUE TITLE
Please add the following words to the 5 Letter Dictionary Category

### ISSUE THREAD

**Issue by eselby84** [Zimtente/ens-collections#832]
1.
Item Name: **yajes.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/yajes
Token ID: 65958256088274663844575820187821886741897320274880357070233333106702819573921

2.
Item Name: **obiit.eth**
Collection: 5 Letter Dictionary; English Verbs
Explanation: https://www.merriam-webster.com/dictionary/obiit
Token ID: 12052097201181221190804847389864291207140698376601443010314109930207396920606

3.
Item Name: **shewn.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/shewn
Token ID: 110225697412104171558823993355086090708010450731026926256657426186697168232783

4.
Item Name: **pauas.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/pauas
Token ID: 5813934499227865047920545462114096182324375589982400468302916484995475588086

5.
Item Name: **pungs.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/pungs
Token ID: 81126802076985340524113057201568277302341597241377831127337889511552892500523

6.
Item Name: **palpi.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/palpi
Token ID: 33425969424937005358196395148973785274199281398386833303087224874745103776789

7.
Item Name: **anyus.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/anyus
Token ID: 45671356992270356728736284125596231315046812167052916081872643462675686277167

8.
Item Name: **ungot.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/ungot
Token ID: 35339002760452215408917726222583342092741793714384715632840023833544776229405

9.
Item Name: **pirns.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/pirns
Token ID: 46668792390401591025359175036790213221020232531189047832995336024509664785149

10.
Item Name: **ulnae.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/ulnae
Token ID: 19822414390572053723108808872619348946839534840532477160594915128829223006221

11.
Item Name: **uveas.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/uveas
Token ID: 100174118857647948015695251766947091491564489546969326492278451825478636031261

12.
Item Name: **pahos.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/pahos
Token ID: 38023780485066416193963167797500739667085639499235765659829616149678296622082

13.
Item Name: **phyma.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/phyma
Token ID: 94462890659400429782150927808887711775128936503362469527372899145586999611870

14.
Item Name: **wadna.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/wadna
Token ID: 19843293894613384842504383265173678034328675165005404431433397651398537461913

15.
Item Name: **raobs.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/raobs
Token ID: 104920553668503349215893888750847976087877717703631070483853405176199477389646

16.
Item Name: **sceat.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/sceat
Token ID: 66779309954905778540931690252768425866841292451713765423071111581300771289827

17.
Item Name: **typps.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/typps
Token ID: 60320704004807190480684651754633588576043612086925701906838862169002865117438

18.
Item Name: **tawie.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/tawie
Token ID: 69664359213136473503978904055629271953798287888286549339355366954570622221992

19.
Item Name: **spean.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/spean
Token ID: 78440174768551093137913608401466951280714194920328108405073961644026347792119

20.
Item Name: **rebab.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/rebab
Token ID: 100602774627177921377635971679370958205921009157744984816493952947276060086593

**Comment by shukaeth** [comment]
Hi thx, names will be added after we release the new database - will be added then! 

cant add wadna ( its scottish dialect) / obiit ( latin ) / yajes (spanish origin) for now, as we only inlcude english for now

Greetings,

shuka.eth

**Comment by eselby84** [comment]
Thank you for the feedback.
