### ISSUE TITLE
Add these emojis in single ethmoji category 

### ISSUE THREAD

**Issue by web3folk** [Zimtente/ens-collections#833]
Hello ensvision team, @shukaeth 
I need my following emojis to be categorized in single ethmoji. Please review and fix them. I have attached the screenshots too.! Thanks.! 

![IMG_20221003_215852](https://user-images.githubusercontent.com/114356494/193635754-8d98c7fc-028a-4a46-8a72-a77e53251b9c.jpg)
Token ID : 
56589133791182328990702452673238257733403652943033151989143761050156292487946

![IMG_20221003_215909](https://user-images.githubusercontent.com/114356494/193635815-5150e126-cee5-4f23-b9c6-78fcb1bab9e1.jpg)
Token ID : 
87545229799021085583596036775842462131122444202857375197806134421267815472168

![IMG_20221003_215927](https://user-images.githubusercontent.com/114356494/193635883-cb5772cb-51ab-4958-ae23-8806c1b3c36c.jpg)
Token ID :
69216462386432107027256187162500906081865641433858665291122930223284218630488

**Comment by PmCanary** [comment]
A Silly request like this is the reason why they are so backed up. These are not single ethmojis, they are 2 emojis each. smh

**Comment by PmCanary** [comment]
do me a favor and try copy and pasting the above ethmojis vs your own. they are true single emojis vs yours that are two separates.

**Comment by web3folk** [comment]
Yes I did copy paste and my emojis are also in same line and length without any space or other things.
And its a request to you please do me a favor by not commenting again on my issue.!
Let @shukaeth review and fix my issue.!!
Ensvision team knows better where it needs to be categorized.

**Comment by Zimtente** [comment]
these are not single ethmojis.
