### ISSUE TITLE
2 words to add to English Nouns

### ISSUE THREAD

**Issue by ENSfuturist** [Zimtente/ens-collections#835]
Please could you kindly add these two words to the English Nouns category. Many thanks

saxophones.eth (noun)
Token ID: 42677303265782842570637969772493974101431465989042681201569674717712839252969

sportiness.eth (noun)
Token ID: 34594334963570621058829391400343417939377252003026926488842966386249947337451

**Comment by shukaeth** [comment]
Hi thx will be added after we release new database - will be added then!
