### ISSUE TITLE
Add these domains to English Verbs please

### ISSUE THREAD

**Issue by zvchvry** [Zimtente/ens-collections#841]
strategizing.eth 20035788009003456444213981623496711296547846703176414035363252431887942130272

cataloging.eth 92050305687750865420574953123119336179484073608303119248585750894568430272946

disobeyed.eth 41991468906474858687926386333558528885697281812986303657027783210793812130139

ratted.eth 22360960824306415310685851575461534278608584501297762400537231127933161624003

unclip.eth 52932605130930250782842182250928776806051996019360129707113866629216856918084

reattach.eth 103976872775677853021043888380734261181519445991891076053099283966639094003651

malfunctions.eth 109772219931430094801872976281135895251511920658763038240220334188029722372821

**Comment by shukaeth** [comment]
Hi thx will be added after we release new database - will be added then!
