### ISSUE TITLE
Please add the following words to the 5 Letter Dictionary Category

### ISSUE THREAD

**Issue by eselby84** [Zimtente/ens-collections#844]
1.
Item Name: **snath.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/snath
Token ID: 26132065142841578032874470952421667622302086037249771902255338905149903952026

2.
Item Name: **punas.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/punas
Token ID: 95515461929524509453550409415253075923471815345443013247736720342308749364301

3.
Item Name: **plups.eth**
Collection: 5 Letter Dictionary; English Adjectives
Explanation: https://www.merriam-webster.com/dictionary/plups
Token ID: 57080335351683183307697623757845168055345825033757093366626515308075261777995

4.
Item Name: **zoeal.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/zoeal
Token ID: 57080335351683183307697623757845168055345825033757093366626515308075261777995

5.
Item Name: **unlax.eth**
Collection: 5 Letter Dictionary; English Verbs
Explanation: https://www.merriam-webster.com/dictionary/unlax
Token ID: 65189566078690896662712383883495123316449228072387979354984128673258917130129

6.
Item Name: **unhot.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.dictionary.com/browse/unhot
Token ID: 28165487064996814106991819946282447932568457740300745906479406271112984565761

7.
Item Name: **teths.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/teths
Token ID: 32092303792913990001846115532409796870487468588170784637356736640147242779984

8.
Item Name: **odahs.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/odahs
Token ID: 6500372421662969148482620696292255381513708046453873075483395539342846280993

9.
Item Name: **speos.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/speos
Token ID: 41999032813505736123139074980208699763511759132357666989506313339735680384285

10.
Item Name: **skeds.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/skeds
Token ID: 94606603235950628992513962130163748648317135007005585735849575915200648923200

11.
Item Name: **alods.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/alods
Token ID: 107227541928107967736607802881723048526181771003431489595555014030324490547045

12.
Item Name: **triga.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/triga
Token ID: 24837224271806867457608623852395708393317492558622872478369160924021372184126

13.
Item Name: **syces.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/syces
Token ID: 19810730692507733280768614157842368126302752591939956871826887429326943749204

14.
Item Name: **smews.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/smews
Token ID: 114996861227970503482899978574105191781990206882873959785915057615646893533830

15.
Item Name: **tolyl.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/tolyl
Token ID: 11611551179294863561972891906141418545773977639670136271108077210999673741167

16.
Item Name: **pulas.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/pulas
Token ID: 72681004662841335275217842328356193311270378607318408110975544221616270991139

17.
Item Name: **pukus.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/pukus
Token ID: 105341310361008173570081433566330815940322572720523445782636454166425526015392

18.
Item Name: **olpes.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/olpes
Token ID: 34768907221239726018093852615198008688952948708714799780956330633820638312312

19.
Item Name: **yeans.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/yeans
Token ID: 48342014486815764974201903171431381791616646139669777687956293671741720660495

20.
Item Name: **odyls.eth**
Collection: 5 Letter Dictionary; English Nouns
Explanation: https://www.merriam-webster.com/dictionary/odyls
Token ID: 19262698195412976883092223648042019811527668162982840794960208399056586235579

**Comment by shukaeth** [comment]
thx will  be added!
