### ISSUE TITLE
Verb / Adjectives / Nouns to add to English categories

### ISSUE THREAD

**Issue by ENSfuturist** [Zimtente/ens-collections#846]
jeering.eth (verb)
https://www.merriam-webster.com/dictionary/jeering
Token ID: 66599060176694607276574604120455408261516402722917457889584283594004313228366

------------

humanness.eth (adjective)
https://www.merriam-webster.com/dictionary/humanness
Token ID: 31623739981292151476191485749665115737607688730853357140730860236173165620613

barricaded.eth (adjective)
https://www.merriam-webster.com/dictionary/barricaded
Token ID: 25991490051352988023981239883806172016426039419090049463250837973987318222820

battleful.eth (adjective)
https://www.thefreedictionary.com/battleful
Token ID: 57785126621640901047768494765912808659657414666642448943541154747221130069940

------------

keyholes.eth (noun)
https://www.merriam-webster.com/dictionary/keyholes
Token ID: 34705896534426660524223499158765676970532435879115804514364611654002905281240

flagrance.eth (noun)
https://www.merriam-webster.com/dictionary/flagrance
Token ID: 80110761634577486445312738915948947613150766288285215371674121526132146333452

ultimation.eth (noun)
https://www.merriam-webster.com/dictionary/ultimation
Token ID: 18653101399504002882781015154766500036123490781117998924966432661936057456589

tambourines.eth (noun)
https://www.merriam-webster.com/dictionary/tambourines
Token ID: 46667814919100545405132781137838023581316479394827469887133550839116561681538

sitars.eth (noun)
https://www.merriam-webster.com/dictionary/sitars
Token ID: 62469696895775444708302957714611069881163430214290318428490430836665580149572

accordions.eth (noun)
https://www.merriam-webster.com/dictionary/accordions
Token ID: 106945364113628181079953134567306120434803388349623761291051504004693787196658

xylophones.eth (noun)
https://www.merriam-webster.com/dictionary/xylophones
Token ID: 108419922081491811739991090737364841021195804760134271001054153758595610358628

managership.eth (noun)
https://www.merriam-webster.com/dictionary/managership#other-words
Token ID: 54606945505087820323157367408947929849384441974518730362979740423571499876079

privatism.eth (noun)
https://www.merriam-webster.com/dictionary/privatism
Token ID: 89019718224112789168692626374470107866285218414539581513688139180416008312982

**Comment by shukaeth** [comment]
thx will be added
