### ISSUE TITLE
Verbs to add to English categories

### ISSUE THREAD

**Issue by cryptoshoper** [Zimtente/ens-collections#847]
**neighed.eth**
https://www.merriam-webster.com/dictionary/neighed
Token ID: 60454127508641617544617029249464566416766187511341254882778362057750079686337

**larded.eth** 
https://www.merriam-webster.com/dictionary/larded
Token ID: 111470581785498787630817353660230564178710746926220093252389906007524201696118

**jibbed.eth**
https://www.merriam-webster.com/dictionary/jibbed
Token ID: 83892508663857595529449731756765523638832191936704529674475679174901362538098

**quelled.eth**
https://www.merriam-webster.com/dictionary/quelled
Token ID: 92634177523191102062695973800134643973319001654258966954326566846218532905106

**partaken.eth** 
https://www.merriam-webster.com/dictionary/partaken
Token ID: 29320505574127706221314182248396669200807406718858313806750725369120145882129

**quavered.eth** 
https://www.merriam-webster.com/dictionary/quavered
Token ID: 41992130542777765037177822939214462086517927982971274815244798537548538756422

**scabble.eth**
https://www.merriam-webster.com/dictionary/scabble
Token ID: 91550722800993437711415225553851866428418428000241503035630795885180121311192

**jabbered.eth**
https://www.merriam-webster.com/dictionary/jabbered
Token ID: 17288848205818227021099103290840083608591556245374783926064155728894716513430

**kneeled.eth**
https://www.merriam-webster.com/dictionary/kneeled
Token ID:  40419343388793331841199477875700896322694111264807184018664342283789447765300

**objectified.eth**
https://www.merriam-webster.com/dictionary/objectified
Token ID: 52903182334398308361312038230478468858644509120380666006374347625182303729109

**simplifications.eth**
https://www.merriam-webster.com/dictionary/simplifications
Token ID:  83655967418043944807867194159361267682249837930467383570182849006804725974510

**officiated.eth**
https://www.merriam-webster.com/dictionary/officiated
Token ID: 94885137888476712446896975122493797970081366562284196628663006781186977896196

**shrilling.eth**
https://www.merriam-webster.com/dictionary/shrilling
Token ID: 11409828808543554894627584149153113978342388874991358437885249688793622467790

**squeaking.eth**
https://www.merriam-webster.com/dictionary/squeaking
Token ID: 59566032835702979938647904876947645382462089769312221502130734370263866524675

**mediatized.eth**
https://www.merriam-webster.com/dictionary/mediatized
Token ID: 54922967105565662034396186245211551435119344335243676105622294402373774523556

**idealizes.eth**
https://www.merriam-webster.com/dictionary/idealizes
Token ID: 57043710500080703171599721801207304552698385164374678594277958823363588922800

**uncurled.eth**
https://www.merriam-webster.com/dictionary/uncurled
Token ID:  25238358267953816583969735142401729546510557011447688083460319367901335116303

**quickened.eth**
https://www.merriam-webster.com/dictionary/quickened
Token ID: 11165261528090433820807943127452126332882855192923257028549181269789362476895

**vibrated.eth**
https://www.merriam-webster.com/dictionary/vibrated
Token ID: 97819073704237988751945658342399105301647019781003950627121951099774595413963

**mediatize.eth**
https://www.merriam-webster.com/dictionary/mediatize
Token ID: 99585293392458961966761270348224726263544123631859172665910247622707933829608

quibbled.eth
https://www.merriam-webster.com/dictionary/quibbled
Token ID: 100729316891090542364795857739440992409363528532796547526980918267823381749337

**Comment by shukaeth** [comment]
hi thx will be added!
