### ISSUE TITLE
Nouns to add to English categories

### ISSUE THREAD

**Issue by cryptoshoper** [Zimtente/ens-collections#848]
**skidded.eth**
https://www.merriam-webster.com/dictionary/skidded
Token ID: 59650761224391021949256208275547259437516367789544021825941132109641968087405

**sassed.eth**
https://www.merriam-webster.com/dictionary/sassed
Token ID: 84734635435452063314774923424520627299218318901915966666236881367655081664302

**warbled.eth**
https://www.merriam-webster.com/dictionary/warbled
Token ID: 31868166946795453399921517571868964969564768017054108956278551635029802719155

**quivered.eth**
https://www.merriam-webster.com/dictionary/quivered
Token ID: 56412680870106410932629558994831725882872102972756686723612735057189240384235

**swotted.eth**
https://www.merriam-webster.com/dictionary/swotted
Token ID: 7397807151668982456100987574531990022423628250158722336857849621073656880242

**lambed.eth**
https://www.merriam-webster.com/dictionary/lambed
Token ID: 61017433291717342572226333173169932334636688364239207231115191108499333899943

**ropers.eth**
https://www.merriam-webster.com/dictionary/ropers
Token ID: 5607955292736958566443077999104069850584427268520850904092945660254041554978

**patted.eth**
https://www.merriam-webster.com/dictionary/patted
Token ID: 73212321289159993835089266450640476408172852994539461176842083034655743060673

**Comment by shukaeth** [comment]
thx will be added!

**Comment by cryptoshoper** [comment]
how long will it take to update on the website because it still
doesn't show up in the categories
