### ISSUE TITLE
Adjectives to add to English categories

### ISSUE THREAD

**Issue by cryptoshoper** [Zimtente/ens-collections#849]
**unbolted.eth**
https://www.merriam-webster.com/dictionary/unbolted
Token ID: 85847856139170125341739993215528938072466819149994475763762791770846326815678

**sweetless.eth**
https://www.merriam-webster.com/dictionary/sweetless
Token ID: 103278352717975993579522032743024315963543870184171286494145857507435432865829

**selfdisciplined.eth**
https://www.merriam-webster.com/dictionary/selfdisciplined
Token ID: 32756569733434958667743683956362195564152919741444291434049767378381058137983

**Comment by shukaeth** [comment]
thx will be added, 
selfdisciplined will be added as shown on merriam-webster: self-disciplined.eth

shuka.eth

**Comment by cryptoshoper** [comment]
how long will it take to update on the website because it still
doesn't show up in the categories
