### ISSUE TITLE
Please Add Following to English Adjectives Collection

### ISSUE THREAD

**Issue by triplevodka** [Zimtente/ens-collections#852]
<html>

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.1.5.2 (Windows)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>

Explanation: | English Language Adjective - https://www.collinsdictionary.com/dictionary/english/curmudgeonly
-- | --
Collection Name: | English Adjectives
Name of Item: | curmudgeonly.eth
Token ID: | 72908402010198741220541465844128184150385106644216936214861745477121447857438
  |  
Explanation: | English Language Adjective - https://www.merriam-webster.com/dictionary/meddlesome
Collection Name: | English Adjectives
Name of Item: | meddlesome.eth
Token ID: | 61150970536541061693627568178517074612968888754024317493698906708626302868954
  |  
Explanation: | English Language Adjective - https://www.collinsdictionary.com/dictionary/english/coltish
Collection Name: | English Adjectives
Name of Item: | coltish.eth
Token ID: | 75265999591056916108184872608979000368646825020047124252564323245734674140180
  |  
Explanation: | English Language Adjective - https://www.collinsdictionary.com/dictionary/english/fatalistic
Collection Name: | English Adjectives
Name of Item: | fatalistic.eth
Token ID: | 27501682484908691767079506497185157940352187456310456935049488436654924166743
  |  
Explanation: | English Language Adjective - https://www.merriam-webster.com/dictionary/unreceptive
Collection Name: | English Adjectives
Name of Item: | unreceptive.eth
Token ID: | 97925532923755665669164271699084659364602482799899110695046114845394012629035

</body>

</html>

**Comment by shukaeth** [comment]
thx will be added!
