### ISSUE TITLE
Please add following to English Nouns Category

### ISSUE THREAD

**Issue by triplevodka** [Zimtente/ens-collections#853]
<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.1.5.2 (Windows)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>

Explanation: | English Language Noun – https://www.collinsdictionary.com/dictionary/english/caecilian
-- | --
Collection Name: | English Nouns
Name of Item: | caecilian.eth
Token ID: | 64255041819111223360811960308050342455050065341441454207877485423152989872911
  |  
Explanation: | English Language Noun – https://www.collinsdictionary.com/dictionary/english/paleozoology
Collection Name: | English Nouns
Name of Item: | paleozoology.eth
Token ID: | 13442141500052420742395263827591762735185633341887763392662782286054753862030

</body>

</html>

**Comment by shukaeth** [comment]
hi thx both will be added.
