### ISSUE TITLE
Please add to 0xEmojis Category

### ISSUE THREAD

**Issue by triplevodka** [Zimtente/ens-collections#854]
<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.1.5.2 (Windows)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>

Explanation: | 0 x Emoji
-- | --
Collection Name: | 0xEmojis
Name of Item: | 0x🧑🏿‍💼.eth
Token ID: | 74312094903499736874568371044976143916025189178769065824051004829640434215451

</body>

</html>
Explanation:	0 x Emoji
Collection Name:	0xEmojis 
Name of Item:	[0x🧑🏿‍💼.eth](https://app.ens.domains/name/0x%F0%9F%A7%91%F0%9F%8F%BF%E2%80%8D%F0%9F%92%BC.eth/details) 
Token ID:	74312094903499736874568371044976143916025189178769065824051004829640434215451

**Comment by shukaeth** [comment]
Hi 0xEmojis Category atm only consists of 1 Emoji after the 0x!

f.E.
![image](https://user-images.githubusercontent.com/107618056/202914209-48ac52d0-0cd1-40c8-b819-6e552762ae5d.png)
