### ISSUE TITLE
English Verbs/Nouns/Adj

### ISSUE THREAD

**Issue by vpofsales** [Zimtente/ens-collections#855]
All are from Oxford language definitions. The only one not in merriam-webster would be spätlese. It is an english word though, depending on which english dictionary. 

détente / noun
 token: 6725547937663197302050694216543749934494264864149857476322788906629218451510  
 
 readability  /noun
  token: 61295952458972257898433919743630055769911579529454851797540983601910869461903  
  
  kabinett / noun 
  token: 103879687122111769330716896467075626755055469257551705319239516243559448127518  
  
  spätlese  /noun  
  token: 29605671284219767572820562970552382454435223153662914499943851522820929657104  
  
  parergon / noun  
  token: 36045971173067503731447476920486709571214164764476698850885416967171063528305  

  faceplate  /noun
   token: 13356394404979326237575251942092796965714589749987793290029312117955888141992 

     penholder  /noun
      token: 36616848152244138186095932659830897068955308144090168383193709455216062873524
        
        l     awnchair / noun
         token: 110344211853948623652074223112281792318594104035873995823453775833238167829211
 
 sofabed  /noun 
 token: 104863314643449011471049692572863608782919701056916220932776931468992745975351  

 walloped  /verb
  token: 94413465230941849371688846393504520720857002140761074855877327188431518451984  

  attired  /verb 
  token: 63687748875953212146618095578036739729130319022226070180868715240150404620148  

  harshen  /verb
   token: 64892277423261679882256664058112192825219680205138676604391199833244158039627

     forebode  /verb 
     token: 52778138955323910038346861622670021816648774988551342546080286398110628357966
       
       mindnumbing  /adj
        token: 62571830744006149171695715814487217339129439098747804753569563833780102350961  

        sneakier  /adj
         token: 29509059553837284848739388947539780000320602598211778243318896720307666640321

**Comment by shukaeth** [comment]
hi 

thx for your additions, unfortunately we'll only add english names for now, so I cant inlcude these:
kabinett / noun 
  token: 103879687122111769330716896467075626755055469257551705319239516243559448127518  
  
  spätlese  /noun  
  token: 29605671284219767572820562970552382454435223153662914499943851522820929657104  
  
  Also only proper spelled words will be added, mindnumbing will be added like it is shown officially on merriem webster:
       mind-numbing

https://www.merriam-webster.com/dictionary/mind-numbing

Also all zero-with-joiners will be removed from the names. Some of the names you posted above contain zero-with-joiners, please always be careful when buying such.

greetings

shuka.eth
