### ISSUE TITLE
Issue #803 #806, Hello, it's been 20 days since the last update and you approved my requests, but the items weren't added to the collection.

### ISSUE THREAD

**Issue by nuevas2012** [Zimtente/ens-collections#856]
Issue #803
Link: https://github.com/Zimtente/ens-collections/issues/803

Issue #806
Link: https://github.com/Zimtente/ens-collections/issues/806

**Comment by shukaeth** [comment]
hi thy, thats because we were not able to make any updates til now! Your names are on the list to get updated.

thx for your patience
