### ISSUE TITLE
3L Months

### ISSUE THREAD

**Issue by oneilleth** [Zimtente/ens-collections#86]
Hi I would like you to add 3 letter months.

{
  "name": "3L Months",
  "slug": "3L Months"
  "description": "Months in the Gregorian calendar abbreviated to 3 letters",
  "csv": ["months abbreviated.csv
[months abbreviated.csv](https://github.com/Zimtente/ens-collections/files/9037403/months.abbreviated.csv)
"]
}

**Comment by CryptoGatsu** [comment]
pushed to main :D
