### ISSUE TITLE
ADD IRP TO 3 Letter Dictionary

### ISSUE THREAD

**Issue by MrNice10** [Zimtente/ens-collections#868]
"irp" is considered a noun or obsolete noun in english. Def:
    noun A grimace or contortion of the body.
3 Letter Dictionary
irp.eth
23637574558787042406890687418468506156416862036054380050146056201531461022640

**Comment by shukaeth** [comment]
thx will be added.

**Comment by shukaeth** [comment]
just saw, that this is already in 3L Dict Collection:
![image](https://user-images.githubusercontent.com/107618056/200172046-a25f746d-d675-4ec8-ab10-b182090a6c1a.png)

**Comment by MrNice10** [comment]
Hi, is in 3 Letters collection but not in 3L Dict Collection yet
