### ISSUE TITLE
ADD republic-of-artsakh TO COUNTRIES

### ISSUE THREAD

**Issue by MrNice10** [Zimtente/ens-collections#869]
"republic-of-artsakh" is a countrie like you can check in wikipedia: https://en.wikipedia.org/wiki/Republic_of_Artsakh as others in the category is a hyphen countrie name
Countries
republic-of-artsakh.eth
107101880979267346438885979060805475400343958835976141854290990463375430711615

**Comment by shukaeth** [comment]
hi countries will be reworked and updated to only UN countries (closed list then)
thx!
