### ISSUE TITLE
Overhaul the Countries Category

### ISSUE THREAD

**Issue by Sexadegen** [Zimtente/ens-collections#870]
The Countries category has become a bit messy with duplication, misspellings and unnecessary hyphens. In an effort to tidy it up, I suggest that we move to a more tightly curated list. I've put one together for you to consider. The list has 230 "countries" where the focus is more on geography than politics. My suggestion is that this list replaces the existing one.

https://docs.google.com/spreadsheets/d/1LGWP_z1NVP2NIIP_NmMyFTC5nHEiXKRhvIVdUSoI3bY/edit?usp=sharing

**Comment by shukaeth** [comment]
belongs to #873 answer too!

thx
