### ISSUE TITLE
Previous requests not included in new database

### ISSUE THREAD

**Issue by echoghi** [Zimtente/ens-collections#871]
I had three issues recently closed that were supposed to be included with the launch of the new database. Unfortunately, I still don't see the names added to their categories, so I wanted to follow up. Thanks 🙏 

[Issue 760](https://github.com/Zimtente/ens-collections/issues/760)
[Issue 828](https://github.com/Zimtente/ens-collections/issues/828)
[Issue 829](https://github.com/Zimtente/ens-collections/issues/829)

**Comment by Sexadegen** [comment]
Issue 818 also closed but not included yet.

**Comment by shukaeth** [comment]
hi that is because we didnt make it to update it yet. All your names are on the list to be. 

Thanks for your patience.
