### ISSUE TITLE
Add names to Spanish Pre punks

### ISSUE THREAD

**Issue by Petardopy** [Zimtente/ens-collections#872]
Hi guys great work, can you please add this pre punks to the spanish pre punk

concursar https://app.ens.domains/name/concursar.eth/details
autorizaciones https://app.ens.domains/name/autorizaciones.eth/details
liquidaciones https://app.ens.domains/name/liquidaciones.eth/details
hospedajes https://app.ens.domains/name/hospedajes.eth/details
comarca https://app.ens.domains/name/comarca.eth/details
masajistas https://app.ens.domains/name/masajistas.eth/details
plasticos https://app.ens.domains/name/plasticos.eth/details
topografia https://app.ens.domains/name/topografia.eth/details

thanks guys! keep it up!

**Comment by D0mainsale** [comment]
petardas
tecnologiasdelainformacion
guineaecuatorial

**Comment by shukaeth** [comment]
@Zimtente

**Comment by shukaeth** [comment]
hi guys, thx for your patience - updated and online on vision now as spanish prepunks!

all the best,

shuka.eth
