### ISSUE TITLE
Overhaul the Capitals Category

### ISSUE THREAD

**Issue by Sexadegen** [Zimtente/ens-collections#873]
This is a companion to #870. It's a curated list of capitals for all of those countries listed that have capitals (a few don't). Once again it addresses the issues of misspelling, and hyphenation and inserts the 2019 apostrophe for some capitals where it was previously omitted. https://docs.google.com/spreadsheets/d/1B1MWFyOMbwkEG-vFOmp-U3tmBZ1Pn4MdCZUVjPHTKZs/edit?usp=sharing

**Comment by shukaeth** [comment]
hey - I am currently reworking both of those categories (countries and capital cities) - it will be a closed list then - will keep you informed!
