### ISSUE TITLE
Update Surnames | Checked with Forebears

### ISSUE THREAD

**Issue by D0mainsale** [Zimtente/ens-collections#874]
Ghania
Gañan
Orejuela
Eraso
Suphon
Garavito
guarnizo 
ratchani 
ibarguen
betancurt 
changgok
jeoung 
Sarda
Chanyeol
Trueba
Sáez
Díez
Diestro
Campoy
Merlos
Blesa
ícaro
Armenteros
Colmenero
Salido
Madrazo
Trigueros
McLamb
Punset
Salvio
Irasema
Resina
Fulgencio
Balduino
Abellan 
Piqueras
Evole
Cañadas
Luengo
Pelangi
Nazaret 
Nicholes
Valdano 
Lorca
Hinrich

Thanks ;)

**Comment by shukaeth** [comment]
thx will be added to surnames category.

shuka.eth

**Comment by D0mainsale** [comment]
Thanks bro ;-)

**Comment by D0mainsale** [comment]
Sorry,

Evole is wrong; is Évole.

**Comment by D0mainsale** [comment]
Sorry, Sarda its wrong; its Sardá.

**Comment by D0mainsale** [comment]
When this? ;-)
