### ISSUE TITLE
Update Pokemon with normalised ’

### ISSUE THREAD

**Issue by Sexadegen** [Zimtente/ens-collections#875]
There are two Pokemon whose names have been truncated up until now because there was no apostrophe available. Now that we have a normalised apostrophe (or will do very soon), can we please change the following names:

Remove farfetchd, add farfetch’d
Remove sirfarfetchd, add sirfarfetch’d

Tokens below

{
  "farfetch’d": "36213120110548340325903976714622525118375393375228414826861100856663760466633",
  "sirfarfetch’d": "69287320523718252643054023938541856016440066158819268951374621458483724729015"
}

**Comment by shukaeth** [comment]
' is not normalised yet. Will update that when it is the case.
