### ISSUE TITLE
Add adjectives pls

### ISSUE THREAD

**Issue by bly99** [Zimtente/ens-collections#876]
**heroical**
https://www.vocabulary.com/dictionary/heroical
token: 83307381082388034141559294537208001357367069290314054843213032355249707497031

**archetypical**
https://www.vocabulary.com/dictionary/archetypical
token: 101086881355135834029981685553390379638475972944641396512104655237715819774644

**idealised**
https://www.vocabulary.com/dictionary/idealised
token: 98862904889714226016265858832361590314668145681391479388408394421155829345859

**extremest**
https://en.wiktionary.org/wiki/extremest
token: 84674152119674883873648691333078800589210114111237116301413364057860531796652

**electrotechnical**
https://www.vocabulary.com/dictionary/electromechanical
token: 90383626568677848441704813520881780631541756545431548559786203704001706140893

**humblest**
https://en.wiktionary.org/wiki/humblest
https://www.dictionary.com/browse/humblest
token: 74475217600710177222002051249551061551042743669010594360967096839438138743640

**pictural**
https://www.vocabulary.com/dictionary/pictural
token: 41019690774846170921056035066252364137765128441543698509976154041421784568934

**ambassadorial**
https://www.vocabulary.com/dictionary/ambassadorial
token: 70703572510223888656743630435462321163160743749771982056891106838980756542216

**textural**
https://www.dictionary.com/browse/textural#:~:text=%5B%20t%C4%95ks%E2%80%B2ch%C9%99r%2D%C9%99l%20%5D,the%20texture%20of%20the%20tissues.
token:  98933425941171495769029752491078536410933790047839126874471476780605983191961

**microbic**
https://www.vocabulary.com/dictionary/microbic
token: 92651599855921822999004366363944747405327050263810349176741836681609163970323

**televisual**
https://www.dictionary.com/browse/televisual
token: 97600285055691234536228646633143675769742385514708402696771866896015301462417

**unactivated**
https://en.wiktionary.org/wiki/unactivated#:~:text=Adjective,%2C%20especially)%20never%20yet%20activated.
token: 33501482501490971930604861957530257618372842601547992530325140999866536955423

**gloomiest**
https://www.collinsdictionary.com/dictionary/english/gloomiest
token: 98787489559583685696914069880819493335373818462096317359863186984133408132240

**survivable**
https://www.merriam-webster.com/dictionary/survivable
token: 56673151594623317252843458102581493814981413514926166684332964130915287448288

**messiest**
https://www.collinsdictionary.com/dictionary/english/messiest
token:  84206553985165945678042877349625584062625596611653410865317505845795885737026

**dryish**
https://en.wiktionary.org/wiki/dryish#:~:text=dryish%20(not%20comparable),Quite%20dry%2C%20relatively%20dry.
token:  67269363404605550009482912792303711708110796855356692905424993032135741860513

**gravest**
https://en.wiktionary.org/wiki/gravest
https://www.merriam-webster.com/dictionary/grave
token:  15369290286118734977784353834895451434439140241272753384983791118408286620234

**conflictual**
https://www.collinsdictionary.com/dictionary/english/conflictual
token: 22094844684515284672334516432489493008039582942372098240667134945135375536630

**aweless**
https://www.merriam-webster.com/dictionary/aweless#:~:text=1%20%3A%20feeling%20no%20awe,2%20obsolete%20%3A%20inspiring%20no%20awe
token: 18258740419179234042660740263051474121190814396651685057285922226807024660185

**Comment by shukaeth** [comment]
Hi 
Thank you for your suggestions - please be aware only properly spelled words, which are officially on https://www.merriam-webster.com/dictionary will be added. Other sources will not be taken into grant. 

All the best,

shuka.eth

**Comment by bly99** [comment]
> Hi Thank you for your suggestions - please be aware only properly spelled words, which are officially on https://www.merriam-webster.com/dictionary will be added. Other sources will not be taken into grant.
> 
> All the best,
> 
> shuka.eth

Thank you! I added more merriam-webster sources, cause didnt know that only this one is in grant! Have a good work!
