### ISSUE TITLE
Add names to female-firstnames

### ISSUE THREAD

**Issue by tonynhubrito** [Zimtente/ens-collections#879]
Add names to female-firstnames

talina.eth
wanessa.eth
brunna.eth
lidiane.eth 
marcilene.eth

**Comment by shukaeth** [comment]
thx will be added

**Comment by tonynhubrito** [comment]
when will they be added?

**Comment by shukaeth** [comment]
hey, will be added with the next merge coming next week.

all the best,

shuka.eth
