### ISSUE TITLE
Adding these Firstnames to the category “Male Firstnames”

### ISSUE THREAD

**Issue by MarioENS** [Zimtente/ens-collections#882]
I would like all the firstnames below to be added since thousands of people have them, which you can see through forebears.io . Thanks in advance.

**saffi** (95954497080131256534527134230976509445994521354454870087257999269094222978274)
**alniyaba** (47435107573173847232277776369673006073395411374986046315144672561640948608787)
**guoqin** (40767300862400532552175459939719886436417116344388445971281889299926272942869)
**seram** (84507387008983492220752596197812889365223366362635347367354956107562281373738)
**nkosinathi** (57873124940768257123260652603310983566414046669423610944626979373496584523723)
**matom** (41897025227173689269167631848323777519725529354806225455952265381087157836838)
**hongan** (2013556177514185787701301240472778071498491293963469064135785079346566583582)
**dumisani** (19922319645758295889114918593410974361992754076168823009612888160111337409103)
**wenbiao** (67250989043227961800024428563615498676564497682107894475616958795846279101745)
**weichao** (15357757707442627279043665267631704956835164381036537482227673659997709092480)
**ubhai** (97532147707350818557169574577188967059553923497167790960004320352017912096172)

**Comment by shukaeth** [comment]
thx also will be added
