### ISSUE TITLE
Adding these Firstnames to the category “Female Firstnames”

### ISSUE THREAD

**Issue by MarioENS** [Zimtente/ens-collections#883]
I would like all the firstnames below to be added since thousands of people have them, which you can see through forebears.io . Thanks in advance.

**sireen** (103876689590442760202644950000741350952761235904448560903373180185550514898571)
**angelene** (110473497166668430050641437031531264006994672225707423388427921142632803567494)
**safieh** (71543544104955581990464956789094952824614401134106826727928175107660630323)
**sahro** (108170177428481940349525465784256128821023352138978278076974583176977369781655)
**bakhitah** (1306026156418948859395716999326230419772805160230398872239919712511087271500)
**fartun** (19247193278038985595552456067051700690714248379474137625679525157237546384247)
**meizhu** (60391956229467634217145911230323791275578971836694811316828971036281142779028)
**chanah** (78944470617548738316832062350121569318951671721113040714452158072172111762166)
**cuiling** (74023232281817314225545896417892849071083974192850137916512835491082630575750)
**wilai** (54393627268209259489713285590986325433243745187790873675311508569926430815116)
**vasanta** (35901757001222078442844944286606677354713824579242444175765492837584482124736)
**vindu** (56188710443892085794683407481698661894048174819470864297837029862103767072046)

**Comment by shukaeth** [comment]
hi thx will be added too
