### ISSUE TITLE
Adding these Surnames to the category “Surnames”

### ISSUE THREAD

**Issue by MrDomains** [Zimtente/ens-collections#884]
I would like all the surnames below to be added since thousands of people have them, which you can see through forebears.io . Thanks in advance.

**valappil** (106055775545458181780833161984712831883085851159724725957460630827764419116996)
**alshihi** (67652996686107321194626878750942375933530590339788977604494032355474136115768)
**alyan** (93655039583935178056063913110247552920402845588353031738521151542654130590335)
**altaniji** (57173149967530787329869173645803521650709818892380112830048806628830226756165)
**elkutby** (83830625201680957228543683622443898574296010878130367804361923246896431866257)
**elhammady** (62929822175746493610945005724488959078844370785697520912053917414577327429842)
**elmisri** (100656890673316577113082505166123104469188403428544438301304955239508368324395)
**elnekby** (70641267891326987646534571173537749038160919791038271494017438164650767205837)
**mahboub** (93340442503080622289270514525802164502106723898085132048069154483329897943426)

**Comment by shukaeth** [comment]
thx will be added
