### ISSUE TITLE
Adding slovakrepublic to the category “UN Countries”

### ISSUE THREAD

**Issue by MarioENS** [Zimtente/ens-collections#885]
I would like you to add the name slovakrepublic to the category “UN Countries”, since it is the official name of the country. You can see it below. Thanks in advance.

https://en.m.wikipedia.org/wiki/Slovakia

**slovakrepublic** (19565116170578297497433296631704286156058568813674964175415043492831611767377)

**Comment by shukaeth** [comment]
Hi there can be no adaptions, as the official UN Member States Homepage is the source for this category. 
https://www.un.org/en/about-us/member-states
![image](https://user-images.githubusercontent.com/107618056/202369955-60842d2d-9081-4286-8f92-69ade4ace011.png)
