### ISSUE TITLE
Adding a "Nicknames" and “Metaverse” categories

### ISSUE THREAD

**Issue by MarioENS** [Zimtente/ens-collections#886]
Please add the "Nicknames" and “Metaverse” categories. I think that nicknames and meta domains are important for ENS world. For example, i have some domains such as BlockchainManiac, DomainPrincess, Defiwoman, Meta-Web, Meta-Chain, etc, and there is nothing for me. I imagine a lot of people have similar domains!

Thanks in advance.

**Comment by shukaeth** [comment]
Hi thanks for your suggestions -  that will be covered and solved with our new tagging system. Users can then set hashtags for their addresses/names f.E. like #Nicknames and others can find names connected to this hashtag via the top search bar.

All the best,

shuka.eth
