### ISSUE TITLE
Adding Names To The "Noun" Collection 

### ISSUE THREAD

**Issue by mamelives** [Zimtente/ens-collections#887]
Explanation why the item should be added to a collection--Screenshot Enclosed 
Collection Name--Noun Collection 
Name of the item--isolationism.eth
Token ID of the item-84222172066116040619227292695865359839319674671921994477979580131164407973143
![Screenshot_20221115-175406](https://user-images.githubusercontent.com/113834432/202042860-e5073cce-0344-4d35-805f-f524a8b5c592.png)

Explanation why the item should be added to a collection--Screenshot Enclosed 
Collection Name--Noun Collection 
Name of the item--shopsteward.eth
Token ID of the item-74994585171214030695549410123039580025075916656682782826094185758670613202147

![Screenshot_20221115-175436](https://user-images.githubusercontent.com/113834432/202043194-d1896db0-a0e6-4e7c-8b21-a6ac6ef76c92.png)

Thank you!!!

**Comment by shukaeth** [comment]
Hi thx will be added.
