### ISSUE TITLE
Adding A Name To The "Adjectives" Collection

### ISSUE THREAD

**Issue by mamelives** [Zimtente/ens-collections#888]
Explanation why the item should be added toa collection--Screenshot Enclosed
Collection Name--Adjectives Collection
Name of the item schizotypal.eth
Token ID of the item-105175738126306502362588721606057970973444895493675317227452015202547359723915

![Screenshot_20221115-182914](https://user-images.githubusercontent.com/113834432/202046924-d8505b1a-f17c-4c29-a0a2-5441faf0d8fe.png)

**Comment by shukaeth** [comment]
Hi thx, will be added.
