### ISSUE TITLE
Add names to "Surnames"

### ISSUE THREAD

**Issue by 0x807a** [Zimtente/ens-collections#889]
Explanation why the item should be added to collection: All valid surnames, not currently in the category

Collection Name: Surnames

Name of the item:
-lebowitz.eth
-sternbach.eth
-fischler.eth
-ashberry.eth
-croswell.eth
-kovitz.eth
-schiffman.eth
-skaife.eth
-broner.eth
-laubenstein.eth
-zechman.eth
-gurewitz.eth

**Comment by shukaeth** [comment]
same here! will be added.

all the best
