### ISSUE TITLE
Add Tamil 999 Club

### ISSUE THREAD

**Issue by Tamil999ENS** [Zimtente/ens-collections#89]
{
  "name": "Tamil 999 Club",
  "slug": "tamil-999-club"
  "description": "௦௦௦ முதல் ௯௯௯ வரையிலான தமிழ் எண்கள்",
  "twitter": "Tamil999ENS",
  "website": "",
  "chat": "",
  "logo": "![Tamil-999](https://user-images.githubusercontent.com/89325836/177141041-955b0dcb-4a94-4bae-9205-524fc10dcb02.png)",
  "csv": "[Tamil-999-List.csv](https://github.com/Zimtente/ens-collections/files/9038820/Tamil-999-List.csv)"
}

**Comment by MathieuTuli** [comment]
Seconded :joy: 

```json
{
    "name": "Tamil 999 Club",
    "slug": "tamil-999-club",
    "description": "Tamil numerals ௦௦௦ - ௯௯௯ ",
    "twitter": "https://twitter.com/Tamil999ENS",
    "logo": "tamil-999-club.png",
    "csv": ["tamil-999-club.csv"]
}
```
[tamil-999-club.csv](https://github.com/Zimtente/ens-collections/files/9042627/tamil-999-club.csv)
![tamil-999-club](https://user-images.githubusercontent.com/20361597/177232374-ddf21520-1f59-46d5-8589-65bb910edb7b.png)

I'm happy to use either configs, just want it uploaded!

**Comment by CryptoGatsu** [comment]
pushed to main!
