### ISSUE TITLE
Add first name cathrina.eth to female first names

### ISSUE THREAD

**Issue by fractionedeth** [Zimtente/ens-collections#891]
Hi there -

Can you please add cathrina.eth to the female first names category. 

As you can see here it is a female name of Greek origin which is a variant of Katherine:
https://charlies-names.com/en/cathrina/

The name can also be found with over 1000 LinkedIn results for the exact spelling of Cathrina. 

Collection name: Female Firstnames
Name of the item: cathrina.eth
Token ID: 63235397193711174420148133948269448090063329847418957377582473397352405899215

Many thanks for all your hard work with the categories!

**Comment by shukaeth** [comment]
Hi thank you, sure will be added with the next update :)
