### ISSUE TITLE
Adding a name to the "Noun" Collection 

### ISSUE THREAD

**Issue by mamelives** [Zimtente/ens-collections#892]
Explanation why the item should be added to a collection--Screenshot Enclosed
Collection Name--Noun Collection
Name of the item--shopsteward.eth
Token ID of the item-74994585171214030695549410123039580025075916656682782826094185758670613202147

Thank you!!!

![Screenshot_20221115-175436](https://user-images.githubusercontent.com/113834432/202953834-c94092e7-83c0-4eae-bcd2-3db9a87389f0.png)

**Comment by shukaeth** [comment]
Hi, as it contains a space between shop and steward the correct way to write it would be shop-steward.eth https://www.ens.vision/name/shop-steward - as the name is not registered yet, we can't put it in a category...
