### ISSUE TITLE
Update English Nouns

### ISSUE THREAD

**Issue by D0mainsale** [Zimtente/ens-collections#893]
dictaphone
electrocardiogram
banquette
employments
blizzards
pulseoximeter
urticaria
clustering
unstoppably
serendibite
rheumatoid
videophone
spacers
westerns
clipboards
chipboard
adolescents
brainstorms
boules
shampoos
exhibitionism
jurists
spectroscopy
micropays
sextuplet
bumder
binturong
boatdocks
halitosis
habitations
zooplankton
pentathlon
colostate
jerkweed
gamblings
investory
voltvagon
nanobody
lightie
epidemiologic
cristians

Thanks ENS vision team!!

**Comment by shukaeth** [comment]
Hi thank you, according to https://www.merriam-webster.com/ the words belong to those categories listed below. Unfortunately not all of your names are proper dictionary words, so we cannot add them. See my comments below for details.

**nouns**:

electrocardiogram
banquette
employments
blizzards
pulse-oximeter
urticaria
serendibite
videophone
spacers
westerns
clipboards
chipboard
adolescents
brainstorms
boules
shampoos
exhibitionism
jurists
spectroscopy
sextuplet
binturong
halitosis
habitations
habitation
zooplankton
pentathlon
epidemiologist
epidemiology


**verbs**:
clustering


**adjectives**:
rheumatoid
zooplanktonic
epidemiologic




_will not be added:_


_adverb:
unstoppably (no category yet)

trademark:
dictaphone

no proper words:
micropays
bumder
boatdocks
colostate
jerkweed
gamblings
investory
voltvagon
nanobody
lightie
cristians_

All the best,

shuka.eth

**Comment by D0mainsale** [comment]
ok!!! thanks!! :-

**Comment by D0mainsale** [comment]
not zooplanktonic --> zooplankton.eth


and boatdocks what is? Not noun?

**Comment by D0mainsale** [comment]
boatdocks are 2 words..sorry!
