### ISSUE TITLE
surnames addition

### ISSUE THREAD

**Issue by az19-eth** [Zimtente/ens-collections#894]
Please add these very common surnames (myres is an extremely popular english surname, buzuidenhout & deklerk are common ducth surnames and habli is indonisian. 

{
"bezuidenhout" : "77702999312512871364671392625022858637257205342791332035840967362273180665161",
"myres" : "76124849574617143281612419977422864701719306352184930202122932003391506019086",
"deklerk" : "34243299034335322205201882187746743005181981064952950261465204498192586650882",
"habli", "99008429478727998707380631604597516520240261801487030697990643712339201000196"
}

**Comment by shukaeth** [comment]
hi thx, will be added!
