### ISSUE TITLE
Adding these Surnames to the category “Surnames”

### ISSUE THREAD

**Issue by laidcat** [Zimtente/ens-collections#895]
Explanation why the item should be added to collection: All valid surnames, since hundreds of thousands of people have them, not currently in the category

Collection Name: Surnames

maia,6562718094104777477529490635497616677143776602398002687954165671015581083868
neto,5517211545748215309751306170548199819210489108395809573377773003388093238972
brito,5275396173352764537386375175172184127748935207905370224109093464429525356567
leal,80933583340990441618616735003812808159743996514813210066433383033497073517002
leal,80933583340990441618616735003812808159743996514813210066433383033497073517002
matos,6810265276386439292182246754939296101238583558075487983164624814482518094550
melo,32888515164679283378473895138318008300534159900441583929937199263130364824115
braga,23591184389189755269884403855968755477148246215693090620129816022490153164272
cunha,18806493111898611879830474147621493969959326838303513345707502115108218879379
diniz,34263874491130500429637243301926552635375820151006553518077161456845744764989
felix,84795152226051012396997791673633109972912119989097402241897906665591766345843
froes,14500934240348431829002972524294407335133394626724000972355664875500005162448
leite,57279668565013057735040470271866209197759013984423033363673360176839179641253
moura,68735846229231592612112678122902326195455116662381474101324095486648718995328
viana,70278473781164801027286081497380634363277740918696618510119158931072440984916
ataide,94540846727954836294047171875376493913328882287272364117892339611209816740545
chaves,28317385736415261788256208256774201931102139519195097354478966230264661373252
gardel,73624556588000606030406794913307393294216761019776417399844484177377200039768
macedo,32543023788032106523154235704456267944048946694964671196751682842436162158497
matias,81647084441324828478982887287560468955809134296514930062816397750714114024015
moraes,20597684861296474208105507251537514131939446700518467908196196923246770843387
barreto,10738308993151257831900788043878072735341292635086399195810134094907799564268
batista,88921518871786537723385448738862119866765571052687638469842621988537465203602
bezerra,92888023174442850148163645208225778900037367678691817386064815226249400161352
camargo,14311833374687984435239446094540197481256472768424497538059037714864738824057
candido,23264462458235406757827829882011841349090285825122208573209075886822980994740
cardoso,18250055588261969076724316269089621595430493904663554425892043058878104054700
dantas,113211447369611823540330185980507753412814871275439671644992980403150152240177
freire,113853233306236177978810673334342654875130097550933849254301285326325142517267
menezes,72285732803435752573207120107278633802125368333261388978942210488989649218284
morais,114922529831758506380972496283821515613697826478181257156775886351737898250015
ribeiro,30377210736155639873273471150452691148252149242738709904749789143164419548380
carneiro,81738214223142579724634064350422130819218228175940711368294263807585284221823
marques,112000739175153321026674336743127713352760120981819321879952227384148207235349
moreira,114853069864378189845740911361004545656205436897614468500616987551142657392712
nogueira,23961823849252570100693206570811442676974244987965616902927965919659481925989
pinheiro,74508906395240061004301866549294050729055011150120150941772073486515894824375
queiroz,107977659437487368864084370332474884528339863988808264935816468360859632924031
silveira,47389527055954650638878789144269249103139450859249133831488739251734641444547
goncalves,91812864270756965603350915295425858882513447927633194267967831453002319230378
magalhaes,40129227009241517112418808400152446007343593985387544502367303104257112007954
guimaraes,111758738602481048509933774643717120832864689186764290193763274943817378141410
nepomuceno,24481296437074734549853421117375060174126727833509106042066109846615887269296
cavalcante,108995919483368850309713443381008097131084902756131342388262105543228283840888
nascimento,101683868337422674602067958820167760190159071295809184606092132267346407309890

**Comment by shukaeth** [comment]
Hi, thanks for your request, surnames will be added :)

all the best,

shuka.eth
