### ISSUE TITLE
add to 4 Letter Dictionary please

### ISSUE THREAD

**Issue by darknessline** [Zimtente/ens-collections#900]
Collection Name:
4 Letter Dictionary

Item Name:
cnco.eth

Token ID:
109873169443914640373911811019799995897193861323358214793474710967832616998623

**Comment by shukaeth** [comment]
Hi, unfortunately I wasn't able to find "cnco" on merriam-webster dict, which is our standard for adding names to dict categories.
https://www.merriam-webster.com/dictionary/cnco

All the best,

shuka.eth
