### ISSUE TITLE
Please add these names to the Male Firstnames category

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#903]
Please add these Turkish male names to the Male Firstnames Category.
Thanks in advance!

varol.eth (40172055608799166401182331017605535529122641833218098353943307498822312636870)
hayri.eth (59313819777293460296637049314356116671711379657811568219280456406604175832202)
hursit.eth (76112204548511988580993108936760145856055797893997476958015724087517974986764)
soykan.eth (81714110087427840016679137329090543103674266760971883796169722386465842238782)
seyhun.eth (42955834057463670707390912139159271080377928064571855302616092725385045369193)
sitki.eth (51311609710504898793718156856784118081869405308195773796676768451743242302797)
dirim.eth (81389905620408155739734032989577112869312801538469636589376112343562024221743)
muhlis.eth (61098850801353042635708308946148958296293763288438794987214198065044671277938)
erdener.eth (92046662458523259804030228647709065365313335759312346589407145704261989886482)
lutfu.eth (14189073371586620298295835795105374137157922891323847786007042001868818515694)
erturk.eth (45150605393737029849004720801179157922987077276822177014128186800002041483431)
mujdat.eth (114156130952181323051670651573257047857611339060920078158520048609674564794169)
cemalcan.eth (24390038739459016202554466281401381652665879580192644960652689526190057370093)
esref.eth (881488946354602826159538459009793032693703219109114011226538155336128265579)
unver.eth (11797836451791304433221411137323107900420462579074462565974434684500801325942)
oytunc.eth (19719512194943777698812820903627559033870585885716225332367115010797833639623)
aybars.eth (44794386306813472355780356998803018063960790920350507271189765038297931049971)
omercan.eth (45463963183886805399396702079546473490666393995691275618362259171101474118775)
oguzcan.eth (52658794911654274617262967378894903748098851323676428380450812544559332769492)
gursel.eth (71960907208336900938344898284218160166072065084935644338355673038331015511870)
egecan.eth (96151477169431237760062284318511764128405177058971640575528225653145854058976)
yamac.eth (38146929784270599937026230958251940727241857272471627217823897477186175648022)
gokalp.eth (105109344343393801253135028840066665200523517401245009438745663265818983331702)
guray.eth (37299991542325089629289322831079405324554240356149303462120160189704976306719)
kurtulus.eth (60608527999114533573851088249717411727790077388056177673992810172962807436615)
saffet.eth (54621127520541295336346912074455002098884723128275771194643946201046999539841)

**Comment by shukaeth** [comment]
hi thx, according to forebears.io the following names also are female names - will be added to both categories:
sitki
dirim
mujdat
unver
saffet

all the best,
shuka.eth
