### ISSUE TITLE
Please add these names to the Female Firstnames category

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#904]
Please add these Turkish female names to the Female Firstnames Category.
Thanks in advance!

turna.eth (18031391298010268166573148608584686839023804995886135213700429777250388166350)
belce.eth (16340218764781365778065646449023765867834368010660745042683794679439336616102)
ilgaz.eth (93321589946966929587247440623717660281776155118796786814862483003237483753856)
efsun.eth (28453472501163471458397039506004782915436131416171101193582167340695646207116)
aysil.eth (98176773076110530987625502904607598553810770977835153953029375199233481952484)
ceylin.eth (103587891019910886657955700238468779947481343706728008668632316306702373019157)
benan.eth (6844215597780456489064690811584067122009014114644981875505477616412598456658)
zumrut.eth (17197080350966138480191563345715519851917936220548013936105195765561624080564)
ayben.eth (16039318213477668952507849737866784246224839836592105791486603305352150754205)
cisem.eth (6691214423525486910126313008709434273582626164481082032710235777118778065824)
sueda.eth (77031885800976388935851358181697677901578495740778915902978898973457820070067)
damlacan.eth (64833583458250702616692996718909310729849011413396987644250652091120992411863)
tarcin.eth (34990636748960809918000457524204848328978108055017955676828297473669379531103)
berfu.eth (80251104505001943652817683100837269387598329101430026005363927807625102083833)
bigem.eth (40325720296581017749879361421258533423718527095305766575751908882223712178426)
kumral.eth (93313073462410444211308540594562850487356277530058543119198320747077550282734)
canset.eth (15838118298259067283333398711050140842724431369360858991731986884716974871)
befru.eth (12069349359237910381122966412788377397052709999295789772152148943668324608299)
bercin.eth (64315741729675378521558068697876568887558021092354986802053517678129727843030)
gupse.eth (66877677969871944191242100026342267604433476945682618428452721186712887248635)
bercem.eth (110316313056341515746024978306267711259993710268459965356243308799212225938979)
almina.eth (91975821460191821694211059867411150055797597539902595004657100196297833007730)
cansel.eth (66606471725881427778753338858974005633302954932099545481266835362481800473961)
muzeyyen.eth (105223333315730027119316302979462240164432678918548977011024040647761004850815)
acelya.eth (108427146323349454694858687861827286646299945688433054701908272231480600575711)
ozgul.eth (25510497769842288991503397736656601096799751647207555993164750797659585591864)

**Comment by shukaeth** [comment]
Hi thx, I also added the follwing names to male first names, as forbears.io says they are used for both genders.
