### ISSUE TITLE
Please add these surnames to the Surnames category

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#905]
Please add these Turkish surnames to the Surnames Category. Some of them are also valid as male/female first names, which I have already submitted earlier today. Many thanks for considering my request!

turna.eth (18031391298010268166573148608584686839023804995886135213700429777250388166350)
rehber.eth (68390252761314694161501857231047466480017805246622850291903071918527945246329)
hayri.eth (59313819777293460296637049314356116671711379657811568219280456406604175832202)
karagol.eth (17574423672366766296423856029566298039435749169589218004159629977247329539273)
hursit.eth (76112204548511988580993108936760145856055797893997476958015724087517974986764)
terazi.eth (81987330976130860561928143550155845310863461798468331400533579552167809534691)
soykan.eth (81714110087427840016679137329090543103674266760971883796169722386465842238782)
kursun.eth (53433633675843665106861231820633915996898813787358572597437428341584989396540)
aybars.eth (44794386306813472355780356998803018063960790920350507271189765038297931049971)
esref.eth (881488946354602826159538459009793032693703219109114011226538155336128265579)
seyhun.eth (42955834057463670707390912139159271080377928064571855302616092725385045369193)
sitki.eth (51311609710504898793718156856784118081869405308195773796676768451743242302797)
komutan.eth (18067292595081025705236224397017656612049569654509155131870838580689063848040)
tarcin.eth (34990636748960809918000457524204848328978108055017955676828297473669379531103)
saffet.eth (54621127520541295336346912074455002098884723128275771194643946201046999539841)
kurtulus.eth (60608527999114533573851088249717411727790077388056177673992810172962807436615)
gulter.eth (42578283216388463530778028068324589750723170387648875794938224836323696522414)
acelya.eth (108427146323349454694858687861827286646299945688433054701908272231480600575711)
gursel.eth (71960907208336900938344898284218160166072065084935644338355673038331015511870)
yamac.eth (38146929784270599937026230958251940727241857272471627217823897477186175648022)
efsun.eth (28453472501163471458397039506004782915436131416171101193582167340695646207116)
guray.eth (37299991542325089629289322831079405324554240356149303462120160189704976306719)
ceylin.eth (103587891019910886657955700238468779947481343706728008668632316306702373019157)
ortaca.eth (85747337491239770679216680553079680002402413383163289991958599774578739331055)
gocek.eth (52843362282045725639407162310264333866865149643423288710194825549161875565709)
oguzcan.eth (52658794911654274617262967378894903748098851323676428380450812544559332769492)
toptan.eth (42580673756409324621087737576444933515952176869056626212618829940070921282954)
ozgul.eth (25510497769842288991503397736656601096799751647207555993164750797659585591864)
gokalp.eth (105109344343393801253135028840066665200523517401245009438745663265818983331702)
oytunc.eth (19719512194943777698812820903627559033870585885716225332367115010797833639623)
unver.eth (11797836451791304433221411137323107900420462579074462565974434684500801325942)
kumral.eth (93313073462410444211308540594562850487356277530058543119198320747077550282734)
cansel.eth (66606471725881427778753338858974005633302954932099545481266835362481800473961)
ilgaz.eth (93321589946966929587247440623717660281776155118796786814862483003237483753856)
dirim.eth (81389905620408155739734032989577112869312801538469636589376112343562024221743)
erdener.eth (92046662458523259804030228647709065365313335759312346589407145704261989886482)
zumrut.eth (17197080350966138480191563345715519851917936220548013936105195765561624080564)
erturk.eth (45150605393737029849004720801179157922987077276822177014128186800002041483431)
varol.eth (40172055608799166401182331017605535529122641833218098353943307498822312636870)

**Comment by shukaeth** [comment]
hi thx will be added with the next sync
