### ISSUE TITLE
Please add this firstname in Male Firstnames category

### ISSUE THREAD

**Issue by domainskeeper** [Zimtente/ens-collections#907]
lionardo.eth (original name of Leoardo da Vinci)
Token ID: 37599169509889379524543726914433825525558865614844041139533117361467251997520

Italian Wikipedia source:
https://it.wikipedia.org/wiki/Leonardo_da_Vinci#Le_origini_e_la_famiglia

![screenshot-it wikipedia org-2022 12 02-11_31_06](https://user-images.githubusercontent.com/119666003/205273107-0d09ec30-4559-4be4-a1e2-d2aa8e881351.png)

**Comment by shukaeth** [comment]
thx will be added with next sync
