### ISSUE TITLE
Want to add these plural nouns to English nouns category. Thank you!

### ISSUE THREAD

**Issue by bly99** [Zimtente/ens-collections#908]
**backstairs**
this one is adjective
https://www.merriam-webster.com/dictionary/backstairs
Token ID: 25543346298819613145905160613046570339421692507065804986322928942463076409666

**fetishists**
fetishist (plural fetishists)
One who has a sexual fetish.
(archaic) A believer in magical fetishes or talismans.
https://en.wiktionary.org/wiki/fetishist#:~:text=fetishist%20(plural%20fetishists)
https://www.merriam-webster.com/dictionary/fetishists
Token ID: 2731268644477907078113940568560433680958969112127309684944709598971692973384

**pessimists**
https://www.merriam-webster.com/dictionary/pessimists
https://www.britannica.com/dictionary/pessimist#:~:text=pessimist%20%2F%CB%88p%C9%9Bs%C9%99m%C9%AAst%2F%20noun,plural%20pessimists
Token ID: 107729122148320546666490313356145020520524616174395872621463122801214621324053

**cactuses**
Noun
cactus (plural cacti or cactuses )
https://www.merriam-webster.com/dictionary/cactuses
https://www.britannica.com/dictionary/boulevard#:~:text=boulevard%20%2F%CB%88b%CA%8Al%C9%99%CB%8Cv%C9%91%C9%9Ad%2F%20noun,%2F%CB%88b%CA%8Al%C9%99%CB%8Cv%C9%91%C9%9Ad%2F
Token ID: 14925145803637290695339175511663504862088985983502491848128673855044166277176

**burnings**
Noun
burning (plural burnings)
A fire.
The burnings continued all day.
https://en.wiktionary.org/wiki/burning
https://www.merriam-webster.com/dictionary/burning
Token ID: 37126417027447720197353135040686601847774904879384785105154711839837123659306

**humiliations**
https://www.collinsdictionary.com/dictionary/english/humiliation#:~:text=Word%20forms%3A%20plural%20humiliations,uncountable%20noun
https://www.merriam-webster.com/dictionary/humiliations
Token ID: 64897538637306585625703677099608876113676777787672363607390989017767203784224

**adorers**
Noun
adorer (plural adorers)
Someone who adores.
https://en.wiktionary.org/wiki/adorer
https://www.merriam-webster.com/dictionary/adorers
Token ID: 64739649390785404876136572552083021342401109600420094082402111620230698017520

**firebombs**
Noun
firebomb (plural firebombs)
A weapon that causes fire, an incendiary weapon.
A Molotov cocktail is a simple firebomb.
https://en.wiktionary.org/wiki/firebomb
https://www.merriam-webster.com/dictionary/firebombs
Token ID: 105525045488440271163984690676034827118213234271684322888092100526210853932259

**minuses**
minus /ˈmaɪnəs/ noun
plural minuses
1.informal : a problem or disadvantage
https://www.britannica.com/dictionary/minus
https://www.merriam-webster.com/dictionary/minuses
Token ID: 1860274914058237070311908730748228118500033799544312926086923715623439764840

**racings**
Noun
racing (countable and uncountable, plural racings)
The sport of competing in races.
https://en.wiktionary.org/wiki/racing#:~:text=Noun,sport%20of%20competing%20in%20races.
https://www.merriam-webster.com/dictionary/racings
Token ID: 111589100722744314745909201901530737786360987627420707278224831808202888972726

**sexologists**
https://www.collinsdictionary.com/dictionary/english/sexologist#:~:text=Word%20forms%3A%20plural%20sexologists,person%20who%20studies%20sexual%20relationships.
https://www.merriam-webster.com/dictionary/sexologists
Token ID: 47184760964756753744476373011414210422238048557214700068376509373527032263026

**sexists**
noun
sexist (plural sexists)
1.(countable) A sexist is a person who believes that men and women should be treated differently.
https://simple.wiktionary.org/wiki/sexist#:~:text=Plural,women%20should%20be%20treated%20differently.
https://www.merriam-webster.com/dictionary/sexists
Token ID: 101397870062390870204163116062156058543306817862928503190768231633589757910853

**egoists**
Noun
egoist (plural egoists)
1.An advocate of egoism.
2.An egocentric or self-centered person.
https://en.wiktionary.org/wiki/egoist
https://www.merriam-webster.com/dictionary/egoists
Token ID: 82284979410341292602867432125567951738749448291063221736017612010016907691660

**Comment by shukaeth** [comment]
Hi thx for your suggestions and all the links! helps a lot :) will be added with the next sync

all the best

shuka.eth
