### ISSUE TITLE
Add 0y99Club

### ISSUE THREAD

**Issue by OatMealShoes** [Zimtente/ens-collections#91]
{
  "name": "0y99 Club",
  "slug": "0y99club"
  "description": "ENS Adresses, digits 0y01-0y99.",
  "twitter": "0y99Club",
  "logo": "(https://user-images.githubusercontent.com/108674968/177161457-f8405e34-0272-47d2-a75a-d21ce15f66ec.png)",
  "csv": [“(https://github.com/Zimtente/ens-collections/files/9039684/0yClub.csv)”]
}

**Comment by tunnckoCore** [comment]
No.
