### ISSUE TITLE
Please add the following FirstNames and Surnames.

### ISSUE THREAD

**Issue by yutt1115** [Zimtente/ens-collections#910]
SurNames

brugman.eth
TokenId : 36464136547430751707438013549025808862266563385486266820406937056148527117826
CreateDate : 2017/07/04

effinger.eth
TokenId : 53761978828637740312531233190633318351949080942543474200066461569565702039405
CreateDate : 2017/07/15

herdman.eth
TokenId : 12754503731022540487384093795360061174009514392497080858492247320588783227550
CreateDate : 2017/07/19

FirstName

haiyong.eth
TokenId : 41500308998479822009647714299974974505869168832707940874041888037407157862532
CreateDate : 2017/08/30

**Comment by shukaeth** [comment]
Hi thx, will be added!
