### ISSUE TITLE
Please add uds.eth to 3 Letter Dictionary Category

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#911]
Please add uds.eth to 3 Letter Dictionary category --> https://www.ens.vision/categories/3-letter-dictionary

It is a valid scrabble and dictionary word.

Reference:
https://www.collinsdictionary.com/dictionary/english/uds
https://word-finder.mobi/is-uds-valid-scrabble-word

uds.eth
Token ID: 109170854470970088842633851789460610795419847847875782209868017094615182457678

Thank you!

**Comment by shukaeth** [comment]
Hi for 3L dict category we only add words which are listed on merriam webster - unfortunately I could'nt find uds there.. :(

https://www.merriam-webster.com/dictionary/uds

all the best,

shuka.eth
