### ISSUE TITLE
Please add kyn.eth to 3 Letters First Names, Female First Names and Male First Names categories.

### ISSUE THREAD

**Issue by subwd** [Zimtente/ens-collections#912]
https://www.babycenter.com/baby-names/details/kyn-807015

https://www.babycenter.com/baby-names/details/kyn-715755

Thank you!

**Comment by shukaeth** [comment]
Hi,

according to forebears.io kyn is also a surname - will be added to:
surnames
3 Letters First Names
Female First Names
Male First Names

all the best,

shuka.eth
