### ISSUE TITLE
Please add the following names to the relevant categories indicated

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#915]
rup.eth (3 Letter First Names and Surnames)
Token ID: 87199733717237675950934523627216541458190156937590947349683173033066743472304
https://forebears.io/forenames/rup
https://forebears.io/surnames/rup

islamov.eth (Surnames)
Token ID: 82226861137506965299910087848580150826852267987142481940869218973929091251556
https://forebears.io/surnames/islamov

islomov.eth (Surnames)
Token ID: 44445947198430215443121483626067165475566674614932504829830555786542142847763
https://forebears.io/surnames/islomov

islomova.eth (Surnames)
Token ID: 36079130282561663245960729281685306525312174830269132940744627872137985403798
https://forebears.io/surnames/islomova

Thank you!
ens360.eth

**Comment by shukaeth** [comment]
thx will be added =) 

All the best,
shuka.eth
