### ISSUE TITLE
Please add hel.eth to the relevant categories indicated

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#919]
hel.eth
Token ID: 104584652645143592294895606757135389928117783442243184365828916179092694108004

3 Letter Dictionary & English Nouns
https://www.merriam-webster.com/dictionary/Hel

3 Letter First Names & Surnames
https://forebears.io/x/forenames/hel
https://forebears.io/surnames/hel

Thank you!

**Comment by shukaeth** [comment]
thx - will also be added to female first names and male first names as it can be both according to forebears. ;)
