### ISSUE TITLE
Add 3 Digits Hebrew Club

### ISSUE THREAD

**Issue by ensenjoyor** [Zimtente/ens-collections#92]
Metadata for 3 Digits Hebrew Club:

{
"name": "3 Digits Hebrew Club",
"slug": "3digits-hebrew-club"
"description": "729 Juxtaposed Numbers written in Hebrew.",
"twitter": "@3DigitsHebrew",
"website": "-",
"chat": "https://discord.com/invite/v3udrSfe",
"logo": "3digits-hebrew-club.png",
"csv": ["3digits-hebrew-club.csv"]
}

File:
[3digits-hebrew-club.csv](https://github.com/Zimtente/ens-collections/files/9039791/3digits-hebrew-club.csv)

Logo:
![3digits-hebrew-club](https://user-images.githubusercontent.com/108676010/177162072-a7d651e8-2b06-4858-9573-496602493793.jpg)

**Comment by bigwarz** [comment]
Hey ! please change the discord to this one :) : thats the right one @CryptoGatsu 

https://discord.gg/GrEDQNKt4M
