### ISSUE TITLE
Please add cid.eth to the relevant categories indicated

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#920]
cid.eth
Token ID: 26272055167285356633110427977470076488093772412378599429168795717177059552189

3 Letter Dictionary
https://www.merriam-webster.com/dictionary/cid

3 Letter First Names & Surnames
https://forebears.io/x/forenames/cid
https://forebears.io/surnames/cid

Thank you!

**Comment by shukaeth** [comment]
Hi thx will be also added to male first names :)

https://forebears.io/x/forenames/cid
