### ISSUE TITLE
Please add these three domains to their categories.

### ISSUE THREAD

**Issue by nuevas2012** [Zimtente/ens-collections#921]
Female Firstnames
kyleen.eth 
Token ID: 30489968653358678144368625813741499403924418107651749656199531398201443820126
![image](https://user-images.githubusercontent.com/79742932/209930340-a5f958ef-7d0c-45b5-96af-0f1da001d1a8.png)

English Adjectives
exclamatory.eth
Token ID: 29062820991955076368028332166186834540686218893476040038585456491491481664512
![image](https://user-images.githubusercontent.com/79742932/209930586-532165a4-c3da-47d3-91c6-35b4fd849f05.png)

English Adjectives
acerate.eth
Token ID: 109914697591879748760654853346507522659528920585056151397767800088711561487164
![image](https://user-images.githubusercontent.com/79742932/209931383-13ccf627-180f-48ef-8807-88677617465e.png)

**Comment by shukaeth** [comment]
Hey,

I can approve those for the categories you mentioned:

kyleen (https://forebears.io/x/forenames/kyleen) - female first names
exclamatory (https://www.merriam-webster.com/dictionary/exclamatory) - english adjectives
acerate (https://www.merriam-webster.com/dictionary/acerate) - english adjectives

will be added with the next sync :)

all the best,

shuka.eth
