### ISSUE TITLE
Please add these names to the 3 Letter First Names Category

### ISSUE THREAD

**Issue by ens360** [Zimtente/ens-collections#926]
ján.eth
Token ID: 14616044033461492335150378995269730596292187651346042009387088754955942866536
https://forebears.io/forenames/ján

éva.eth
Token ID: 22950483761307944646851801898521429705073246979054154100136183215228973188846
https://forebears.io/forenames/éva

Thank you!

**Comment by shukaeth** [comment]
thx will be added
