### ISSUE TITLE
request to add to Female Firstnames, Male Firstnames and Surnames category

### ISSUE THREAD

**Issue by nuevas2012** [Zimtente/ens-collections#927]
Domain: amelework.eth

Token ID: 49438945617833713510286967996230789892258521179939725052495570881025850942978

Link 1:  https://forebears.io/search?q=amelework&meaning=genealogy-names-surnames
Link 2: https://www.nameslook.com/amelework/
Link 3: https://forebears.io/surnames/amelework
Link 4: https://forebears.io/x/forenames/amelework
![image](https://user-images.githubusercontent.com/79742932/212522043-98e5e2e5-fe10-45a2-83d3-ca9642f0d5cd.png)

![image](https://user-images.githubusercontent.com/79742932/212522173-630fb0a5-02f9-4938-992d-fb0503670484.png)

**Comment by shukaeth** [comment]
Hi, according to forebears it is a surname and female first name - will be added to those categories!

all the best, 
shuka.eth
