### ISSUE TITLE
request to add to Surnames, Male Firstnames and Female Firstnames category

### ISSUE THREAD

**Issue by nuevas2012** [Zimtente/ens-collections#930]
Domain: ratnayake.eth

Token ID: 18643961814429161629040330066462507029573937347833348048609207183743210552537

Link 1: https://forebears.io/search?q=ratnayake&meaning=genealogy-names-surnames
Link 2: https://forebears.io/surnames/ratnayake
Link 3: https://forebears.io/x/forenames/ratnayake

Thank you very much.

![image](https://user-images.githubusercontent.com/79742932/213665825-574ba09d-112c-40b3-82c6-0a0e1d5578a4.png)
![image](https://user-images.githubusercontent.com/79742932/213665979-8f5b78f1-60a6-4279-aa88-074bdbf82ddd.png)

**Comment by shukaeth** [comment]
thank you will be added with next sync =)
