### ISSUE TITLE
Noun Addition

### ISSUE THREAD

**Issue by THEREALMON** [Zimtente/ens-collections#934]
Gm Ser can we add Disabler as noun? thanks in advance https://www.merriam-webster.com/dictionary/disabler 

Token Id: 79897828790392838784103502106044824914343965189375824375653900204216458110294

Gyver as firstname 

Token Id: 19741687250863343558240057208078585621709324727612450789435217486291002490637

thank you..

**Comment by shukaeth** [comment]
Thank will be added with next Update!

**Comment by THEREALMON** [comment]
tia..
