### ISSUE TITLE
Add Hyphens-NNN Club, please. Metadata and Files ready to go.

### ISSUE THREAD

**Issue by 8-1-8** [Zimtente/ens-collections#98]
Hello ENS.vision team! Thank you for all that you do!  You have the single most valuable ENS tool out there. I cannot thank you enough!

Here's the info for the N-N-N Club. Please let me know if you need anything else.

Metadata:

{
"name": "Hyphens-NNN",
"slug": "hyphens-nnn",
"description": "Hyphenated N-N-N ENS domains 0-0-0 to 9-9-9",
"twitter": "@HyphensNNNClub",
"chat": "https://discord.com/channels/970489721602080798/970632628652900372",
"logo": "hyphens-nnn.png",
"csv": ["hyphens-nnn.csv"]
}

Files:
[hyphens-nnn.csv](https://github.com/Zimtente/ens-collections/files/9056802/hyphens-nnn.csv)

![hyphens-nnn](https://user-images.githubusercontent.com/108684697/177191012-76e771c8-b25b-4835-9a7b-35a9daec805a.png)

**Comment by tunnckoCore** [comment]
Okay, good. Thanks.

**Comment by psadier** [comment]
Thanks

**Comment by 8-1-8** [comment]
CSV updated. 1-0-0 was duplicate.

**Comment by 8-1-8** [comment]
Thank you guys! Does this mean the category should be live on ens.vision now or do we still have something pending? Thanks a million!
